[project]
id      = "github.com/gmlewis/picogk/shapes"
version = "0.2.0"
license = "Apache-2.0"

[dependencies]
"github.com/gmlewis/picogk/picogkffi-gos" = { path = "../picogkffi" }

[rust-bindings]
picogkffi = { path = "../picogkffi/picogkffi" }

