#!/usr/bin/env python3
"""Generate an idiomatic Go SDK for the Blender MCP server.

Parses all MCP tool definitions from ~/Projects/Blender/blender_mcp/mcp/blmcp/tools/*.py
and emits a complete Go package (blender) with:
  - A Client struct that manages the MCP stdio subprocess
  - Builder-pattern method functions for all tools
  - Full doc comments on every function
  - A README.md with usage examples

Usage:
    ./scripts/generate-go-blender-sdk.py [--output DIR] [--verbose]

Output goes to sdk/go/blender/ by default.
"""

from __future__ import annotations

import argparse
import ast
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

GENERATED_HEADER = "// Code generated by scripts/generate-go-blender-sdk.py — DO NOT EDIT.\n"

BLENDER_MCP_DIR = Path.home() / "Projects" / "Blender" / "blender_mcp" / "mcp" / "blmcp" / "tools"


# ---------------------------------------------------------------------------
# Tool definitions
# ---------------------------------------------------------------------------

@dataclass
class Param:
    name: str
    py_type: str
    description: str
    default: str | None
    has_default: bool


@dataclass
class ToolDef:
    name: str
    description: str
    category: str
    params: list[Param] = field(default_factory=list)

    @property
    def required_params(self) -> list[Param]:
        return [p for p in self.params if not p.has_default]

    @property
    def optional_params(self) -> list[Param]:
        return [p for p in self.params if p.has_default]


# ---------------------------------------------------------------------------
# Python type -> Go type mapping
# ---------------------------------------------------------------------------

def go_type(py_type: str) -> str:
    """Map a Python type to its Go equivalent."""
    base = py_type.strip().rstrip("]").lstrip("[")
    if py_type.startswith("list["):
        inner = py_type[5:-1]
        return f"[]{go_type(inner)}"
    if py_type.startswith("dict["):
        return "map[string]any"
    if py_type in ("str", "str | None"):
        return "string"
    if py_type in ("int", "int | None"):
        return "int"
    if py_type in ("bool",):
        return "bool"
    if py_type in ("float",):
        return "float64"
    if py_type in ("object", "any"):
        return "any"
    # Literal types (enum) -> string
    if py_type.startswith("Literal["):
        return "string"
    # Named type aliases (e.g., AreaUIType) -> string
    if py_type in ("AreaUIType",):
        return "string"
    return "any"


def go_zero(py_type: str) -> str:
    """Return the Go zero value for a type."""
    if py_type.startswith("list["):
        return "nil"
    if py_type.startswith("dict["):
        return "nil"
    if py_type in ("str", "str | None"):
        return '""'
    if py_type in ("int", "int | None"):
        return "0"
    if py_type in ("bool",):
        return "false"
    if py_type in ("float",):
        return "0"
    if py_type.startswith("Literal["):
        return '""'
    return "nil"


# ---------------------------------------------------------------------------
# Name conversion
# ---------------------------------------------------------------------------

def go_method_name(tool_name: str) -> str:
    """Convert a snake_case tool name to PascalCase Go method name."""
    parts = tool_name.split("_")
    # Go initialism rules
    initialisms = {
        "api": "API", "json": "JSON", "id": "ID", "ids": "IDs",
        "url": "URL", "3d": "3D", "vdb": "VDB",
    }
    result = []
    for p in parts:
        lower = p.lower()
        if lower in initialisms:
            result.append(initialisms[lower])
        elif lower == "for":
            result.append("For")
        elif lower == "cli":
            result.append("CLI")
        elif lower == "blend":
            result.append("Blend")
        elif lower == "file":
            result.append("File")
        else:
            result.append(p.capitalize())
    name = "".join(result)
    # Clean up: "GetBlendfileSummary" -> "GetBlendFileSummary"
    name = re.sub(r"Blendfile", "BlendFile", name)
    name = re.sub(r"Tabby", "TabBy", name)
    return name


def go_struct_name(tool_name: str) -> str:
    """Convert a snake_case tool name to PascalCase Go struct name."""
    return go_method_name(tool_name) + "Request"


def go_field_name(param_name: str) -> str:
    """Convert snake_case param name to Go-idiomatic exported field name."""
    parts = param_name.split("_")
    initialisms = {
        "id": "ID", "ids": "IDs", "api": "API", "json": "JSON",
        "url": "URL", "3d": "3D",
    }
    result = []
    for p in parts:
        lower = p.lower()
        if lower in initialisms:
            result.append(initialisms[lower])
        elif lower == "ui":
            result.append("UI")
        elif lower == "type":
            result.append("Type")
        else:
            result.append(p.capitalize())
    return "".join(result)


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

def _find_tool_files() -> list[Path]:
    """Find all non-template, non-toolcode Python files in the tools directory."""
    files = []
    for f in sorted(BLENDER_MCP_DIR.glob("*.py")):
        if f.name.startswith("_"):
            continue
        if f.name.endswith("_toolcode.py"):
            continue
        files.append(f)
    return files


def _extract_docstring(source: str) -> str:
    """Extract the docstring from a function's source code."""
    try:
        tree = ast.parse(source)
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.body and isinstance(node.body[0], ast.Expr):
                    val = node.body[0].value
                    if isinstance(val, (ast.Constant, ast.Str)):
                        s = val.value if isinstance(val, ast.Constant) else val.s
                        return s.strip()
    except SyntaxError:
        pass
    return ""


def _parse_function_def(source: str) -> tuple[str, str, list[Param]]:
    """Parse a Python function definition, returning (name, docstring, params)."""
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if node.name.startswith("_"):
            continue
        if not any(isinstance(d, ast.Name) and d.id == "mcp"
                    for decorator in node.decorator_list
                    for d in ([decorator] if isinstance(decorator, ast.Name)
                              else ([decorator.func] if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Name) else []))):
            # Check for @mcp.tool(...) pattern
            pass  # We'll include all functions that have decorators with 'tool'

        # Extract docstring
        docstring = ""
        if node.body and isinstance(node.body[0], ast.Expr):
            val = node.body[0].value
            if isinstance(val, (ast.Constant, ast.Str)):
                docstring = val.value if isinstance(val, ast.Constant) else val.s

        # Extract parameters
        params = []
        args = node.args
        # Build defaults mapping (defaults align from the end)
        num_defaults = len(args.defaults)
        num_args = len(args.args)
        for i, arg in enumerate(args.args):
            if arg.arg == "self":
                continue
            py_type = ""
            if arg.annotation:
                if isinstance(arg.annotation, ast.Name):
                    py_type = arg.annotation.id
                elif isinstance(arg.annotation, ast.Subscript):
                    if isinstance(arg.annotation.value, ast.Name):
                        base = arg.annotation.value.id
                        if isinstance(arg.annotation.slice, ast.Name):
                            inner = arg.annotation.slice.id
                        elif isinstance(arg.annotation.slice, ast.Tuple):
                            inner = ", ".join(
                                e.id if isinstance(e, ast.Name) else ast.dump(e)
                                for e in arg.annotation.slice.elts
                            )
                        else:
                            inner = ast.dump(arg.annotation.slice)
                        py_type = f"{base}[{inner}]"
                elif isinstance(arg.annotation, ast.BinOp):
                    # Union types: str | None
                    left = arg.annotation.left
                    right = arg.annotation.right
                    left_str = left.id if isinstance(left, ast.Name) else ast.dump(left)
                    right_str = right.id if isinstance(right, ast.Name) else ast.dump(right)
                    py_type = f"{left_str} | {right_str}"

            default_idx = i - (num_args - num_defaults)
            if default_idx >= 0:
                default_node = args.defaults[default_idx]
                if isinstance(default_node, ast.Constant):
                    default_val = repr(default_node.value)
                elif isinstance(default_node, ast.NameConstant):
                    default_val = str(default_node.value)
                elif isinstance(default_node, ast.Attribute):
                    default_val = ast.dump(default_node)
                else:
                    default_val = ast.dump(default_node)
                params.append(Param(
                    name=arg.arg,
                    py_type=py_type,
                    description="",
                    default=default_val,
                    has_default=True,
                ))
            else:
                params.append(Param(
                    name=arg.arg,
                    py_type=py_type,
                    description="",
                    default=None,
                    has_default=False,
                ))

        return node.name, docstring, params

    return "", "", []


def parse_all_tools() -> list[ToolDef]:
    """Parse all Blender MCP tools from the Python source files."""
    tools = []

    for filepath in _find_tool_files():
        source = filepath.read_text()

        # We need to find the functions registered as MCP tools
        # Each file typically has one or two @mcp.tool() decorated functions
        # Parse the AST to find them
        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue

        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            if node.name.startswith("_"):
                continue
            # Check for @mcp.tool decorator
            has_tool_decorator = False
            for decorator in node.decorator_list:
                if isinstance(decorator, ast.Call):
                    func = decorator.func
                    if isinstance(func, ast.Attribute) and func.attr == "tool":
                        has_tool_decorator = True
                        break
            if not has_tool_decorator:
                continue

            # Extract docstring
            docstring = ""
            if node.body and isinstance(node.body[0], ast.Expr):
                val = node.body[0].value
                if isinstance(val, (ast.Constant, ast.Str)):
                    docstring = val.value if isinstance(val, ast.Constant) else val.s
                    # Clean up: strip leading/trailing whitespace, normalize newlines
                    docstring = " ".join(docstring.split())

            # Extract parameters
            params = []
            args = node.args
            num_defaults = len(args.defaults)
            num_args = len(args.args)
            for i, arg in enumerate(args.args):
                if arg.arg == "self":
                    continue
                py_type = ""
                if arg.annotation:
                    py_type = _ast_type_to_str(arg.annotation)

                default_idx = i - (num_args - num_defaults)
                if default_idx >= 0:
                    default_node = args.defaults[default_idx]
                    default_val = _ast_value_to_str(default_node)
                    params.append(Param(
                        name=arg.arg,
                        py_type=py_type,
                        description="",
                        default=default_val,
                        has_default=True,
                    ))
                else:
                    params.append(Param(
                        name=arg.arg,
                        py_type=py_type,
                        description="",
                        default=None,
                        has_default=False,
                    ))

            # Determine category from filename
            category = _category_from_filename(filepath.stem)

            tools.append(ToolDef(
                name=node.name,
                description=docstring,
                category=category,
                params=params,
            ))

    return tools


def _ast_type_to_str(node: ast.AST) -> str:
    """Convert an AST type annotation node to a string."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Constant):
        return str(node.value)
    if isinstance(node, ast.Subscript):
        base = _ast_type_to_str(node.value)
        inner = _ast_type_to_str(node.slice)
        return f"{base}[{inner}]"
    if isinstance(node, ast.Tuple):
        parts = [_ast_type_to_str(e) for e in node.elts]
        return ", ".join(parts)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        left = _ast_type_to_str(node.left)
        right = _ast_type_to_str(node.right)
        return f"{left} | {right}"
    if isinstance(node, ast.Attribute):
        return f"{_ast_type_to_str(node.value)}.{node.attr}"
    return ast.dump(node)


def _ast_value_to_str(node: ast.AST) -> str:
    """Convert an AST default value node to a string."""
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, ast.NameConstant):
        return str(node.value)
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return f"{_ast_value_to_str(node.value)}.{node.attr}"
    return ast.dump(node)


def _category_from_filename(stem: str) -> str:
    """Determine category from the tool filename."""
    if stem.startswith("get_blendfile_summary"):
        return "Blend File"
    if stem.startswith("get_screenshot"):
        return "Screenshot"
    if stem.startswith("execute_blender_code"):
        return "Execute"
    if stem.startswith("get_python_api_docs") or stem.startswith("search_api_docs"):
        return "API Docs"
    if stem.startswith("search_manual_docs"):
        return "Manual Docs"
    if stem.startswith("get_objects_summary") or stem.startswith("get_object_detail"):
        return "Objects"
    if stem.startswith("render_"):
        return "Render"
    if stem.startswith("jump_to_tab"):
        return "Workspace"
    if stem.startswith("jump_to_view3d"):
        return "Viewport"
    return "Other"


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def _go_struct_tag(name: str) -> str:
    """Generate a Go struct tag with backtick delimiters."""
    return '`' + name + '`'


def gen_client_go(tools: list[ToolDef]) -> str:
    """Generate the core client.go file."""
    BQ = '`'  # backtick character
    NL = "'\\n'"  # produces '\n' in Go output

    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("package blender\n")
    lines.append("import (")
    lines.append('\t"bufio"')
    lines.append('\t"context"')
    lines.append('\t"encoding/json"')
    lines.append('\t"fmt"')
    lines.append('\t"io"')
    lines.append('\t"log"')
    lines.append('\t"os"')
    lines.append('\t"os/exec"')
    lines.append('\t"path/filepath"')
    lines.append('\t"strings"')
    lines.append('\t"sync"')
    lines.append(")\n")

    # Client type and doc comment
    lines.append("// Client manages a connection to the Blender MCP server.")
    lines.append("// It launches the server as a subprocess and communicates via JSON-RPC over stdio.")
    lines.append("//")
    lines.append("// Usage:")
    lines.append("//")
    lines.append("//\t// Uses default server (blender-mcp)")
    lines.append("//\tclient, err := blender.NewClient(ctx, \"\")")
    lines.append("//\tdefer client.Close()")
    lines.append("//\t// Or specify a custom path:")
    lines.append("//\tclient, err := blender.NewClient(ctx, \"/path/to/blender-mcp\")")
    lines.append("//\t// Execute Python code in Blender")
    lines.append("//\tres, err := client.ExecuteBlenderCode(blender.ExecuteBlenderCodeRequest{")
    lines.append("//\t\tCode: \"import bpy; result = {'objects': [o.name for o in bpy.data.objects]}\",")
    lines.append("//\t})")
    lines.append("type Client struct {")
    lines.append("\tctx       context.Context")
    lines.append("\tcmd       *exec.Cmd")
    lines.append("\tstdin     io.WriteCloser")
    lines.append("\tstdout    *bufio.Reader")
    lines.append("\tmu        sync.Mutex")
    lines.append("\tmsgID     int")
    lines.append("\tserverBin string")
    lines.append("}\n")

    lines.append("// DefaultServerBin is the default command to launch the Blender MCP server.")
    lines.append("// It can be overridden by passing a non-empty path to NewClient.")
    lines.append('const DefaultServerBin = "uv"\n')
    lines.append("// DefaultServerArgs are the default arguments for the Blender MCP server.")
    lines.append('var DefaultServerArgs = []string{"--directory", expandPath("~/Projects/Blender/blender_mcp/mcp/blmcp"), "run", "blender-mcp"}\n')

    # NewClient
    lines.append("// NewClient launches the Blender MCP server and returns a Client.")
    lines.append("// If serverBin is empty, uses the default (uv run blender-mcp).")
    lines.append("// If serverBin is a directory, uses uv --directory <dir> run blender-mcp.")
    lines.append("func NewClient(ctx context.Context, serverBin string) (*Client, error) {")
    lines.append('\tif serverBin == "" {')
    lines.append("\t\treturn newClientWithArgs(ctx, DefaultServerBin, DefaultServerArgs, \"\")")
    lines.append("\t}")
    lines.append("\tserverBin = expandPath(serverBin)")
    lines.append("\t// If it's a directory, use uv --directory <dir> run blender-mcp")
    lines.append('\tif info, err := os.Stat(serverBin); err == nil && info.IsDir() {')
    lines.append('\t\treturn newClientWithArgs(ctx, "uv", []string{"--directory", serverBin, "run", "blender-mcp"}, "")')
    lines.append("\t}")
    lines.append("\t// Otherwise treat as a direct binary/command")
    lines.append("\treturn newClientWithArgs(ctx, serverBin, nil, \"\")")
    lines.append("}\n")

    # newClientWithArgs
    lines.append("func newClientWithArgs(ctx context.Context, bin string, args []string, workDir string) (*Client, error) {")
    lines.append("\tcmd := exec.CommandContext(ctx, bin, args...)")
    lines.append("\tif workDir != \"\" {")
    lines.append("\t\tcmd.Dir = workDir")
    lines.append("\t}")
    lines.append("\tstdin, err := cmd.StdinPipe()")
    lines.append('\tif err != nil {')
    lines.append('\t\treturn nil, fmt.Errorf("creating stdin pipe: %w", err)')
    lines.append("\t}")
    lines.append("\tstdout, err := cmd.StdoutPipe()")
    lines.append('\tif err != nil {')
    lines.append('\t\treturn nil, fmt.Errorf("creating stdout pipe: %w", err)')
    lines.append("\t}")
    lines.append('\tif err := cmd.Start(); err != nil {')
    lines.append('\t\treturn nil, fmt.Errorf("starting server: %w", err)')
    lines.append("\t}")
    lines.append("\tc := &Client{")
    lines.append("\t\tctx:       ctx,")
    lines.append("\t\tcmd:       cmd,")
    lines.append("\t\tstdin:     stdin,")
    lines.append("\t\tstdout:    bufio.NewReader(stdout),")
    lines.append("\t\tserverBin: bin,")
    lines.append("\t}")
    lines.append("\t// Perform MCP initialize handshake")
    lines.append('\tif err := c.initialize(); err != nil {')
    lines.append("\t\tcmd.Process.Kill()")
    lines.append('\t\treturn nil, fmt.Errorf("initialize handshake: %w", err)')
    lines.append("\t}")
    lines.append("\treturn c, nil")
    lines.append("}\n")

    # Close
    lines.append("// Close shuts down the MCP server process.")
    lines.append("func (c *Client) Close() error {")
    lines.append("\tc.mu.Lock()")
    lines.append("\tdefer c.mu.Unlock()")
    lines.append("\tif c.stdin != nil {")
    lines.append("\t\tc.stdin.Close()")
    lines.append("\t}")
    lines.append("\tif c.cmd != nil && c.cmd.Process != nil {")
    lines.append("\t\tdone := make(chan struct{})")
    lines.append("\t\tgo func() {")
    lines.append("\t\t\tc.cmd.Wait()")
    lines.append("\t\t\tclose(done)")
    lines.append("\t\t}()")
    lines.append("\t\tselect {")
    lines.append("\t\tcase <-done:")
    lines.append("\t\tcase <-c.ctx.Done():")
    lines.append("\t\t\tc.cmd.Process.Kill()")
    lines.append("\t\t\t<-done")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn nil")
    lines.append("}\n")

    # expandPath
    lines.append("// expandPath expands a leading ~ to the user's home directory.")
    lines.append("func expandPath(path string) string {")
    lines.append('\tif strings.HasPrefix(path, "~") {')
    lines.append("\t\thome, err := os.UserHomeDir()")
    lines.append("\t\tif err == nil {")
    lines.append("\t\t\tpath = filepath.Join(home, path[1:])")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn path")
    lines.append("}\n")

    # JSON-RPC internals
    lines.append("// --- JSON-RPC internals ---\n")

    lines.append("type jsonRPCRequest struct {")
    lines.append(f"\tJSONRPC string {BQ}json:\"jsonrpc\"{BQ}")
    lines.append(f"\tID      int    {BQ}json:\"id\"{BQ}")
    lines.append(f"\tMethod  string {BQ}json:\"method\"{BQ}")
    lines.append(f"\tParams  any    {BQ}json:\"params\"{BQ}")
    lines.append("}\n")

    lines.append("type jsonRPCResponse struct {")
    lines.append(f"\tJSONRPC string          {BQ}json:\"jsonrpc\"{BQ}")
    lines.append(f"\tID      int             {BQ}json:\"id\"{BQ}")
    lines.append(f"\tResult  json.RawMessage {BQ}json:\"result,omitempty\"{BQ}")
    lines.append(f"\tError   *jsonRPCErr     {BQ}json:\"error,omitempty\"{BQ}")
    lines.append("}\n")

    lines.append("type jsonRPCErr struct {")
    lines.append(f"\tCode    int    {BQ}json:\"code\"{BQ}")
    lines.append(f"\tMessage string {BQ}json:\"message\"{BQ}")
    lines.append("}\n")

    lines.append("type toolResult struct {")
    lines.append("\tContent []struct {")
    lines.append("\t\tType string " + BQ + 'json:"type"' + BQ)
    lines.append("\t\tText string " + BQ + 'json:"text"' + BQ)
    lines.append("\t} " + BQ + 'json:"content"' + BQ)
    lines.append("\tIsError bool " + BQ + 'json:"isError"' + BQ)
    lines.append("}\n")

    # initialize
    lines.append("func (c *Client) initialize() error {")
    lines.append("\treq := map[string]any{")
    lines.append('\t\t"jsonrpc": "2.0",')
    lines.append("\t\t\"id\":      c.nextID(),")
    lines.append('\t\t"method":  "initialize",')
    lines.append('\t\t"params": map[string]any{')
    lines.append('\t\t\t"protocolVersion": "2024-11-05",')
    lines.append('\t\t\t"capabilities":    map[string]any{},')
    lines.append('\t\t\t"clientInfo": map[string]any{')
    lines.append('\t\t\t\t"name":    "blender-go-sdk",')
    lines.append('\t\t\t\t"version": "1.0.0",')
    lines.append("\t\t\t},")
    lines.append("\t\t},")
    lines.append("\t}")
    lines.append("\t_, err := c.call(req)")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn err")
    lines.append("\t}")
    lines.append("\t// Send initialized notification")
    lines.append("\tnotif := map[string]any{")
    lines.append('\t\t"jsonrpc": "2.0",')
    lines.append('\t\t"method":  "notifications/initialized",')
    lines.append("\t}")
    lines.append("\treturn c.send(notif)")
    lines.append("}\n")

    # nextID
    lines.append("func (c *Client) nextID() int {")
    lines.append("\tc.mu.Lock()")
    lines.append("\tdefer c.mu.Unlock()")
    lines.append("\tc.msgID++")
    lines.append("\treturn c.msgID")
    lines.append("}\n")

    # send
    lines.append("func (c *Client) send(msg any) error {")
    lines.append("\tdata, err := json.Marshal(msg)")
    lines.append('\tif err != nil {')
    lines.append('\t\treturn fmt.Errorf("marshaling: %w", err)')
    lines.append("\t}")
    lines.append("\tc.mu.Lock()")
    lines.append("\tdefer c.mu.Unlock()")
    lines.append(f"\t_, err = c.stdin.Write(append(data, {NL}))")
    lines.append("\treturn err")
    lines.append("}\n")

    # callNoParse
    lines.append("func (c *Client) callNoParse(req any) (string, error) {")
    lines.append("\tif err := c.send(req); err != nil {")
    lines.append('\t\treturn "", err')
    lines.append("\t}")
    lines.append("\t// Read response line")
    lines.append(f"\tline, err := c.stdout.ReadString({NL})")
    lines.append('\tif err != nil {')
    lines.append('\t\treturn "", fmt.Errorf("reading response: %w", err)')
    lines.append("\t}")
    lines.append("\treturn line, nil")
    lines.append("}\n")

    # call
    lines.append("func (c *Client) call(req any) (json.RawMessage, error) {")
    lines.append("\tline, err := c.callNoParse(req)")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn nil, err")
    lines.append("\t}")
    lines.append("\tvar resp jsonRPCResponse")
    lines.append("\tif err := json.Unmarshal([]byte(line), &resp); err != nil {")
    lines.append('\t\treturn nil, fmt.Errorf("parsing response: %w (line: %q)", err, line)')
    lines.append("\t}")
    lines.append("\tif resp.Error != nil {")
    lines.append('\t\treturn nil, fmt.Errorf("server error [%d]: %s", resp.Error.Code, resp.Error.Message)')
    lines.append("\t}")
    lines.append("\treturn resp.Result, nil")
    lines.append("}\n")

    # newReq
    lines.append("func (c *Client) newReq(toolName string, args map[string]any) map[string]any {")
    lines.append("\treturn map[string]any{")
    lines.append('\t\t"jsonrpc": "2.0",')
    lines.append("\t\t\"id\":      c.nextID(),")
    lines.append('\t\t"method":  "tools/call",')
    lines.append('\t\t"params": map[string]any{')
    lines.append('\t\t\t"name":      toolName,')
    lines.append('\t\t\t"arguments": args,')
    lines.append("\t\t},")
    lines.append("\t}")
    lines.append("}\n")

    # callToolNoParse
    lines.append("// callToolNoParse invokes an MCP tool by name and returns the raw response.")
    lines.append("func (c *Client) callToolNoParse(toolName string, args map[string]any) (string, error) {")
    lines.append("\treq := c.newReq(toolName, args)")
    lines.append("\tresult, err := c.callNoParse(req)")
    lines.append("\tif err != nil {")
    lines.append('\t\treturn "", err')
    lines.append("\t}")
    lines.append("\treturn string(result), nil")
    lines.append("}\n")

    # callTool
    lines.append("// callTool invokes an MCP tool by name and returns the parsed text content.")
    lines.append("func (c *Client) callTool(toolName string, args map[string]any) (string, error) {")
    lines.append("\treq := c.newReq(toolName, args)")
    lines.append("\tresult, err := c.call(req)")
    lines.append("\tif err != nil {")
    lines.append('\t\treturn "", err')
    lines.append("\t}")
    lines.append("\tvar tr toolResult")
    lines.append("\tif err := json.Unmarshal([]byte(result), &tr); err != nil {")
    lines.append('\t\treturn "", fmt.Errorf("parsing tool result: %w", err)')
    lines.append("\t}")
    lines.append("\tvar text string")
    lines.append("\tfor _, item := range tr.Content {")
    lines.append('\t\tif item.Type == "text" {')
    lines.append("\t\t\ttext += item.Text")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\tif tr.IsError {")
    lines.append('\t\treturn text, fmt.Errorf("tool error: %s", text)')
    lines.append("\t}")
    lines.append("\treturn text, nil")
    lines.append("}\n")

    # Must
    lines.append("// Must calls Do and must have no error or it will abort the program.")
    lines.append("func (c *Client) Must(cmd any) (label, result string) {")
    lines.append("\tvar err error")
    lines.append("\tlabel, result, err = c.Do(cmd)")
    lines.append("\tif err != nil {")
    lines.append('\t\tlog.Fatalf("FAIL: %v -> %v", label, err)')
    lines.append("\t}")
    lines.append("\treturn label, result")
    lines.append("}\n")

    # Do
    lines.append("// Do executes an MCP tool call, returning a string result and an error.")
    lines.append("func (c *Client) Do(cmd any) (label, result string, err error) {")
    lines.append("\tswitch req := cmd.(type) {")

    # Build switch cases
    for tool in tools:
        go_name = go_method_name(tool.name)
        lines.append(f"\tcase {go_name}Request:")
        lines.append(f"\tlabel = \"{go_name}\"")
        lines.append(f"\tresult, err = c.{go_name}(req)")

    lines.append("""
\tdefault:
\t\treturn "", "", fmt.Errorf("unknown cmd type %T", cmd)
\t}
\treturn label, result, err
}
""")
    return "\n".join(lines)


def gen_tools_go(tools: list[ToolDef]) -> str:
    """Generate the tools.go file with one request struct + method per tool."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("package blender")
    lines.append("")

    # Group tools by category
    categories: dict[str, list[ToolDef]] = {}
    for t in tools:
        categories.setdefault(t.category, []).append(t)

    for category, cat_tools in categories.items():
        lines.append(f"// --- {category} ---")
        lines.append("")

        for tool in cat_tools:
            struct_name = go_struct_name(tool.name)
            go_name = go_method_name(tool.name)

            # Generate request struct
            lines.append(f"// {struct_name} holds parameters for the {tool.name} tool.")
            if tool.description:
                # First line of description
                first_line = tool.description.split("\n")[0]
                lines.append(f"// {first_line}")
            lines.append(f"type {struct_name} struct {{")

            for p in tool.params:
                field = go_field_name(p.name)
                py_type = p.py_type

                if p.has_default:
                    # Use pointer for optional params (except string, which uses "")
                    go_t = go_type(py_type)
                    if py_type in ("str", "str | None"):
                        # Use empty string as sentinel for "not set"
                        lines.append(f"\t{field} {go_t} `json:\"{p.name},omitempty\"`")
                    elif py_type == "bool":
                        lines.append(f"\t{field} *bool `json:\"{p.name},omitempty\"`")
                    elif py_type == "int" or py_type == "int | None":
                        lines.append(f"\t{field} *int `json:\"{p.name},omitempty\"`")
                    elif py_type.startswith("list["):
                        lines.append(f"\t{field} {go_t} `json:\"{p.name},omitempty\"`")
                    elif py_type.startswith("Literal["):
                        lines.append(f"\t{field} {go_t} `json:\"{p.name},omitempty\"`")
                    else:
                        lines.append(f"\t{field} {go_t} `json:\"{p.name},omitempty\"`")
                else:
                    go_t = go_type(py_type)
                    if py_type.startswith("Literal["):
                        lines.append(f"\t{field} {go_t} `json:\"{p.name}\"`")
                    else:
                        lines.append(f"\t{field} {go_t} `json:\"{p.name}\"`")

            lines.append("}")
            lines.append("")

            # Generate method on Client
            lines.append(f"// {go_name} calls the {tool.name} MCP tool.")
            if tool.description:
                for desc_line in tool.description.split("\n"):
                    desc_line = desc_line.strip()
                    if desc_line:
                        lines.append(f"// {desc_line}")
            lines.append(f"func (c *Client) {go_name}(req {struct_name}) (string, error) {{")

            # Build args map
            lines.append("\targs := map[string]any{}")
            for p in tool.params:
                field = go_field_name(p.name)
                py_type = p.py_type

                if p.has_default:
                    if py_type in ("str", "str | None"):
                        lines.append(f'\tif req.{field} != "" {{')
                        lines.append(f'\t\targs["{p.name}"] = req.{field}')
                        lines.append("\t}")
                    elif py_type == "bool":
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f'\t\targs["{p.name}"] = *req.{field}')
                        lines.append("\t}")
                    elif py_type == "int" or py_type == "int | None":
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f'\t\targs["{p.name}"] = *req.{field}')
                        lines.append("\t}")
                    elif py_type.startswith("list["):
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f'\t\targs["{p.name}"] = req.{field}')
                        lines.append("\t}")
                    elif py_type.startswith("Literal["):
                        lines.append(f'\tif req.{field} != "" {{')
                        lines.append(f'\t\targs["{p.name}"] = req.{field}')
                        lines.append("\t}")
                    else:
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f'\t\targs["{p.name}"] = req.{field}')
                        lines.append("\t}")
                else:
                    if py_type.startswith("list["):
                        lines.append(f'\targs["{p.name}"] = req.{field}')
                    elif py_type.startswith("dict["):
                        lines.append(f'\targs["{p.name}"] = req.{field}')
                    else:
                        lines.append(f'\targs["{p.name}"] = req.{field}')

            lines.append(f'\treturn c.callTool("{tool.name}", args)')
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def gen_go_mod(version: str = "1.0.0") -> str:
    """Generate go.mod."""
    return f"""module github.com/gmlewis/PicoGK/sdk/go/blender

go 1.22

// blender: Blender MCP SDK for Go
// Version: {version}
"""


def gen_readme_md(tools: list[ToolDef]) -> str:
    """Generate the SDK README.md."""
    tool_count = len(tools)
    category_list: dict[str, list[str]] = {}
    for t in tools:
        category_list.setdefault(t.category, []).append(t.name)

    cat_table = "\n".join(
        f"| **{cat}** | {', '.join(names)} |"
        for cat, names in sorted(category_list.items())
    )

    return (
        "# blender \u2014 Go SDK for the Blender MCP Server\n"
        "\n"
        "`blender` is an auto-generated Go SDK for the [Blender MCP](https://github.com/ahujasid/blender-mcp) server. "
        f"It provides a fully typed, idiomatic Go interface to all {tool_count} Blender MCP tools \u2014 "
        "from executing Python code to querying scene objects, capturing screenshots, rendering, and inspecting blend files.\n"
        "\n"
        "## Quick Start\n"
        "\n"
        "```bash\n"
        "go get github.com/gmlewis/PicoGK/sdk/go/blender\n"
        "```\n"
        "\n"
        "```go\n"
        "package main\n"
        "\n"
        'import (\n'
        '    "context"\n'
        '    "fmt"\n'
        '    "log"\n'
        '\n'
        '    "github.com/gmlewis/PicoGK/sdk/go/blender"\n'
        ')\n'
        '\n'
        'func main() {\n'
        '    ctx := context.Background()\n'
        '\n'
        "    // Launch the Blender MCP server\n"
        "    // Assumes 'python -m blmcp' is available, or pass a custom path\n"
        '    client, err := blender.NewClient(ctx, "")\n'
        '    if err != nil {\n'
        '        log.Fatal(err)\n'
        '    }\n'
        '    defer client.Close()\n'
        '\n'
        "    // Execute Python code in Blender\n"
        '    res, err := client.ExecuteBlenderCode(blender.ExecuteBlenderCodeRequest{\n'
        '        Code: "import bpy; result = {\'count\': len(bpy.data.objects)}",\n'
        '    })\n'
        '    if err != nil {\n'
        '        log.Fatal(err)\n'
        '    }\n'
        '    fmt.Println(res)\n'
        '\n'
        "    // Get scene objects summary\n"
        '    res, err = client.GetObjectsSummary(blender.GetObjectsSummaryRequest{})\n'
        '    if err != nil {\n'
        '        log.Fatal(err)\n'
        '    }\n'
        '    fmt.Println(res)\n'
        '\n'
        "    // Capture a screenshot\n"
        '    _, err = client.GetScreenshotOfWindowAsImage(blender.GetScreenshotOfWindowAsImageRequest{\n'
        '        SizeLimitInBytes: intPtr(512 * 1024),\n'
        '    })\n'
        '    if err != nil {\n'
        '        log.Fatal(err)\n'
        '    }\n'
        '\n'
        "    // Search the Blender Python API docs\n"
        '    res, err = client.SearchAPIDocs(blender.SearchAPIDocsRequest{\n'
        '        Query: "how to bake",\n'
        '    })\n'
        '    if err != nil {\n'
        '        log.Fatal(err)\n'
        '    }\n'
        '    fmt.Println(res)\n'
        '}\n'
        '\n'
        "// Helper: create an int pointer\n"
        'func intPtr(v int) *int { return &v }\n'
        "```\n"
        "\n"
        "## API Overview\n"
        "\n"
        f"The SDK exposes all {tool_count} Blender MCP tools via request structs:\n"
        "\n"
        "| Category | Tools |\n"
        "|----------|-------|\n"
        f"{cat_table}\n"
        "\n"
        "Each tool has:\n"
        "- A `XxxRequest` struct with typed fields (optional params are pointers)\n"
        "- A `client.Xxx(req)` method returning `(string, error)`\n"
        "- Full doc comments\n"
        "\n"
        "## Architecture\n"
        "\n"
        "The SDK launches the Blender MCP server as a subprocess and communicates via\n"
        "JSON-RPC over stdio. The Blender MCP server must be installed separately, and\n"
        "Blender must be running with the MCP addon enabled.\n"
        "\n"
        "## Auto-Generation\n"
        "\n"
        "This SDK is auto-generated from the Blender MCP server tool definitions by\n"
        "`scripts/generate-go-blender-sdk.py`. To regenerate:\n"
        "\n"
        "```bash\n"
        "./scripts/generate-go-blender-sdk.py --verbose\n"
        "```\n"
        "\n"
        "**DO NOT EDIT** the generated files \u2014 changes will be overwritten.\n"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate the Go (blender) MCP SDK from Blender MCP tool definitions."
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent.parent / "sdk" / "go",
        help="Output directory (default: sdk/go/)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    tools = parse_all_tools()
    print(f"Parsed {len(tools)} tools from Blender MCP tools")

    if args.verbose:
        for t in tools:
            req = [p.name for p in t.required_params]
            opt = [p.name for p in t.optional_params]
            print(f"  {t.name} ({t.category})")
            print(f"    desc: {t.description[:80]}...")
            if req:
                print(f"    required: {req}")
            if opt:
                print(f"    optional: {opt}")
            print()

    # Create output directories
    pkg_dir = args.output / "blender"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    client_go = gen_client_go(tools)
    tools_go = gen_tools_go(tools)
    go_mod = gen_go_mod()
    readme_md = gen_readme_md(tools)

    (pkg_dir / "client.go").write_text(client_go)
    (pkg_dir / "tools.go").write_text(tools_go)
    (pkg_dir / "go.mod").write_text(go_mod)
    (pkg_dir / "README.md").write_text(readme_md)

    # Run go fmt on generated source files
    try:
        subprocess.run(["go", "fmt", str(pkg_dir / "client.go"), str(pkg_dir / "tools.go")],
                       check=True, capture_output=True, timeout=30)
    except Exception as e:
        print(f"  Warning: go fmt failed: {e}")

    # Re-read formatted files for accurate line count
    client_lines = len((pkg_dir / "client.go").read_text().splitlines())
    tools_lines = len((pkg_dir / "tools.go").read_text().splitlines())
    readme_lines = len((pkg_dir / "README.md").read_text().splitlines())

    print(f"Generated Go SDK in {pkg_dir}:")
    print(f"  client.go   ({client_lines:>5} lines)")
    print(f"  tools.go    ({tools_lines:>5} lines)")
    print(f"  go.mod")
    print(f"  README.md   ({readme_lines:>5} lines)")
    print(f"\n  Total: {len(tools)} tools across {len(set(t.category for t in tools))} categories")


if __name__ == "__main__":
    main()
