#!/usr/bin/env python3
"""Generate an idiomatic MoonBit SDK for the PicoGK MCP server.

Parses all MCP tool definitions from PicoGK.Mcp/Tools/*.cs and emits
a complete MoonBit package (mbtpicogk) with:
  - A Client type that manages the MCP stdio subprocess
  - Builder-pattern method functions for all 62 tools
  - Full doc comments on every function
  - A README.md with usage examples

Usage:
    ./scripts/generate-mbt-mcp-sdk.py [--output DIR] [--verbose]

Output goes to sdk/mbt/ by default.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _parse_mcp_tools import parse_mcp_tools, ToolDef, Param

GENERATED_HEADER = "// Code generated by scripts/generate-mbt-mcp-sdk.py — DO NOT EDIT.\n"


# ---------------------------------------------------------------------------
# Type mapping: C# -> MoonBit
# ---------------------------------------------------------------------------

def mbt_type(cs_type: str) -> str:
    """Map a C# type to its MoonBit equivalent."""
    if cs_type == "float":
        return "Double"
    if cs_type == "int":
        return "Int"
    if cs_type == "bool":
        return "Bool"
    if cs_type in ("string", "string?"):
        return "String"
    if cs_type == "string[]":
        return "Array[String]"
    return "Unit"


def mbt_type_for_optional(cs_type: str) -> str:
    """For optional params, MoonBit uses Option[T]."""
    if cs_type == "float":
        return "Double?"
    if cs_type == "int":
        return "Int?"
    if cs_type == "bool":
        return "Bool?"
    if cs_type in ("string", "string?"):
        return "String?"
    if cs_type == "string[]":
        return "Array[String]?"  # nil means not set
    return "Unit"


def mbt_zero(cs_type: str) -> str:
    """Return the MoonBit zero/default value."""
    if cs_type == "float":
        return "0.0"
    if cs_type == "int":
        return "0"
    if cs_type == "bool":
        return "false"
    if cs_type in ("string", "string?"):
        return '""'
    if cs_type == "string[]":
        return "[]"
    return "Unit"


# ---------------------------------------------------------------------------
# Name conversion
# ---------------------------------------------------------------------------

def mbt_field_name(param_name: str) -> str:
    """Convert snake_case param name to MoonBit camelCase field name."""
    parts = param_name.split("_")
    result = parts[0]
    for p in parts[1:]:
        result += p[:1].upper() + p[1:]
    return result


def mbt_method_name(tool_name: str) -> str:
    """Convert PascalCase to MoonBit snake_case method name."""
    import re
    result = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", tool_name)
    result = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", result)
    return result.lower()


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def gen_client_mbt(tools: list[ToolDef]) -> str:
    """Generate the core client.mbt file."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("///")
    lines.append("/// Client manages a connection to the PicoGK MCP server.")
    lines.append("/// It launches the server as a subprocess and communicates via JSON-RPC over stdio.")
    lines.append("///")
    lines.append("/// Usage:")
    lines.append("///   let client = @mbtpicogk.new_client(\"/path/to/PicoGK.Mcp\")!")
    lines.append("///   client.picogk_init(0.5)!")
    lines.append("///   client.create_sphere(0.0, 0.0, 0.0, 30.0, Some(\"body\"))!")
    lines.append("///   client.close!")
    lines.append("///")
    lines.append("pub struct Client {")
    lines.append("  process : Process")
    lines.append("  stdin : Buffer")
    lines.append("  stdout : Buffer")
    lines.append("  mut msg_id : Int")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// new_client launches the PicoGK MCP server binary and returns a Client.")
    lines.append("/// The server_bin path should point to the self-contained PicoGK.Mcp executable.")
    lines.append("///")
    lines.append("pub fn new_client(server_bin : String) -> Client! {")
    lines.append("  // Launch the server process")
    lines.append("  let proc = @process.start(server_bin, [])!")
    lines.append("  let client = Client{")
    lines.append("    process: proc,")
    lines.append("    stdin: Buffer::new(),")
    lines.append("    stdout: Buffer::new(),")
    lines.append("    msg_id: 0,")
    lines.append("  }")
    lines.append("  // Perform MCP initialize handshake")
    lines.append("  client.initialize!()")
    lines.append("  client")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// close shuts down the MCP server process.")
    lines.append("///")
    lines.append("pub fn Client::close(self : Client) -> Unit {")
    lines.append("  self.process.kill()")
    lines.append("}")
    lines.append("")
    lines.append("// --- JSON-RPC internals ---")
    lines.append("")
    lines.append("///")
    lines.append("/// next_id returns the next JSON-RPC request ID.")
    lines.append("///")
    lines.append("fn Client::next_id(self : Client) -> Int {")
    lines.append("  self.msg_id = self.msg_id + 1")
    lines.append("  self.msg_id")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// call_tool invokes an MCP tool by name and returns the text response.")
    lines.append("///")
    lines.append("pub fn Client::call_tool(self : Client, tool_name : String, args : Map[String, JsonValue]) -> String!String {")
    lines.append("  let id = self.next_id()")
    lines.append("  let req = JsonValue::Object([")
    lines.append("    (\"jsonrpc\", JsonValue::String(\"2.0\")),")
    lines.append("    (\"id\", JsonValue::Int(id)),")
    lines.append("    (\"method\", JsonValue::String(\"tools/call\")),")
    lines.append("    (\"params\", JsonValue::Object([")
    lines.append("      (\"name\", JsonValue::String(tool_name)),")
    lines.append("      (\"arguments\", JsonValue::Object(args.iter().to_array())),")
    lines.append("    ])),")
    lines.append("  ])")
    lines.append("  let json_str = req.stringify()")
    lines.append("  self.process.write_line!(json_str)")
    lines.append("  let response = self.process.read_line!()")
    lines.append("  // Parse response and extract text content")
    lines.append("  let resp = JsonValue::from_string!(response)")
    lines.append("  match resp {")
    lines.append("    JsonValue::Object(fields) => {")
    lines.append("      let result = fields.get(\"result\").or_panic!()")
    lines.append("      match result {")
    lines.append("        JsonValue::Object(result_fields) => {")
    lines.append("          let content = result_fields.get(\"content\").or_panic!()")
    lines.append("          match content {")
    lines.append("            JsonValue::Array(items) => {")
    lines.append("              let mut text = \"\"")
    lines.append("              for item in items {")
    lines.append("                match item {")
    lines.append("                  JsonValue::Object(item_fields) => {")
    lines.append("                    match item_fields.get(\"text\") {")
    lines.append("                      Some(JsonValue::String(s)) => text = text + s")
    lines.append("                      _ => ()")
    lines.append("                    }")
    lines.append("                  }")
    lines.append("                  _ => ()")
    lines.append("                }")
    lines.append("              }")
    lines.append("              text")
    lines.append("            }")
    lines.append("            _ => abort(\"unexpected content format\")")
    lines.append("          }")
    lines.append("        }")
    lines.append("        _ => abort(\"unexpected result format\")")
    lines.append("      }")
    lines.append("    }")
    lines.append("    _ => abort(\"unexpected response format\")")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// initialize performs the MCP initialize handshake.")
    lines.append("///")
    lines.append("fn Client::initialize(self : Client) -> Unit!String {")
    lines.append("  let id = self.next_id()")
    lines.append("  let req = JsonValue::Object([")
    lines.append("    (\"jsonrpc\", JsonValue::String(\"2.0\")),")
    lines.append("    (\"id\", JsonValue::Int(id)),")
    lines.append("    (\"method\", JsonValue::String(\"initialize\")),")
    lines.append("    (\"params\", JsonValue::Object([")
    lines.append("      (\"protocolVersion\", JsonValue::String(\"2024-11-05\")),")
    lines.append("      (\"capabilities\", JsonValue::Object([])),")
    lines.append("      (\"clientInfo\", JsonValue::Object([")
    lines.append("        (\"name\", JsonValue::String(\"mbtpicogk\")),")
    lines.append("        (\"version\", JsonValue::String(\"1.0.0\")),")
    lines.append("      ])),")
    lines.append("    ])),")
    lines.append("  ])")
    lines.append("  self.process.write_line!(req.stringify())")
    lines.append("  let _ = self.process.read_line!()")
    lines.append("  // Send initialized notification")
    lines.append("  let notif = JsonValue::Object([")
    lines.append("    (\"jsonrpc\", JsonValue::String(\"2.0\")),")
    lines.append("    (\"method\", JsonValue::String(\"notifications/initialized\")),")
    lines.append("  ])")
    lines.append("  self.process.write_line!(notif.stringify())")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_tools_mbt(tools: list[ToolDef]) -> str:
    """Generate the tools.mbt file with one method per tool."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    # Group tools by category
    categories: dict[str, list[ToolDef]] = {}
    for t in tools:
        categories.setdefault(t.category, []).append(t)

    for category, cat_tools in categories.items():
        lines.append(f"// === {category} ===")
        lines.append("")

        for tool in cat_tools:
            method_name = mbt_method_name(tool.name)
            # Build function signature
            params_sig: list[str] = []
            for p in tool.params:
                if p.has_default:
                    mbt_t = mbt_type_for_optional(p.cs_type)
                else:
                    mbt_t = mbt_type(p.cs_type)
                params_sig.append(f"{mbt_field_name(p.name)} : {mbt_t}")

            params_str = ", ".join(params_sig)

            # Build the args map construction
            args_lines: list[str] = []
            for p in tool.params:
                field = mbt_field_name(p.name)
                json_key = p.name
                if p.has_default:
                    if p.cs_type == "string[]":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(arr) => args.set(\"{json_key}\", JsonValue::Array(arr.map(fn(s) {{ JsonValue::String(s) }})))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type == "float":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", JsonValue::Number(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type == "int":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", JsonValue::Int(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type == "bool":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", JsonValue::Bool(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type in ("string", "string?"):
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", JsonValue::String(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                else:
                    if p.cs_type == "float":
                        args_lines.append(f"  args.set(\"{json_key}\", JsonValue::Number({field}))")
                    elif p.cs_type == "int":
                        args_lines.append(f"  args.set(\"{json_key}\", JsonValue::Int({field}))")
                    elif p.cs_type == "bool":
                        args_lines.append(f"  args.set(\"{json_key}\", JsonValue::Bool({field}))")
                    elif p.cs_type in ("string", "string?"):
                        args_lines.append(f"  args.set(\"{json_key}\", JsonValue::String({field}))")
                    elif p.cs_type == "string[]":
                        args_lines.append(f"  args.set(\"{json_key}\", JsonValue::Array({field}.map(fn(s) {{ JsonValue::String(s) }})))")

            # Write doc comment
            # Escape the description for MoonBit comments
            desc = tool.description.replace('\n', '\n  ///')
            lines.append(f"///")
            lines.append(f"/// {method_name} — {tool.snake_name}")
            lines.append(f"/// {desc}")
            lines.append(f"///")

            # Function signature
            if params_str:
                lines.append(f"pub fn Client::{tool.name}(self : Client, {params_str}) -> String!String {{")
            else:
                lines.append(f"pub fn Client::{tool.name}(self : Client) -> String!String {{")

            lines.append(f"  let args : Map[String, JsonValue] = {{}}")
            if args_lines:
                lines.extend(args_lines)
            lines.append(f"  self.call_tool!(\"{tool.snake_name}\", args)")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def gen_moon_mod_json() -> str:
    """Generate moon.mod.json."""
    return """{
  "name": "leap71/mbtpicogk",
  "version": "1.0.0",
  "description": "MoonBit SDK for the PicoGK MCP geometry kernel server",
  "readme": "README.md",
  "repository": "https://github.com/leap71/PicoGK",
  "license": "Apache-2.0"
}
"""


def gen_moon_pkg_json() -> str:
    """Generate moon.pkg.json."""
    return """{
  "import": [
    "moonbitlang/core/json",
    "moonbitlang/core/process"
  ],
  "link": {
    "wasm": {}
  }
}
"""


def gen_readme_md(tools: list[ToolDef]) -> str:
    """Generate the SDK README.md."""
    tool_count = len(tools)
    category_list: dict[str, list[str]] = {}
    for t in tools:
        category_list.setdefault(t.category, []).append(t.snake_name)

    cat_table = "\n".join(
        f"| **{cat}** | {', '.join(names)} |"
        for cat, names in sorted(category_list.items())
    )

    return f"""# mbtpicogk — MoonBit SDK for the PicoGK MCP Server

`mbtpicogk` is an auto-generated MoonBit SDK for the [PicoGK](https://picogk.org)
geometry kernel's MCP (Model Context Protocol) server. It provides a fully typed,
idiomatic MoonBit interface to all {tool_count} PicoGK tools — from creating
primitives to boolean operations, lattice design, mesh manipulation, rendering, and
3D-printing export.

## Quick Start

```bash
moon add leap71/mbtpicogk
```

```moonbit
///|
fn main {{
  // Launch the PicoGK MCP server
  let client = @mbtpicogk.new_client("/path/to/PicoGK.Mcp")!

  // Initialize the geometry kernel (0.5mm voxels)
  let _ = client.picogk_init!(0.5)

  // Create a sphere
  let res = client.create_sphere!(0.0, 0.0, 0.0, 30.0, Some("body"))
  println(res)

  // Create a box cutout
  let _ = client.create_box!(-10.0, -10.0, -40.0, 10.0, 10.0, 40.0, Some("cutout"))

  // Subtract box from sphere
  let _ = client.boolean_subtract!("body", "cutout", Some("result"))

  // Smooth the result
  let _ = client.smooth!("result", 2.0, Some("smoothed"))

  // Convert to mesh and export STL
  let _ = client.voxels_to_mesh!("smoothed", Some("mesh"))
  let _ = client.save_stl!("mesh", "/tmp/part.stl")

  // Render a preview
  let _ = client.render_to_image!("smoothed", "/tmp/preview.png")

  // Clean up
  client.close()

  println("Done! Part exported to /tmp/part.stl")
}}
```

## API Overview

The SDK exposes all {tool_count} PicoGK MCP tools via typed methods:

| Category | Tools |
|----------|-------|
{cat_table}

Each tool has:
- A `Client::ToolName(...)` method with typed parameters
- Optional parameters are `Option[T]` (use `Some(value)` or `None`)
- Returns `String` (the tool's text response) or raises `String` on error
- Full doc comments

## Architecture

The SDK launches the PicoGK MCP server as a subprocess and communicates via
JSON-RPC over stdio. No network connection is needed. The server binary must
be installed separately (see the main PicoGK README for build instructions).

## Auto-Generation

This SDK is auto-generated from the PicoGK C# MCP tool definitions by
`scripts/generate-mbt-mcp-sdk.py`. To regenerate:

```bash
./scripts/generate-mbt-mcp-sdk.py --verbose
```

**DO NOT EDIT** the generated files — changes will be overwritten. Edit the
C# tool definitions in `PicoGK.Mcp/Tools/*.cs` instead, then regenerate.
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate the MoonBit (mbtpicogk) MCP SDK from PicoGK C# tool definitions."
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent.parent / "sdk" / "mbt",
        help="Output directory (default: sdk/mbt/)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    tools = parse_mcp_tools()
    print(f"Parsed {len(tools)} tools from PicoGK.Mcp/Tools/*.cs")

    # Create output directories
    pkg_dir = args.output / "mbtpicogk"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    client_mbt = gen_client_mbt(tools)
    tools_mbt = gen_tools_mbt(tools)
    moon_mod = gen_moon_mod_json()
    moon_pkg = gen_moon_pkg_json()
    readme_md = gen_readme_md(tools)

    (pkg_dir / "client.mbt").write_text(client_mbt)
    (pkg_dir / "tools.mbt").write_text(tools_mbt)
    (pkg_dir / "moon.mod.json").write_text(moon_mod)
    (pkg_dir / "moon.pkg.json").write_text(moon_pkg)
    (pkg_dir / "README.md").write_text(readme_md)

    print(f"Generated MoonBit SDK in {pkg_dir}:")
    print(f"  client.mbt      ({len(client_mbt.splitlines()):>5} lines)")
    print(f"  tools.mbt       ({len(tools_mbt.splitlines()):>5} lines)")
    print(f"  moon.mod.json")
    print(f"  moon.pkg.json")
    print(f"  README.md       ({len(readme_md.splitlines()):>5} lines)")
    print(f"\n  Total: {len(tools)} tools across {len(set(t.category for t in tools))} categories")


if __name__ == "__main__":
    main()