#!/usr/bin/env python3
"""Generate an idiomatic MoonBit SDK for the Blender MCP server.

Parses all MCP tool definitions from ~/Projects/Blender/blender_mcp/mcp/blmcp/tools/*.py
and emits a complete MoonBit package (blender) with:
  - A Client type that manages the MCP stdio subprocess
  - Builder-pattern method functions for all tools
  - Full doc comments on every function
  - A README.md with usage examples

Usage:
    ./scripts/generate-mbt-blender-sdk.py [--output DIR] [--verbose]

Output goes to sdk/mbt/blender/ by default.
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

GENERATED_HEADER = "// Code generated by scripts/generate-mbt-blender-sdk.py — DO NOT EDIT.\n"

BLENDER_MCP_DIR = Path.home() / "Projects" / "Blender" / "blender_mcp" / "mcp" / "blmcp" / "tools"


# ---------------------------------------------------------------------------
# Tool definitions
# ---------------------------------------------------------------------------

@dataclass
class Param:
    name: str
    py_type: str
    description: str
    default: str | None
    has_default: bool


@dataclass
class ToolDef:
    name: str
    description: str
    category: str
    params: list[Param] = field(default_factory=list)

    @property
    def required_params(self) -> list[Param]:
        return [p for p in self.params if not p.has_default]

    @property
    def optional_params(self) -> list[Param]:
        return [p for p in self.params if p.has_default]


# ---------------------------------------------------------------------------
# Python type -> MoonBit type mapping
# ---------------------------------------------------------------------------

def mbt_type(py_type: str) -> str:
    """Map a Python type to its MoonBit equivalent."""
    if py_type.startswith("list["):
        inner = py_type[5:-1]
        return f"Array[{mbt_type(inner)}]"
    if py_type.startswith("dict["):
        return "Map[String, Json]"
    if py_type in ("str", "str | None"):
        return "String"
    if py_type in ("int", "int | None"):
        return "Int"
    if py_type in ("bool",):
        return "Bool"
    if py_type in ("float",):
        return "Double"
    if py_type in ("object", "any"):
        return "Json"
    # Literal types (enum) -> String
    if py_type.startswith("Literal["):
        return "String"
    # Named type aliases (e.g., AreaUIType) -> String
    if py_type in ("AreaUIType",):
        return "String"
    return "Json"


def mbt_type_optional(py_type: str) -> str:
    """For optional params, MoonBit uses Option[T]."""
    return mbt_type(py_type) + "?"


def mbt_zero(py_type: str) -> str:
    """Return the MoonBit zero/default value."""
    if py_type.startswith("list["):
        return "[]"
    if py_type.startswith("dict["):
        return "{}"
    if py_type in ("str", "str | None"):
        return '""'
    if py_type in ("int", "int | None"):
        return "0"
    if py_type in ("bool",):
        return "false"
    if py_type in ("float",):
        return "0.0"
    if py_type.startswith("Literal["):
        return '""'
    return "None"


# ---------------------------------------------------------------------------
# Name conversion
# ---------------------------------------------------------------------------

def mbt_field_name(param_name: str) -> str:
    """Convert snake_case param name to MoonBit camelCase field name."""
    parts = param_name.split("_")
    result = parts[0]
    for p in parts[1:]:
        result += p[:1].upper() + p[1:]
    return result


def mbt_method_name(tool_name: str) -> str:
    """Convert snake_case tool name to MoonBit snake_case method name."""
    # Already snake_case, just use as-is
    return tool_name


# ---------------------------------------------------------------------------
# Tool discovery (reuses Go SDK's AST parser)
# ---------------------------------------------------------------------------

def _find_tool_files() -> list[Path]:
    """Find all non-template, non-toolcode Python files in the tools directory."""
    files = []
    for f in sorted(BLENDER_MCP_DIR.glob("*.py")):
        if f.name.startswith("_"):
            continue
        if f.name.endswith("_toolcode.py"):
            continue
        files.append(f)
    return files


def _ast_type_to_str(node: ast.AST) -> str:
    """Convert an AST type annotation node to a string."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Constant):
        return str(node.value)
    if isinstance(node, ast.Subscript):
        base = _ast_type_to_str(node.value)
        inner = _ast_type_to_str(node.slice)
        return f"{base}[{inner}]"
    if isinstance(node, ast.Tuple):
        parts = [_ast_type_to_str(e) for e in node.elts]
        return ", ".join(parts)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        left = _ast_type_to_str(node.left)
        right = _ast_type_to_str(node.right)
        return f"{left} | {right}"
    if isinstance(node, ast.Attribute):
        return f"{_ast_type_to_str(node.value)}.{node.attr}"
    return ast.dump(node)


def _ast_value_to_str(node: ast.AST) -> str:
    """Convert an AST default value node to a string."""
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, ast.NameConstant):
        return str(node.value)
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return f"{_ast_value_to_str(node.value)}.{node.attr}"
    return ast.dump(node)


def _category_from_filename(stem: str) -> str:
    """Determine category from the tool filename."""
    if stem.startswith("get_blendfile_summary"):
        return "Blend File"
    if stem.startswith("get_screenshot"):
        return "Screenshot"
    if stem.startswith("execute_blender_code"):
        return "Execute"
    if stem.startswith("get_python_api_docs") or stem.startswith("search_api_docs"):
        return "API Docs"
    if stem.startswith("search_manual_docs"):
        return "Manual Docs"
    if stem.startswith("get_objects_summary") or stem.startswith("get_object_detail"):
        return "Objects"
    if stem.startswith("render_"):
        return "Render"
    if stem.startswith("jump_to_tab"):
        return "Workspace"
    if stem.startswith("jump_to_view3d"):
        return "Viewport"
    return "Other"


def parse_all_tools() -> list[ToolDef]:
    """Parse all Blender MCP tools from the Python source files."""
    tools = []

    for filepath in _find_tool_files():
        source = filepath.read_text()

        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue

        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef):
                continue
            if node.name.startswith("_"):
                continue
            # Check for @mcp.tool decorator
            has_tool_decorator = False
            for decorator in node.decorator_list:
                if isinstance(decorator, ast.Call):
                    func = decorator.func
                    if isinstance(func, ast.Attribute) and func.attr == "tool":
                        has_tool_decorator = True
                        break
            if not has_tool_decorator:
                continue

            # Extract docstring
            docstring = ""
            if node.body and isinstance(node.body[0], ast.Expr):
                val = node.body[0].value
                if isinstance(val, (ast.Constant, ast.Str)):
                    docstring = val.value if isinstance(val, ast.Constant) else val.s
                    docstring = " ".join(docstring.split())

            # Extract parameters
            params = []
            args = node.args
            num_defaults = len(args.defaults)
            num_args = len(args.args)
            for i, arg in enumerate(args.args):
                if arg.arg == "self":
                    continue
                py_type = ""
                if arg.annotation:
                    py_type = _ast_type_to_str(arg.annotation)

                default_idx = i - (num_args - num_defaults)
                if default_idx >= 0:
                    default_node = args.defaults[default_idx]
                    default_val = _ast_value_to_str(default_node)
                    params.append(Param(
                        name=arg.arg,
                        py_type=py_type,
                        description="",
                        default=default_val,
                        has_default=True,
                    ))
                else:
                    params.append(Param(
                        name=arg.arg,
                        py_type=py_type,
                        description="",
                        default=None,
                        has_default=False,
                    ))

            category = _category_from_filename(filepath.stem)

            tools.append(ToolDef(
                name=node.name,
                description=docstring,
                category=category,
                params=params,
            ))

    return tools


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def gen_client_mbt(tools: list[ToolDef]) -> str:
    """Generate the core client.mbt file using moonbitlang/async for process I/O."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("///")
    lines.append("/// Client manages a connection to the Blender MCP server.")
    lines.append("/// It launches the server as a subprocess and communicates via JSON-RPC over stdio.")
    lines.append("/// All tool methods are async and must be called within an `async fn main` block.")
    lines.append("///")
    lines.append("/// Usage:")
    lines.append("///   async fn main {")
    lines.append('///     let client = @blender.new_client("")')
    lines.append('///     let res = client.execute_blender_code("import bpy; result = {\'count\': len(bpy.data.objects)}")')
    lines.append("///     println(res)")
    lines.append("///     client.close()")
    lines.append("///   }")
    lines.append("///")
    lines.append("pub struct Client {")
    lines.append("  pid : Int")
    lines.append("  stdin : @process.WriteToProcess")
    lines.append("  stdout : @process.ReadFromProcess")
    lines.append("  mut msg_id : Int")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// default_server_bin returns the default command to launch the Blender MCP server.")
    lines.append("///")
    lines.append('let default_server_bin : String = "uv"')
    lines.append("")
    lines.append("///")
    lines.append("/// default_server_args returns the default arguments for the Blender MCP server.")
    lines.append("///")
    lines.append('let default_server_args : Array[String] = ["--directory", expand_path("~/Projects/Blender/blender_mcp/mcp/blmcp"), "run", "blender-mcp"]')
    lines.append("")
    lines.append("///")
    lines.append("/// new_client launches the Blender MCP server and returns a Client.")
    lines.append("/// If server_bin is empty, uses the default (uv run blender-mcp).")
    lines.append("/// Must be called within an async function.")
    lines.append("///")
    lines.append("pub async fn new_client(server_bin : String) -> Client raise {")
    lines.append("  let (cmd, args) = if server_bin == \"\" {")
    lines.append("    (default_server_bin, default_server_args)")
    lines.append("  } else {")
    lines.append("    (server_bin, [])")
    lines.append("  }")
    lines.append("  let path = expand_path(cmd)")
    lines.append("  let (stdin_read, stdin_write) = @process.write_to_process()")
    lines.append("  let (stdout_read, stdout_write) = @process.read_from_process()")
    lines.append("  let pid = @process.spawn_orphan(path, args, stdin=stdin_read, stdout=stdout_write)")
    lines.append("  let client = Client::{")
    lines.append("    pid: pid,")
    lines.append("    stdin: stdin_write,")
    lines.append("    stdout: stdout_read,")
    lines.append("    msg_id: 0,")
    lines.append("  }")
    lines.append("  client.initialize()")
    lines.append("  client")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// close shuts down the MCP server process.")
    lines.append("///")
    lines.append("pub fn Client::close(self : Client) -> Unit {")
    lines.append("  self.stdin.close()")
    lines.append("  self.stdout.close()")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// expand_path expands a leading ~ to the user's home directory.")
    lines.append("///")
    lines.append("fn expand_path(path : String) -> String {")
    lines.append('  if path.has_prefix("~") {')
    lines.append('    let home = @env.get_env_var("HOME").unwrap_or("")')
    lines.append("    home + path[1:].to_owned()")
    lines.append("  } else {")
    lines.append("    path")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("// --- JSON-RPC internals ---")
    lines.append("")
    lines.append("///")
    lines.append("/// next_id returns the next JSON-RPC request ID.")
    lines.append("///")
    lines.append("fn Client::next_id(self : Client) -> Int {")
    lines.append("  self.msg_id = self.msg_id + 1")
    lines.append("  self.msg_id")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// send_line writes a JSON-RPC message to the server's stdin.")
    lines.append("///")
    lines.append("async fn Client::send_line(self : Client, json_str : String) -> Unit raise {")
    lines.append('  let data = @utf8.encode(json_str + "\\n")')
    lines.append("  let _ = self.stdin.write_once(data, offset=0, len=data.length())")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// read_line reads a JSON-RPC response line from the server's stdout.")
    lines.append("///")
    lines.append("async fn Client::read_line(self : Client) -> String raise {")
    lines.append('  match self.stdout.read_until("\\n") {')
    lines.append("    Some(line) => line")
    lines.append('    None => raise Failure::Failure("EOF: no more data from server")')
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// call_tool invokes an MCP tool by name and returns the text response.")
    lines.append("///")
    lines.append("pub async fn Client::call_tool(self : Client, tool_name : String, args : Map[String, Json]) -> String raise {")
    lines.append("  let id = self.next_id()")
    lines.append("  let req = Json::object(Map([")
    lines.append('    ("jsonrpc", Json::string("2.0")),')
    lines.append("    (\"id\", Json::number(id.to_double())),")
    lines.append('    ("method", Json::string("tools/call")),')
    lines.append('    ("params", Json::object(Map([')
    lines.append('      ("name", Json::string(tool_name)),')
    lines.append('      ("arguments", Json::object(args)),')
    lines.append("    ]))),")
    lines.append("  ]))")
    lines.append("  self.send_line(req.stringify())")
    lines.append("  let response = self.read_line()")
    lines.append("  try @json.parse(response) catch {")
    lines.append("    _ => return response")
    lines.append("  } noraise {")
    lines.append("    resp => {")
    lines.append("      match resp {")
    lines.append("        Object(fields) => {")
    lines.append('          let result = fields.get("result").unwrap()')
    lines.append("          match result {")
    lines.append("            Object(result_fields) => {")
    lines.append('              let content = result_fields.get("content").unwrap()')
    lines.append("              match content {")
    lines.append("                Array(items) => {")
    lines.append('                  let mut text = ""')
    lines.append("                  for item in items {")
    lines.append("                    match item {")
    lines.append("                      Object(item_fields) => {")
    lines.append('                        match item_fields.get("text") {')
    lines.append("                          Some(String(s)) => text = text + s")
    lines.append("                          _ => ()")
    lines.append("                        }")
    lines.append("                      }")
    lines.append("                      _ => ()")
    lines.append("                    }")
    lines.append("                  }")
    lines.append("                  text")
    lines.append("                }")
    lines.append('                _ => raise Failure::Failure("unexpected content format")')
    lines.append("              }")
    lines.append("            }")
    lines.append('            _ => raise Failure::Failure("unexpected result format")')
    lines.append("          }")
    lines.append("        }")
    lines.append("        _ => response")
    lines.append("      }")
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// initialize performs the MCP initialize handshake.")
    lines.append("///")
    lines.append("async fn Client::initialize(self : Client) -> Unit raise {")
    lines.append("  let id = self.next_id()")
    lines.append("  let req = Json::object(Map([")
    lines.append('    ("jsonrpc", Json::string("2.0")),')
    lines.append("    (\"id\", Json::number(id.to_double())),")
    lines.append('    ("method", Json::string("initialize")),')
    lines.append('    ("params", Json::object(Map([')
    lines.append('      ("protocolVersion", Json::string("2024-11-05")),')
    lines.append('      ("capabilities", Json::object(Map([]))),')
    lines.append('      ("clientInfo", Json::object(Map([')
    lines.append('        ("name", Json::string("blender")),')
    lines.append('        ("version", Json::string("0.1.0")),')
    lines.append("      ]))),")
    lines.append("    ]))),")
    lines.append("  ]))")
    lines.append("  self.send_line(req.stringify())")
    lines.append("  let _ = self.read_line()")
    lines.append("  let notif = Json::object(Map([")
    lines.append('    ("jsonrpc", Json::string("2.0")),')
    lines.append('    ("method", Json::string("notifications/initialized")),')
    lines.append("  ]))")
    lines.append("  self.send_line(notif.stringify())")
    lines.append("}")
    return "\n".join(lines)


def gen_tools_mbt(tools: list[ToolDef]) -> str:
    """Generate the tools.mbt file with one method per tool."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")

    # Group tools by category
    categories: dict[str, list[ToolDef]] = {}
    for t in tools:
        categories.setdefault(t.category, []).append(t)

    for category, cat_tools in categories.items():
        lines.append(f"// === {category} ===")
        lines.append("")

        for tool in cat_tools:
            method_name = mbt_method_name(tool.name)

            # Build function signature
            params_sig: list[str] = []
            for p in tool.params:
                if p.has_default:
                    mbt_t = mbt_type_optional(p.py_type)
                else:
                    mbt_t = mbt_type(p.py_type)
                params_sig.append(f"{mbt_field_name(p.name)} : {mbt_t}")

            params_str = ", ".join(params_sig)

            # Build the args map construction
            args_lines: list[str] = []
            for p in tool.params:
                field = mbt_field_name(p.name)
                json_key = p.name
                if p.has_default:
                    if p.py_type == "int" or p.py_type == "int | None":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", Json::number(v.to_double()))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.py_type == "bool":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", Json::boolean(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.py_type.startswith("list["):
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(arr) => args.set(\"{json_key}\", Json::array(arr.map(fn(s) {{ Json::string(s) }})))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    else:
                        # String and other optional types
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", Json::string(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                else:
                    if p.py_type == "int":
                        args_lines.append(f"  args.set(\"{json_key}\", Json::number({field}.to_double()))")
                    elif p.py_type == "bool":
                        args_lines.append(f"  args.set(\"{json_key}\", Json::boolean({field}))")
                    elif p.py_type.startswith("list["):
                        args_lines.append(f"  args.set(\"{json_key}\", Json::array({field}.map(fn(s) {{ Json::string(s) }})))")
                    elif p.py_type.startswith("dict["):
                        args_lines.append(f"  args.set(\"{json_key}\", {field})")
                    else:
                        # String and other types
                        args_lines.append(f"  args.set(\"{json_key}\", Json::string({field}))")

            # Write doc comment
            desc = tool.description.replace('\n', '\n  ///')
            lines.append(f"///")
            lines.append(f"/// {method_name} — {tool.name}")
            lines.append(f"/// {desc}")
            lines.append(f"///")

            # Function signature
            if params_str:
                lines.append(f"pub async fn Client::{method_name}(self : Client, {params_str}) -> String raise {{")
            else:
                lines.append(f"pub async fn Client::{method_name}(self : Client) -> String raise {{")

            lines.append(f"  let args : Map[String, Json] = {{}}")
            if args_lines:
                lines.extend(args_lines)
            lines.append(f"  self.call_tool(\"{tool.name}\", args)")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def gen_moon_mod() -> str:
    """Generate moon.mod."""
    return """// blender: Blender MCP SDK for MoonBit
// To regenerate, run: ./scripts/generate-mbt-blender-sdk.py
// DO NOT EDIT — this file is auto-generated.

name = "gmlewis/blender"

version = "0.1.0"

readme = "README.md"

repository = "https://github.com/gmlewis/PicoGK"

license = "Apache-2.0"

keywords = []

description = "MoonBit SDK for the Blender MCP server"

preferred_target = "native"

supported_targets = "+native"

import {
  "moonbitlang/async@0.19.2"
}
"""


def gen_moon_pkg() -> str:
    """Generate moon.pkg."""
    return """// blender package configuration
// DO NOT EDIT — this file is auto-generated.

import {
  "moonbitlang/async/process",
  "moonbitlang/core/json",
  "moonbitlang/core/env",
  "moonbitlang/core/encoding/utf8" @utf8,
}
"""


def gen_readme_md(tools: list[ToolDef]) -> str:
    """Generate the SDK README.md."""
    tool_count = len(tools)
    category_list: dict[str, list[str]] = {}
    for t in tools:
        category_list.setdefault(t.category, []).append(t.name)

    cat_table = "\n".join(
        f"| **{cat}** | {', '.join(names)} |"
        for cat, names in sorted(category_list.items())
    )

    return f"""# blender — MoonBit SDK for the Blender MCP Server

`blender` is an auto-generated MoonBit SDK for the [Blender MCP](https://github.com/ahujasid/blender-mcp) server. It provides a fully typed, idiomatic MoonBit interface to all {tool_count} Blender MCP tools — from executing Python code to querying scene objects, capturing screenshots, rendering, and inspecting blend files.

All tool methods are **async** and use `moonbitlang/async` for subprocess management.
They must be called within an `async fn main` block.

## Quick Start

```bash
moon add gmlewis/blender
```

```moonbit
///|
async fn main {{
  let client = @blender.new_client("")

  // Execute Python code in Blender
  let res = client.execute_blender_code("import bpy; result = {{'count': len(bpy.data.objects)}}")
  println(res)

  // Get scene objects summary
  let summary = client.get_objects_summary()
  println(summary)

  // Search the Blender Python API docs
  let docs = client.search_api_docs("how to bake")
  println(docs)

  client.close()
}}
```

## API Overview

The SDK exposes all {tool_count} Blender MCP tools via typed methods:

| Category | Tools |
|----------|-------|
{cat_table}

Each tool has:
- A `Client::method_name(...)` method with typed parameters (snake_case)
- Optional parameters are `Option[T]` (use `Some(value)` or `None`)
- Returns `String` (the tool's text response) or raises `Failure` on error
- Full doc comments

## Architecture

The SDK launches the Blender MCP server as a subprocess and communicates via
JSON-RPC over stdio. The Blender MCP server must be installed separately, and
Blender must be running with the MCP addon enabled.

## Auto-Generation

This SDK is auto-generated from the Blender MCP server tool definitions by
`scripts/generate-mbt-blender-sdk.py`. To regenerate:

```bash
./scripts/generate-mbt-blender-sdk.py --verbose
```

**DO NOT EDIT** the generated files — changes will be overwritten.
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate the MoonBit (blender) MCP SDK from Blender MCP tool definitions."
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent.parent / "sdk" / "mbt",
        help="Output directory (default: sdk/mbt/)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    tools = parse_all_tools()
    print(f"Parsed {len(tools)} tools from Blender MCP tools")

    if args.verbose:
        for t in tools:
            req = [p.name for p in t.required_params]
            opt = [p.name for p in t.optional_params]
            print(f"  {t.name} ({t.category})")
            print(f"    desc: {t.description[:80]}...")
            if req:
                print(f"    required: {req}")
            if opt:
                print(f"    optional: {opt}")
            print()

    # Create output directories
    pkg_dir = args.output / "blender"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    client_mbt = gen_client_mbt(tools)
    tools_mbt = gen_tools_mbt(tools)
    moon_mod = gen_moon_mod()
    moon_pkg = gen_moon_pkg()
    readme_md = gen_readme_md(tools)

    # Remove old-format files if they exist
    for old_file in ["moon.mod.json", "moon.pkg.json"]:
        old_path = pkg_dir / old_file
        if old_path.exists():
            old_path.unlink()

    (pkg_dir / "client.mbt").write_text(client_mbt)
    (pkg_dir / "tools.mbt").write_text(tools_mbt)
    (pkg_dir / "moon.mod").write_text(moon_mod)
    (pkg_dir / "moon.pkg").write_text(moon_pkg)
    (pkg_dir / "README.md").write_text(readme_md)

    # Run moon fmt on generated source files
    try:
        subprocess.run(["moon", "fmt", str(pkg_dir)],
                       check=False, capture_output=True, timeout=30)
    except Exception:
        pass

    # Re-read formatted files for accurate line count
    client_lines = len((pkg_dir / "client.mbt").read_text().splitlines())
    tools_lines = len((pkg_dir / "tools.mbt").read_text().splitlines())
    readme_lines = len((pkg_dir / "README.md").read_text().splitlines())

    print(f"Generated MoonBit SDK in {pkg_dir}:")
    print(f"  client.mbt      ({client_lines:>5} lines)")
    print(f"  tools.mbt       ({tools_lines:>5} lines)")
    print(f"  moon.mod")
    print(f"  moon.pkg")
    print(f"  README.md       ({readme_lines:>5} lines)")
    print(f"\n  Total: {len(tools)} tools across {len(set(t.category for t in tools))} categories")


if __name__ == "__main__":
    main()
