#!/usr/bin/env python3
"""Generate an idiomatic Go SDK for the PicoGK MCP server.

Parses all MCP tool definitions from PicoGK.Mcp/Tools/*.cs and emits
a complete Go package (picogk) with:
  - A Client struct that manages the MCP stdio subprocess
  - Builder-pattern method functions for all 62 tools
  - Full doc comments on every function
  - A README.md with usage examples

Usage:
    ./scripts/generate-go-mcp-sdk.py [--output DIR] [--verbose]

Output goes to sdk/go/ by default.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Add scripts/ to path for the shared parser
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _parse_mcp_tools import parse_mcp_tools, ToolDef, Param

GENERATED_HEADER = "// Code generated by scripts/generate-go-mcp-sdk.py — DO NOT EDIT.\n"


# ---------------------------------------------------------------------------
# Type mapping: C# -> Go
# ---------------------------------------------------------------------------

def go_type(cs_type: str) -> str:
    """Map a C# type to its Go equivalent."""
    if cs_type == "float":
        return "float64"
    if cs_type == "int":
        return "int"
    if cs_type == "bool":
        return "bool"
    if cs_type in ("string", "string?"):
        return "string"
    if cs_type == "string[]":
        return "[]string"
    return "interface{}"


def go_zero(cs_type: str) -> str:
    """Return the Go zero value for a type."""
    if cs_type == "float":
        return "0"
    if cs_type == "int":
        return "0"
    if cs_type == "bool":
        return "false"
    if cs_type in ("string", "string?"):
        return '""'
    if cs_type == "string[]":
        return "nil"
    return "nil"


def go_json_type(cs_type: str) -> str:
    """Return how the value should appear in JSON encoding."""
    if cs_type == "float":
        return "float64"
    if cs_type == "int":
        return "int"
    if cs_type == "bool":
        return "bool"
    if cs_type in ("string", "string?"):
        return "string"
    if cs_type == "string[]":
        return "[]string"
    return "interface{}"


def is_pointer_optional(cs_type: str) -> bool:
    """For string? we still use string (Go strings are nil-able via "")."""
    return False


# ---------------------------------------------------------------------------
# Name conversion
# ---------------------------------------------------------------------------

def go_field_name(param_name: str) -> str:
    """Convert snake_case param name to Go-idiomatic exported field name."""
    parts = param_name.split("_")
    return "".join(p[:1].upper() + p[1:] for p in parts)


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def gen_client_go(tools: list[ToolDef]) -> str:
    """Generate the core client.go file."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("package picogk")
    lines.append("")
    lines.append("import (")
    lines.append('\t"bufio"')
    lines.append('\t"context"')
    lines.append('\t"encoding/json"')
    lines.append('\t"fmt"')
    lines.append('\t"io"')
    lines.append('\t"os"')
    lines.append('\t"os/exec"')
    lines.append('\t"path/filepath"')
    lines.append('\t"strings"')
    lines.append('\t"sync"')
    lines.append(")")
    lines.append("")
    lines.append("// Client manages a connection to the PicoGK MCP server.")
    lines.append("// It launches the server as a subprocess and communicates via JSON-RPC over stdio.")
    lines.append("//")
    lines.append("// Usage:")
    lines.append("//\t// Uses default server at $HOME/.local/bin/picogk-mcp/PicoGK.Mcp")
    lines.append("//\tclient, err := picogk.NewClient(ctx, \"\")")
    lines.append("//\tdefer client.Close(ctx)")
    lines.append("//\t// Or specify a custom path:")
    lines.append("//\tclient, err := picogk.NewClient(ctx, \"/custom/path/to/PicoGK.Mcp\")")
    lines.append("//\t// Initialize the geometry kernel")
    lines.append("//\tres, err := client.PicogkInit(ctx, picogk.PicogkInitRequest{VoxelSizeMM: 0.5})")
    lines.append("//\t// Create a sphere, subtract a box, export STL...")
    lines.append("type Client struct {")
    lines.append("\tcmd       *exec.Cmd")
    lines.append("\tstdin     io.WriteCloser")
    lines.append("\tstdout    *bufio.Reader")
    lines.append("\tmu        sync.Mutex")
    lines.append("\tmsgID     int")
    lines.append("\tserverBin string")
    lines.append("}")
    lines.append("")
    lines.append("// DefaultServerBin is the default path to the PicoGK MCP server binary.")
    lines.append("// It can be overridden by passing a non-empty path to NewClient.")
    lines.append("const DefaultServerBin = \"~/.local/bin/picogk-mcp/PicoGK.Mcp\"")
    lines.append("")
    lines.append("// NewClient launches the PicoGK MCP server binary and returns a Client.")
    lines.append("// If serverBin is empty, uses DefaultServerBin ($HOME/.local/bin/picogk-mcp/PicoGK.Mcp).")
    lines.append("// Expand ~ to the user's home directory automatically.")
    lines.append("func NewClient(ctx context.Context, serverBin string) (*Client, error) {")
    lines.append("\tif serverBin == \"\" {")
    lines.append("\t\tserverBin = DefaultServerBin")
    lines.append("\t}")
    lines.append("\tserverBin = expandPath(serverBin)")
    lines.append("\tcmd := exec.CommandContext(ctx, serverBin)")
    lines.append("\tstdin, err := cmd.StdinPipe()")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn nil, fmt.Errorf(\"creating stdin pipe: %w\", err)")
    lines.append("\t}")
    lines.append("\tstdout, err := cmd.StdoutPipe()")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn nil, fmt.Errorf(\"creating stdout pipe: %w\", err)")
    lines.append("\t}")
    lines.append("\tif err := cmd.Start(); err != nil {")
    lines.append("\t\treturn nil, fmt.Errorf(\"starting server: %w\", err)")
    lines.append("\t}")
    lines.append("\tc := &Client{")
    lines.append("\t\tcmd:       cmd,")
    lines.append("\t\tstdin:     stdin,")
    lines.append("\t\tstdout:    bufio.NewReader(stdout),")
    lines.append("\t\tserverBin: serverBin,")
    lines.append("\t}")
    lines.append("\t// Perform MCP initialize handshake")
    lines.append("\tif err := c.initialize(ctx); err != nil {")
    lines.append("\t\tcmd.Process.Kill()")
    lines.append("\t\treturn nil, fmt.Errorf(\"initialize handshake: %w\", err)")
    lines.append("\t}")
    lines.append("\treturn c, nil")
    lines.append("}")
    lines.append("")
    lines.append("// Close shuts down the MCP server process.")
    lines.append("func (c *Client) Close(ctx context.Context) error {")
    lines.append("\tc.mu.Lock()")
    lines.append("\tdefer c.mu.Unlock()")
    lines.append("\tif c.stdin != nil {")
    lines.append("\t\tc.stdin.Close()")
    lines.append("\t}")
    lines.append("\tif c.cmd != nil && c.cmd.Process != nil {")
    lines.append("\t\tdone := make(chan struct{})")
    lines.append("\t\tgo func() {")
    lines.append("\t\t\tc.cmd.Wait()")
    lines.append("\t\t\tclose(done)")
    lines.append("\t\t}()")
    lines.append("\t\tselect {")
    lines.append("\t\tcase <-done:")
    lines.append("\t\tcase <-ctx.Done():")
    lines.append("\t\t\tc.cmd.Process.Kill()")
    lines.append("\t\t\t<-done")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn nil")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("// expandPath expands a leading ~ to the user's home directory.")
    lines.append("func expandPath(path string) string {")
    lines.append('\tif strings.HasPrefix(path, "~") {')
    lines.append('\t\thome, err := os.UserHomeDir()')
    lines.append('\t\tif err == nil {')
    lines.append('\t\t\tpath = filepath.Join(home, path[1:])')
    lines.append('\t\t}')
    lines.append('\t}')
    lines.append('\treturn path')
    lines.append("}")
    lines.append("")
    lines.append("// --- JSON-RPC internals ---")
    lines.append("")
    lines.append("type jsonRPCRequest struct {")
    lines.append('\tJSONRPC string      `json:"jsonrpc"`')
    lines.append("\tID       int         `json:\"id\"`")
    lines.append("\tMethod   string      `json:\"method\"`")
    lines.append("\tParams   interface{} `json:\"params\"`")
    lines.append("}")
    lines.append("")
    lines.append("type jsonRPCResponse struct {")
    lines.append('\tJSONRPC string          `json:"jsonrpc"`')
    lines.append("\tID       int             `json:\"id\"`")
    lines.append("\tResult   json.RawMessage `json:\"result,omitempty\"`")
    lines.append("\tError    *jsonRPCErr     `json:\"error,omitempty\"`")
    lines.append("}")
    lines.append("")
    lines.append("type jsonRPCErr struct {")
    lines.append("\tCode    int    `json:\"code\"`")
    lines.append("\tMessage string `json:\"message\"`")
    lines.append("}")
    lines.append("")
    lines.append("type toolResult struct {")
    lines.append("\tContent []struct {")
    lines.append("\t\tType string `json:\"type\"`")
    lines.append("\t\tText string `json:\"text\"`")
    lines.append("\t} `json:\"content\"`")
    lines.append("\tIsError bool `json:\"isError\"`")
    lines.append("}")
    lines.append("")
    lines.append("func (c *Client) initialize(ctx context.Context) error {")
    lines.append("\treq := map[string]interface{}{")
    lines.append('\t\t"jsonrpc": "2.0",')
    lines.append('\t\t"id":      c.nextID(),')
    lines.append('\t\t"method":  "initialize",')
    lines.append('\t\t"params": map[string]interface{}{')
    lines.append('\t\t\t"protocolVersion": "2024-11-05",')
    lines.append('\t\t\t"capabilities":   map[string]interface{}{},')
    lines.append('\t\t\t"clientInfo": map[string]interface{}{')
    lines.append('\t\t\t\t"name":    "picogk",')
    lines.append('\t\t\t\t"version": "1.0.0",')
    lines.append('\t\t\t},')
    lines.append('\t\t},')
    lines.append("\t}")
    lines.append("\t_, err := c.call(ctx, req)")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn err")
    lines.append("\t}")
    lines.append("\t// Send initialized notification")
    lines.append("\tnotif := map[string]interface{}{")
    lines.append('\t\t"jsonrpc": "2.0",')
    lines.append('\t\t"method":  "notifications/initialized",')
    lines.append("\t}")
    lines.append("\treturn c.send(notif)")
    lines.append("}")
    lines.append("")
    lines.append("func (c *Client) nextID() int {")
    lines.append("\tc.mu.Lock()")
    lines.append("\tdefer c.mu.Unlock()")
    lines.append("\tc.msgID++")
    lines.append("\treturn c.msgID")
    lines.append("}")
    lines.append("")
    lines.append("func (c *Client) send(msg interface{}) error {")
    lines.append("\tdata, err := json.Marshal(msg)")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn fmt.Errorf(\"marshaling: %w\", err)")
    lines.append("\t}")
    lines.append("\tc.mu.Lock()")
    lines.append("\tdefer c.mu.Unlock()")
    lines.append("\t_, err = c.stdin.Write(append(data, '\\n'))")
    lines.append("\treturn err")
    lines.append("}")
    lines.append("")
    lines.append("func (c *Client) call(ctx context.Context, req interface{}) (json.RawMessage, error) {")
    lines.append("\tif err := c.send(req); err != nil {")
    lines.append("\t\treturn nil, err")
    lines.append("\t}")
    lines.append("\t// Read response line")
    lines.append("\tline, err := c.stdout.ReadString('\\n')")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn nil, fmt.Errorf(\"reading response: %w\", err)")
    lines.append("\t}")
    lines.append("\tvar resp jsonRPCResponse")
    lines.append("\tif err := json.Unmarshal([]byte(line), &resp); err != nil {")
    lines.append('\t\treturn nil, fmt.Errorf("parsing response: %w (line: %q)", err, line)')
    lines.append("\t}")
    lines.append("\tif resp.Error != nil {")
    lines.append("\t\treturn nil, fmt.Errorf(\"server error [%d]: %s\", resp.Error.Code, resp.Error.Message)")
    lines.append("\t}")
    lines.append("\treturn resp.Result, nil")
    lines.append("}")
    lines.append("")
    lines.append("// callTool invokes an MCP tool by name and returns the text content of the response.")
    lines.append("func (c *Client) callTool(ctx context.Context, toolName string, args map[string]interface{}) (string, error) {")
    lines.append("\treq := map[string]interface{}{")
    lines.append('\t\t"jsonrpc": "2.0",')
    lines.append('\t\t"id":      c.nextID(),')
    lines.append('\t\t"method":  "tools/call",')
    lines.append('\t\t"params": map[string]interface{}{')
    lines.append('\t\t\t"name":      toolName,')
    lines.append('\t\t\t"arguments": args,')
    lines.append('\t\t},')
    lines.append("\t}")
    lines.append("\tresult, err := c.call(ctx, req)")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn \"\", err")
    lines.append("\t}")
    lines.append("\tvar tr toolResult")
    lines.append("\tif err := json.Unmarshal(result, &tr); err != nil {")
    lines.append('\t\treturn "", fmt.Errorf("parsing tool result: %w", err)')
    lines.append("\t}")
    lines.append("\tvar text string")
    lines.append("\tfor _, item := range tr.Content {")
    lines.append("\t\tif item.Type == \"text\" {")
    lines.append("\t\t\ttext += item.Text")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\tif tr.IsError {")
    lines.append('\t\treturn text, fmt.Errorf("tool error: %s", text)')
    lines.append("\t}")
    lines.append("\treturn text, nil")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_tools_go(tools: list[ToolDef]) -> str:
    """Generate the tools.go file with one builder struct + method per tool."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("package picogk")
    lines.append("")
    lines.append("import (")
    lines.append('\t"context"')
    lines.append(")")
    lines.append("")

    # Group tools by category
    categories: dict[str, list[ToolDef]] = {}
    for t in tools:
        categories.setdefault(t.category, []).append(t)

    for category, cat_tools in categories.items():
        lines.append(f"// --- {category} ---")
        lines.append("")

        for tool in cat_tools:
            # Generate request struct
            req_struct = f"{tool.name}Request"
            lines.append(f"// {req_struct} holds parameters for the {tool.snake_name} tool.")
            lines.append(f"// {tool.description}")
            lines.append(f"type {req_struct} struct {{")
            for p in tool.params:
                go_t = go_type(p.cs_type)
                field = go_field_name(p.name)
                json_tag = p.name
                if p.has_default:
                    # Use pointer for optional params so we can distinguish "not set"
                    if p.cs_type == "float":
                        go_t = "*float64"
                    elif p.cs_type == "int":
                        go_t = "*int"
                    elif p.cs_type == "bool":
                        go_t = "*bool"
                    elif p.cs_type in ("string", "string?"):
                        go_t = "*string"
                    elif p.cs_type == "string[]":
                        go_t = "[]string"  # nil means not set
                    # json omitempty for optionals
                    lines.append(f"\t{field} {go_t} `json:\"{json_tag},omitempty\"`")
                else:
                    lines.append(f"\t{field} {go_t} `json:\"{json_tag}\"`")
            lines.append("}")
            lines.append("")

            # Generate method on Client
            lines.append(f"// {tool.name} calls the {tool.snake_name} MCP tool.")
            lines.append(f"// {tool.description}")
            if tool.required_params:
                req_params_str = ", ".join(
                    p.name for p in tool.required_params
                )
            lines.append(f"func (c *Client) {tool.name}(ctx context.Context, req {req_struct}) (string, error) {{")

            # Build args map
            lines.append("\targs := map[string]interface{}{}")
            for p in tool.params:
                field = go_field_name(p.name)
                if p.has_default:
                    if p.cs_type == "string[]":
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f"\t\targs[\"{p.name}\"] = req.{field}")
                        lines.append(f"\t}}")
                    else:
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f"\t\targs[\"{p.name}\"] = *req.{field}")
                        lines.append(f"\t}}")
                else:
                    if p.cs_type == "string[]":
                        lines.append(f"\targs[\"{p.name}\"] = req.{field}")
                    else:
                        lines.append(f"\targs[\"{p.name}\"] = req.{field}")

            lines.append(f"\treturn c.callTool(ctx, \"{tool.snake_name}\", args)")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def gen_go_mod(version: str = "1.0.0") -> str:
    """Generate go.mod."""
    return f"""module github.com/gmlewis/PicoGK/sdk/go/picogk

go 1.22

// picogk: PicoGK MCP SDK for Go
// Version: {version}
"""


def gen_readme_md(tools: list[ToolDef]) -> str:
    """Generate the SDK README.md."""
    tool_count = len(tools)
    category_list: dict[str, list[str]] = {}
    for t in tools:
        category_list.setdefault(t.category, []).append(t.snake_name)

    cat_table = "\n".join(
        f"| **{cat}** | {', '.join(names)} |"
        for cat, names in sorted(category_list.items())
    )

    return f"""# picogk — Go SDK for the PicoGK MCP Server

`picogk` is an auto-generated Go SDK for the [PicoGK](https://picogk.org) geometry
kernel's MCP (Model Context Protocol) server. It provides a fully typed, idiomatic Go
interface to all {tool_count} PicoGK tools — from creating primitives to boolean operations,
lattice design, mesh manipulation, rendering, and 3D-printing export.

## Quick Start

```bash
go get github.com/gmlewis/PicoGK/sdk/go/picogk
```

```go
package main

import (
    "context"
    "fmt"
    "log"

    "github.com/gmlewis/PicoGK/sdk/go/picogk"
)

func main() {{
    ctx := context.Background()

    // Launch the PicoGK MCP server (default path: $HOME/.local/bin/picogk-mcp/PicoGK.Mcp)
    client, err := picogk.NewClient(ctx, "")
    if err != nil {{
        log.Fatal(err)
    }}
    defer client.Close(ctx)

    // Initialize the geometry kernel (0.5mm voxels)
    _, err = client.PicogkInit(ctx, picogk.PicogkInitRequest{{
        VoxelSizeMM: float64Ptr(0.5),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Create a sphere
    res, err := client.CreateSphere(ctx, picogk.CreateSphereRequest{{
        X:      0,
        Y:      0,
        Z:      0,
        Radius: 30,
        Id:     stringPtr("body"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}
    fmt.Println(res)

    // Create a box cutout
    _, err = client.CreateBox(ctx, picogk.CreateBoxRequest{{
        MinX: -10, MinY: -10, MinZ: -40,
        MaxX:  10, MaxY:  10, MaxZ: 40,
        Id:   stringPtr("cutout"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Subtract box from sphere
    _, err = client.BooleanSubtract(ctx, picogk.BooleanSubtractRequest{{
        A:  "body",
        B:  "cutout",
        Id: stringPtr("result"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Smooth the result
    _, err = client.Smooth(ctx, picogk.SmoothRequest{{
        ObjectId: "result",
        Distance: 2.0,
        Id:       stringPtr("smoothed"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Convert to mesh and export STL
    _, err = client.VoxelsToMesh(ctx, picogk.VoxelsToMeshRequest{{
        VoxelsId: "smoothed",
        Id:       stringPtr("mesh"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}
    _, err = client.SaveStl(ctx, picogk.SaveStlRequest{{
        MeshId: "mesh",
        Path:   "/tmp/part.stl",
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Render a preview
    _, err = client.RenderToImage(ctx, picogk.RenderToImageRequest{{
        ObjectId: "smoothed",
        Path:     "/tmp/preview.png",
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    fmt.Println("Done! Part exported to /tmp/part.stl")
}}

// Helper: create a float64 pointer
func float64Ptr(v float64) *float64 {{ return &v }}

// Helper: create a string pointer
func stringPtr(v string) *string {{ return &v }}
```

## API Overview

The SDK exposes all {tool_count} PicoGK MCP tools via builder-pattern request structs:

| Category | Tools |
|----------|-------|
{cat_table}

Each tool has:
- A `XxxRequest` struct with typed fields (optional params are pointers)
- A `Client.Xxx(ctx, req)` method returning `(string, error)`
- Full doc comments

## Architecture

The SDK launches the PicoGK MCP server as a subprocess and communicates via
JSON-RPC over stdio. No network connection is needed. The server binary must
be installed separately (see the main PicoGK README for build instructions).

## Auto-Generation

This SDK is auto-generated from the PicoGK C# MCP tool definitions by
`scripts/generate-go-mcp-sdk.py`. To regenerate:

```bash
./scripts/generate-go-mcp-sdk.py --verbose
```

**DO NOT EDIT** the generated files — changes will be overwritten. Edit the
C# tool definitions in `PicoGK.Mcp/Tools/*.cs` instead, then regenerate.
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate the Go (picogk) MCP SDK from PicoGK C# tool definitions."
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent.parent / "sdk" / "go",
        help="Output directory (default: sdk/go/)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    tools = parse_mcp_tools()
    print(f"Parsed {len(tools)} tools from PicoGK.Mcp/Tools/*.cs")

    # Create output directories
    pkg_dir = args.output / "picogk"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    client_go = gen_client_go(tools)
    tools_go = gen_tools_go(tools)
    go_mod = gen_go_mod()
    readme_md = gen_readme_md(tools)

    (pkg_dir / "client.go").write_text(client_go)
    (pkg_dir / "tools.go").write_text(tools_go)
    (pkg_dir / "go.mod").write_text(go_mod)
    (pkg_dir / "README.md").write_text(readme_md)

    # Run go fmt on generated source files
    import subprocess
    try:
        subprocess.run(["go", "fmt", str(pkg_dir / "client.go"), str(pkg_dir / "tools.go")],
                       check=True, capture_output=True, timeout=30)
    except Exception as e:
        print(f"  Warning: go fmt failed: {e}")

    # Re-read formatted files for accurate line count
    client_lines = len((pkg_dir / "client.go").read_text().splitlines())
    tools_lines = len((pkg_dir / "tools.go").read_text().splitlines())
    readme_lines = len((pkg_dir / "README.md").read_text().splitlines())

    print(f"Generated Go SDK in {pkg_dir}:")
    print(f"  client.go   ({client_lines:>5} lines)")
    print(f"  tools.go    ({tools_lines:>5} lines)")
    print(f"  go.mod")
    print(f"  README.md   ({readme_lines:>5} lines)")
    print(f"\n  Total: {len(tools)} tools across {len(set(t.category for t in tools))} categories")


if __name__ == "__main__":
    main()