#!/usr/bin/env python3
"""Generate an idiomatic MoonBit SDK for the PicoGK MCP server.

Parses all MCP tool definitions from PicoGK.Mcp/Tools/*.cs and emits
a complete MoonBit package (picogk) with:
  - A Client type that manages the MCP stdio subprocess
  - Builder-pattern method functions for all 62 tools
  - Full doc comments on every function
  - A README.md with usage examples

Usage:
    ./scripts/generate-mbt-mcp-sdk.py [--output DIR] [--verbose]

Output goes to sdk/mbt/ by default.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _parse_mcp_tools import parse_mcp_tools, ToolDef, Param

GENERATED_HEADER = "// Code generated by scripts/generate-mbt-mcp-sdk.py — DO NOT EDIT.\n"


# ---------------------------------------------------------------------------
# Type mapping: C# -> MoonBit
# ---------------------------------------------------------------------------

def mbt_type(cs_type: str) -> str:
    """Map a C# type to its MoonBit equivalent."""
    if cs_type == "float":
        return "Double"
    if cs_type == "int":
        return "Int"
    if cs_type == "bool":
        return "Bool"
    if cs_type in ("string", "string?"):
        return "String"
    if cs_type == "string[]":
        return "Array[String]"
    return "Unit"


def mbt_type_for_optional(cs_type: str) -> str:
    """For optional params, MoonBit uses Option[T]."""
    if cs_type == "float":
        return "Double?"
    if cs_type == "int":
        return "Int?"
    if cs_type == "bool":
        return "Bool?"
    if cs_type in ("string", "string?"):
        return "String?"
    if cs_type == "string[]":
        return "Array[String]?"  # nil means not set
    return "Unit"


def mbt_zero(cs_type: str) -> str:
    """Return the MoonBit zero/default value."""
    if cs_type == "float":
        return "0.0"
    if cs_type == "int":
        return "0"
    if cs_type == "bool":
        return "false"
    if cs_type in ("string", "string?"):
        return '""'
    if cs_type == "string[]":
        return "[]"
    return "Unit"


# ---------------------------------------------------------------------------
# Name conversion
# ---------------------------------------------------------------------------

def mbt_field_name(param_name: str) -> str:
    """Convert snake_case param name to MoonBit camelCase field name."""
    parts = param_name.split("_")
    result = parts[0]
    for p in parts[1:]:
        result += p[:1].upper() + p[1:]
    return result


def mbt_method_name(tool_name: str) -> str:
    """Convert PascalCase to MoonBit snake_case method name."""
    import re
    result = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", tool_name)
    result = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", result)
    return result.lower()


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def gen_client_mbt(tools: list[ToolDef]) -> str:
    """Generate the core client.mbt file using moonbitlang/async for process I/O."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("///")
    lines.append("/// Client manages a connection to the PicoGK MCP server.")
    lines.append("/// It launches the server as a subprocess and communicates via JSON-RPC over stdio.")
    lines.append("/// All tool methods are async and must be called within an `async fn main` block.")
    lines.append("///")
    lines.append("/// Usage:")
    lines.append('///   async fn main {')
    lines.append('///     // Uses default server at $HOME/.local/bin/picogk-mcp/PicoGK.Mcp')
    lines.append('///     let client = @picogk.new_client("")')
    lines.append('///     // Or specify a custom path:')
    lines.append('///     // let client = @picogk.new_client("/custom/path/to/PicoGK.Mcp")')
    lines.append('///     client.picogk_init(Some(0.5))')
    lines.append('///     client.create_sphere(0.0, 0.0, 0.0, 30.0, Some("body"))')
    lines.append('///     client.close()')
    lines.append('///   }')
    lines.append("///")
    lines.append("pub struct Client {")
    lines.append("  pid : Int")
    lines.append("  stdin : @process.WriteToProcess")
    lines.append("  stdout : @process.ReadFromProcess")
    lines.append("  mut msg_id : Int")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// default_server_bin returns the default path to the PicoGK MCP server binary.")
    lines.append("///")
    lines.append('let default_server_bin : String = "~/.local/bin/picogk-mcp/PicoGK.Mcp"')
    lines.append("")
    lines.append("///")
    lines.append("/// new_client launches the PicoGK MCP server binary and returns a Client.")
    lines.append("/// If server_bin is empty, uses default_server_bin.")
    lines.append("/// Must be called within an async function.")
    lines.append("///")
    lines.append("pub async fn new_client(server_bin : String) -> Client raise {")
    lines.append('  let bin = if server_bin == "" { default_server_bin } else { server_bin }')
    lines.append("  let path = expand_path(bin)")
    lines.append("  // Create pipes for stdin/stdout")
    lines.append("  let (stdin_read, stdin_write) = @process.write_to_process()")
    lines.append("  let (stdout_read, stdout_write) = @process.read_from_process()")
    lines.append("  // Spawn the server as an orphan process so it survives beyond any task group")
    lines.append("  let pid = @process.spawn_orphan(path, [], stdin=stdin_read, stdout=stdout_write)")
    lines.append("  let client = Client::{")
    lines.append("    pid: pid,")
    lines.append("    stdin: stdin_write,")
    lines.append("    stdout: stdout_read,")
    lines.append("    msg_id: 0,")
    lines.append("  }")
    lines.append("  // Perform MCP initialize handshake")
    lines.append("  client.initialize()")
    lines.append("  client")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// close shuts down the MCP server process.")
    lines.append("///")
    lines.append("pub fn Client::close(self : Client) -> Unit {")
    lines.append("  self.stdin.close()")
    lines.append("  self.stdout.close()")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// expand_path expands a leading ~ to the user's home directory.")
    lines.append("///")
    lines.append("fn expand_path(path : String) -> String {")
    lines.append('  if path.has_prefix("~") {')
    lines.append('    let home = @env.get_env_var("HOME").unwrap_or("")')
    lines.append('    home + path[1:].to_owned()')
    lines.append("  } else {")
    lines.append("    path")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("// --- JSON-RPC internals ---")
    lines.append("")
    lines.append("///")
    lines.append("/// next_id returns the next JSON-RPC request ID.")
    lines.append("///")
    lines.append("fn Client::next_id(self : Client) -> Int {")
    lines.append("  self.msg_id = self.msg_id + 1")
    lines.append("  self.msg_id")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// send_line writes a JSON-RPC message to the server's stdin.")
    lines.append("///")
    lines.append("async fn Client::send_line(self : Client, json_str : String) -> Unit raise {")
    lines.append('  let data = @utf8.encode(json_str + "\\n")')
    lines.append("  let _ = self.stdin.write_once(data, offset=0, len=data.length())")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// read_line reads a JSON-RPC response line from the server's stdout.")
    lines.append("///")
    lines.append("async fn Client::read_line(self : Client) -> String raise {")
    lines.append("  match self.stdout.read_until(\"\\n\") {")
    lines.append("    Some(line) => line")
    lines.append('    None => raise Failure::Failure("EOF: no more data from server")')
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// call_tool invokes an MCP tool by name and returns the text response.")
    lines.append("///")
    lines.append("pub async fn Client::call_tool(self : Client, tool_name : String, args : Map[String, Json]) -> String raise {")
    lines.append("  let id = self.next_id()")
    lines.append("  let req = Json::object(Map([")
    lines.append('    ("jsonrpc", Json::string("2.0")),')
    lines.append("    (\"id\", Json::number(id.to_double())),")
    lines.append('    ("method", Json::string("tools/call")),')
    lines.append('    ("params", Json::object(Map([')
    lines.append('      ("name", Json::string(tool_name)),')
    lines.append('      ("arguments", Json::object(args)),')
    lines.append("    ]))),")
    lines.append("  ]))")
    lines.append("  self.send_line(req.stringify())")
    lines.append("  let response = self.read_line()")
    lines.append("  // Parse response and extract text content")
    lines.append("  // Some tools (e.g. picogk_shutdown) may return non-JSON; return raw text in that case")
    lines.append("  try @json.parse(response) catch {")
    lines.append("    _ => return response")
    lines.append("  } noraise {")
    lines.append("    resp => {")
    lines.append("      match resp {")
    lines.append("        Object(fields) => {")
    lines.append('          let result = fields.get("result").unwrap()')
    lines.append("          match result {")
    lines.append("            Object(result_fields) => {")
    lines.append('              let content = result_fields.get("content").unwrap()')
    lines.append("              match content {")
    lines.append("                Array(items) => {")
    lines.append('                  let mut text = ""')
    lines.append("                  for item in items {")
    lines.append("                    match item {")
    lines.append("                      Object(item_fields) => {")
    lines.append('                        match item_fields.get("text") {')
    lines.append("                          Some(String(s)) => text = text + s")
    lines.append("                          _ => ()")
    lines.append("                        }")
    lines.append("                      }")
    lines.append("                      _ => ()")
    lines.append("                    }")
    lines.append("                  }")
    lines.append("                  text")
    lines.append("                }")
    lines.append('                _ => raise Failure::Failure("unexpected content format")')
    lines.append("              }")
    lines.append("            }")
    lines.append('            _ => raise Failure::Failure("unexpected result format")')
    lines.append("          }")
    lines.append("        }")
    lines.append("        _ => response")
    lines.append("      }")
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///")
    lines.append("/// initialize performs the MCP initialize handshake.")
    lines.append("///")
    lines.append("async fn Client::initialize(self : Client) -> Unit raise {")
    lines.append("  let id = self.next_id()")
    lines.append("  let req = Json::object(Map([")
    lines.append('    ("jsonrpc", Json::string("2.0")),')
    lines.append("    (\"id\", Json::number(id.to_double())),")
    lines.append('    ("method", Json::string("initialize")),')
    lines.append('    ("params", Json::object(Map([')
    lines.append('      ("protocolVersion", Json::string("2024-11-05")),')
    lines.append('      ("capabilities", Json::object(Map([]))),')
    lines.append('      ("clientInfo", Json::object(Map([')
    lines.append('        ("name", Json::string("picogk")),')
    lines.append('        ("version", Json::string("0.1.0")),')
    lines.append("      ]))),")
    lines.append("    ]))),")
    lines.append("  ]))")
    lines.append("  self.send_line(req.stringify())")
    lines.append("  let _ = self.read_line()")
    lines.append("  // Send initialized notification")
    lines.append("  let notif = Json::object(Map([")
    lines.append('    ("jsonrpc", Json::string("2.0")),')
    lines.append('    ("method", Json::string("notifications/initialized")),')
    lines.append("  ]))")
    lines.append("  self.send_line(notif.stringify())")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_tools_mbt(tools: list[ToolDef]) -> str:
    """Generate the tools.mbt file with one method per tool."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    # Group tools by category
    categories: dict[str, list[ToolDef]] = {}
    for t in tools:
        categories.setdefault(t.category, []).append(t)

    for category, cat_tools in categories.items():
        lines.append(f"// === {category} ===")
        lines.append("")

        for tool in cat_tools:
            method_name = mbt_method_name(tool.name)
            # Build function signature
            params_sig: list[str] = []
            for p in tool.params:
                if p.has_default:
                    mbt_t = mbt_type_for_optional(p.cs_type)
                else:
                    mbt_t = mbt_type(p.cs_type)
                params_sig.append(f"{mbt_field_name(p.name)} : {mbt_t}")

            params_str = ", ".join(params_sig)

            # Build the args map construction
            args_lines: list[str] = []
            for p in tool.params:
                field = mbt_field_name(p.name)
                json_key = p.name
                if p.has_default:
                    if p.cs_type == "string[]":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(arr) => args.set(\"{json_key}\", Json::array(arr.map(fn(s) {{ Json::string(s) }})))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type == "float":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", Json::number(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type == "int":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", Json::number(v.to_double()))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type == "bool":
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", Json::boolean(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                    elif p.cs_type in ("string", "string?"):
                        args_lines.append(f"  match {field} {{")
                        args_lines.append(f"    Some(v) => args.set(\"{json_key}\", Json::string(v))")
                        args_lines.append(f"    None => ()")
                        args_lines.append(f"  }}")
                else:
                    if p.cs_type == "float":
                        args_lines.append(f"  args.set(\"{json_key}\", Json::number({field}))")
                    elif p.cs_type == "int":
                        args_lines.append(f"  args.set(\"{json_key}\", Json::number({field}.to_double()))")
                    elif p.cs_type == "bool":
                        args_lines.append(f"  args.set(\"{json_key}\", Json::boolean({field}))")
                    elif p.cs_type in ("string", "string?"):
                        args_lines.append(f"  args.set(\"{json_key}\", Json::string({field}))")
                    elif p.cs_type == "string[]":
                        args_lines.append(f"  args.set(\"{json_key}\", Json::array({field}.map(fn(s) {{ Json::string(s) }})))")

            # Write doc comment
            # Escape the description for MoonBit comments
            desc = tool.description.replace('\n', '\n  ///')
            lines.append(f"///")
            lines.append(f"/// {method_name} — {tool.snake_name}")
            lines.append(f"/// {desc}")
            lines.append(f"///")

            # Function signature — all tools are async
            if params_str:
                lines.append(f"pub async fn Client::{method_name}(self : Client, {params_str}) -> String raise {{")
            else:
                lines.append(f"pub async fn Client::{method_name}(self : Client) -> String raise {{")

            lines.append(f"  let args : Map[String, Json] = {{}}")
            if args_lines:
                lines.extend(args_lines)
            lines.append(f"  self.call_tool(\"{tool.snake_name}\", args)")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def gen_moon_mod() -> str:
    """Generate moon.mod (new format, not JSON)."""
    return """// picogk: PicoGK MCP SDK for MoonBit
// To regenerate, run: ./scripts/generate-mbt-mcp-sdk.py
// DO NOT EDIT — this file is auto-generated.

name = "gmlewis/picogk"

version = "0.1.0"

readme = "README.md"

repository = "https://github.com/gmlewis/PicoGK"

license = "Apache-2.0"

keywords = []

description = "MoonBit SDK for the PicoGK MCP geometry kernel server"

preferred_target = "native"

supported_targets = "+native"

import {
  "moonbitlang/async@0.19.2"
}
"""


def gen_moon_pkg() -> str:
    """Generate moon.pkg (new format, not JSON)."""
    return """// picogk package configuration
// DO NOT EDIT — this file is auto-generated.

import {
  "moonbitlang/async/process",
  "moonbitlang/core/json",
  "moonbitlang/core/env",
  "moonbitlang/core/encoding/utf8" @utf8,
}
"""


def gen_readme_md(tools: list[ToolDef]) -> str:
    """Generate the SDK README.md."""
    tool_count = len(tools)
    category_list: dict[str, list[str]] = {}
    for t in tools:
        category_list.setdefault(t.category, []).append(t.snake_name)

    cat_table = "\n".join(
        f"| **{cat}** | {', '.join(names)} |"
        for cat, names in sorted(category_list.items())
    )

    return f"""# picogk — MoonBit SDK for the PicoGK MCP Server

`picogk` is an auto-generated MoonBit SDK for the [PicoGK](https://picogk.org)
geometry kernel's MCP (Model Context Protocol) server. It provides a fully typed,
idiomatic MoonBit interface to all {tool_count} PicoGK tools — from creating
primitives to boolean operations, lattice design, mesh manipulation, rendering, and
3D-printing export.

All tool methods are **async** and use `moonbitlang/async` for subprocess management.
They must be called within an `async fn main` block.

## Quick Start

```bash
moon add gmlewis/picogk
```

```moonbit
///|
async fn main {{
  // Launch the PicoGK MCP server (default: $HOME/.local/bin/picogk-mcp/PicoGK.Mcp)
  let client = @picogk.new_client("")

  // Initialize the geometry kernel (0.5mm voxels)
  let _ = client.picogk_init(Some(0.5))

  // Create a sphere
  let res = client.create_sphere(0.0, 0.0, 0.0, 30.0, Some("body"))
  println(res)

  // Create a box cutout
  let _ = client.create_box(-10.0, -10.0, -40.0, 10.0, 10.0, 40.0, Some("cutout"))

  // Subtract box from sphere
  let _ = client.boolean_subtract("body", "cutout", Some("result"))

  // Smooth the result
  let _ = client.smooth("result", 2.0, Some("smoothed"))

  // Convert to mesh and export STL
  let _ = client.voxels_to_mesh("smoothed", Some("mesh"))
  let _ = client.save_stl("mesh", "/tmp/part.stl", None)

  // Render a preview
  let _ = client.render_to_image("smoothed", "/tmp/preview.png", None, None, None, None)

  // Clean up
  client.close()

  println("Done! Part exported to /tmp/part.stl")
}}
```

## API Overview

The SDK exposes all {tool_count} PicoGK MCP tools via typed methods:

| Category | Tools |
|----------|-------|
{cat_table}

Each tool has:
- A `Client::method_name(...)` method with typed parameters (snake_case)
- Optional parameters are `Option[T]` (use `Some(value)` or `None`)
- Returns `String` (the tool's text response) or raises `Failure` on error
- Full doc comments

## Architecture

The SDK launches the PicoGK MCP server as a subprocess and communicates via
JSON-RPC over stdio. No network connection is needed. The server binary must
be installed separately (see the main PicoGK README for build instructions).

## Auto-Generation

This SDK is auto-generated from the PicoGK C# MCP tool definitions by
`scripts/generate-mbt-mcp-sdk.py`. To regenerate:

```bash
./scripts/generate-mbt-mcp-sdk.py --verbose
```

**DO NOT EDIT** the generated files — changes will be overwritten. Edit the
C# tool definitions in `PicoGK.Mcp/Tools/*.cs` instead, then regenerate.
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate the MoonBit (picogk) MCP SDK from PicoGK C# tool definitions."
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent.parent / "sdk" / "mbt",
        help="Output directory (default: sdk/mbt/)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    tools = parse_mcp_tools()
    print(f"Parsed {len(tools)} tools from PicoGK.Mcp/Tools/*.cs")

    # Create output directories
    pkg_dir = args.output / "picogk"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    client_mbt = gen_client_mbt(tools)
    tools_mbt = gen_tools_mbt(tools)
    moon_mod = gen_moon_mod()
    moon_pkg = gen_moon_pkg()
    readme_md = gen_readme_md(tools)

    # Remove old-format files if they exist
    for old_file in ["moon.mod.json", "moon.pkg.json"]:
        old_path = pkg_dir / old_file
        if old_path.exists():
            old_path.unlink()

    (pkg_dir / "client.mbt").write_text(client_mbt)
    (pkg_dir / "tools.mbt").write_text(tools_mbt)
    (pkg_dir / "moon.mod").write_text(moon_mod)
    (pkg_dir / "moon.pkg").write_text(moon_pkg)
    (pkg_dir / "README.md").write_text(readme_md)

    # Run moon fmt on generated source files
    import subprocess
    try:
        subprocess.run(["moon", "fmt", str(pkg_dir)],
                       check=False, capture_output=True, timeout=30)
    except Exception:
        pass  # moon fmt may not be available or may warn — non-fatal

    # Re-read formatted files for accurate line count
    client_lines = len((pkg_dir / "client.mbt").read_text().splitlines())
    tools_lines = len((pkg_dir / "tools.mbt").read_text().splitlines())
    readme_lines = len((pkg_dir / "README.md").read_text().splitlines())

    print(f"Generated MoonBit SDK in {pkg_dir}:")
    print(f"  client.mbt      ({client_lines:>5} lines)")
    print(f"  tools.mbt       ({tools_lines:>5} lines)")
    print(f"  moon.mod")
    print(f"  moon.pkg")
    print(f"  README.md       ({readme_lines:>5} lines)")
    print(f"\n  Total: {len(tools)} tools across {len(set(t.category for t in tools))} categories")


if __name__ == "__main__":
    main()