#!/usr/bin/env python3
"""Generate an idiomatic Go SDK for the PicoGK MCP server.

Parses all MCP tool definitions from PicoGK.Mcp/Tools/*.cs and emits
a complete Go package (picogk) with:
  - A Client struct that manages the MCP stdio subprocess
  - Builder-pattern method functions for all 62 tools
  - Full doc comments on every function
  - A README.md with usage examples

Usage:
    ./scripts/generate-go-picogk-sdk.py [--output DIR] [--verbose]

Output goes to sdk/go/ by default.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Add scripts/ to path for the shared parser
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _parse_mcp_tools import parse_mcp_tools, ToolDef, Param

GENERATED_HEADER = "// Code generated by scripts/generate-go-picogk-sdk.py — DO NOT EDIT.\n"


# ---------------------------------------------------------------------------
# Type mapping: C# -> Go
# ---------------------------------------------------------------------------

def go_type(cs_type: str) -> str:
    """Map a C# type to its Go equivalent."""
    if cs_type == "float":
        return "float64"
    if cs_type == "int":
        return "int"
    if cs_type == "bool":
        return "bool"
    if cs_type in ("string", "string?"):
        return "string"
    if cs_type == "string[]":
        return "[]string"
    return "any"


def go_zero(cs_type: str) -> str:
    """Return the Go zero value for a type."""
    if cs_type == "float":
        return "0"
    if cs_type == "int":
        return "0"
    if cs_type == "bool":
        return "false"
    if cs_type in ("string", "string?"):
        return '""'
    if cs_type == "string[]":
        return "nil"
    return "nil"


def go_json_type(cs_type: str) -> str:
    """Return how the value should appear in JSON encoding."""
    if cs_type == "float":
        return "float64"
    if cs_type == "int":
        return "int"
    if cs_type == "bool":
        return "bool"
    if cs_type in ("string", "string?"):
        return "string"
    if cs_type == "string[]":
        return "[]string"
    return "any"


def is_pointer_optional(cs_type: str) -> bool:
    """For string? we still use string (Go strings are nil-able via "")."""
    return False


# ---------------------------------------------------------------------------
# Name conversion
# ---------------------------------------------------------------------------

def go_tool_name(tool_name: str) -> str:
    """Apply Go initialism rules to a tool name (e.g. SaveStl -> SaveSTL)."""
    replacements = {
        "Stl": "STL",
        "Svg": "SVG",
        "VdbFields": "VDBFields",
        "Vdb": "VDB",
        "Cli": "CLI",
    }
    for old, new in replacements.items():
        if tool_name.endswith(old):
            return tool_name[:-len(old)] + new
    if tool_name.startswith("Picogk"):
        return tool_name[6:]
    return tool_name


def capitalize_initialisms(p: str) -> str:
    """Capitalize words, checking for common Go initialisms"""
    if p == "ids":
        return "IDs"
    if p == "id":
        return "ID"

    if p.endswith("IdA"):
        p = p[:-3] + "IDA"
    if p.endswith("IdB"):
        p = p[:-3] + "IDB"
    if p.endswith("Ids"):
        p = p[:-3] + "IDs"
    if p.endswith("Id"):
        p = p[:-2] + "ID"
    return p[:1].upper() + p[1:]

def capitalize_field_name(parts: list[str]) -> str:
    wp = [capitalize_initialisms(p) for p in parts]
    return "".join(wp)

def go_field_name(param_name: str) -> str:
    """Convert snake_case param name to Go-idiomatic exported field name."""
    parts = param_name.split("_")
    return capitalize_field_name(parts)


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def gen_client_go(tools: list[ToolDef]) -> str:
    """Generate the core client.go file."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("""package picogk

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

// Client manages a connection to the PicoGK MCP server.
// It launches the server as a subprocess and communicates via JSON-RPC over stdio.
//
// Usage:
//
//	// Uses default server at $HOME/.local/bin/picogk-mcp/PicoGK.Mcp
//	client, err := picogk.NewClient(ctx, "")
//	defer client.Close()
//	// Or specify a custom path:
//	client, err := picogk.NewClient(ctx, "/custom/path/to/PicoGK.Mcp")
//	// Initialize the geometry kernel
//	res, err := client.PicoGKInit(picogk.PicoGKInitRequest{VoxelSizeMM: 0.5})
//	// Create a sphere, subtract a box, export STL...
type Client struct {
	ctx       context.Context
	cmd       *exec.Cmd
	stdin     io.WriteCloser
	stdout    *bufio.Reader
	mu        sync.Mutex
	msgID     int
	serverBin string
}

// DefaultServerBin is the default path to the PicoGK MCP server binary.
// It can be overridden by passing a non-empty path to NewClient.
const DefaultServerBin = "~/.local/bin/picogk-mcp/PicoGK.Mcp"

// NewClient launches the PicoGK MCP server binary and returns a Client.
// If serverBin is empty, uses DefaultServerBin ($HOME/.local/bin/picogk-mcp/PicoGK.Mcp).
// Expand ~ to the user's home directory automatically.
func NewClient(ctx context.Context, serverBin string) (*Client, error) {
	if serverBin == "" {
		serverBin = DefaultServerBin
	}
	serverBin = expandPath(serverBin)
	cmd := exec.CommandContext(ctx, serverBin)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdin pipe: %w", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdout pipe: %w", err)
	}
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("starting server: %w", err)
	}
	c := &Client{
		ctx:       ctx,
		cmd:       cmd,
		stdin:     stdin,
		stdout:    bufio.NewReader(stdout),
		serverBin: serverBin,
	}
	// Perform MCP initialize handshake
	if err := c.initialize(); err != nil {
		cmd.Process.Kill()
		return nil, fmt.Errorf("initialize handshake: %w", err)
	}
	return c, nil
}

// Close shuts down the MCP server process.
func (c *Client) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.stdin != nil {
		c.stdin.Close()
	}
	if c.cmd != nil && c.cmd.Process != nil {
		done := make(chan struct{})
		go func() {
			c.cmd.Wait()
			close(done)
		}()
		select {
		case <-done:
		case <-c.ctx.Done():
			c.cmd.Process.Kill()
			<-done
		}
	}
	return nil
}

// expandPath expands a leading ~ to the user's home directory.
func expandPath(path string) string {
	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err == nil {
			path = filepath.Join(home, path[1:])
		}
	}
	return path
}

// --- JSON-RPC internals ---

type jsonRPCRequest struct {
	JSONRPC string `json:"jsonrpc"`
	ID      int    `json:"id"`
	Method  string `json:"method"`
	Params  any    `json:"params"`
}

type jsonRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      int             `json:"id"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *jsonRPCErr     `json:"error,omitempty"`
}

type jsonRPCErr struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type toolResult struct {
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content"`
	IsError bool `json:"isError"`
}

func (c *Client) initialize() error {
	req := map[string]any{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "initialize",
		"params": map[string]any{
			"protocolVersion": "2024-11-05",
			"capabilities":    map[string]any{},
			"clientInfo": map[string]any{
				"name":    "picogk",
				"version": "1.0.0",
			},
		},
	}
	_, err := c.call(req)
	if err != nil {
		return err
	}
	// Send initialized notification
	notif := map[string]any{
		"jsonrpc": "2.0",
		"method":  "notifications/initialized",
	}
	return c.send(notif)
}

func (c *Client) nextID() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.msgID++
	return c.msgID
}

func (c *Client) send(msg any) error {
	data, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshaling: %w", err)
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	_, err = c.stdin.Write(append(data, '\\n'))
	return err
}

func (c *Client) callNoParse(req any) (string, error) {
	if err := c.send(req); err != nil {
		return "", err
	}
	// Read response line
	line, err := c.stdout.ReadString('\\n')
	if err != nil {
		return "", fmt.Errorf("reading response: %w", err)
	}
	return line, nil
}

func (c *Client) call(req any) (json.RawMessage, error) {
	line, err := c.callNoParse(req)
	if err != nil {
		return nil, err
	}
	var resp jsonRPCResponse
	if err := json.Unmarshal([]byte(line), &resp); err != nil {
		return nil, fmt.Errorf("parsing response: %w (line: %q)", err, line)
	}
	if resp.Error != nil {
		return nil, fmt.Errorf("server error [%d]: %s", resp.Error.Code, resp.Error.Message)
	}
	return resp.Result, nil
}

func (c *Client) newReq(toolName string, args map[string]any) map[string]any {
	return map[string]any{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "tools/call",
		"params": map[string]any{
			"name":      toolName,
			"arguments": args,
		},
	}
}

// callToolNoParse invokes an MCP tool by name and returns the raw text content of the response.
func (c *Client) callToolNoParse(toolName string, args map[string]any) (string, error) {
	req := c.newReq(toolName, args)
	result, err := c.callNoParse(req)
	if err != nil {
		return "", err
	}
	return string(result), nil
}

// callTool invokes an MCP tool by name and returns the parsed text content of the response.
func (c *Client) callTool(toolName string, args map[string]any) (string, error) {
	req := c.newReq(toolName, args)
	result, err := c.call(req)
	if err != nil {
		return "", err
	}
	var tr toolResult
	if err := json.Unmarshal([]byte(result), &tr); err != nil {
		return "", fmt.Errorf("parsing tool result: %w", err)
	}
	var text string
	for _, item := range tr.Content {
		if item.Type == "text" {
			text += item.Text
		}
	}
	if tr.IsError {
		return text, fmt.Errorf("tool error: %s", text)
	}
	return text, nil
}

// Must calls Do and must have no error or it will abort the program.
func (c *Client) Must(cmd any) (label, result string) {
	var err error
	label, result, err = c.Do(cmd)
	if err != nil {
		log.Fatalf("FAIL: %v -> %v", label, err)
	}
	return label, result
}

// Do executes an MCP tool call, returning a string result and an error.
func (c *Client) Do(cmd any) (label, result string, err error) {
	switch req := cmd.(type) {""")
    # Now build up the switch case statements
    for tool in tools:
        go_name = go_tool_name(tool.name)
        lines.append(f"\tcase {go_name}:")
        lines.append(f"\tlabel = \"{go_name}\"")
        lines.append(f"\tresult, err = c.{go_name}Fn(req)")
    lines.append("""
	default:
		return "", "", fmt.Errorf("unknown cmd type %T", cmd)
	}
	return label, result, err
}
""")
    return "\n".join(lines)


def gen_tools_go(tools: list[ToolDef]) -> str:
    """Generate the tools.go file with one builder struct + method per tool."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("")
    lines.append("package picogk")
    lines.append("")
    lines.append("")

    # Group tools by category
    categories: dict[str, list[ToolDef]] = {}
    for t in tools:
        categories.setdefault(t.category, []).append(t)

    for category, cat_tools in categories.items():
        lines.append(f"// --- {category} ---")
        lines.append("")

        for tool in cat_tools:
            # Generate request struct
            go_name = go_tool_name(tool.name)
            lines.append(f"// {go_name} holds parameters for the {tool.snake_name} tool.")
            lines.append(f"// {tool.description}")
            lines.append(f"type {go_name} struct {{")
            for p in tool.params:
                go_t = go_type(p.cs_type)
                field = go_field_name(p.name)
                json_tag = p.name
                if p.has_default:
                    # Use pointer for optional params so we can distinguish "not set"
                    if p.cs_type == "float":
                        go_t = "*float64"
                    elif p.cs_type == "int":
                        go_t = "*int"
                    elif p.cs_type == "bool":
                        go_t = "*bool"
                    elif p.cs_type in ("string", "string?"):
                        # go_t = "*string"
                        go_t = "string"
                    elif p.cs_type == "string[]":
                        go_t = "[]string"  # nil means not set
                    # json omitempty for optionals
                    lines.append(f"\t{field} {go_t} `json:\"{json_tag},omitempty\"`")
                else:
                    lines.append(f"\t{field} {go_t} `json:\"{json_tag}\"`")
            lines.append("}")
            lines.append("")

            # Generate method on Client
            lines.append(f"// {go_name}Fn calls the {tool.snake_name} MCP tool.")
            lines.append(f"// {tool.description}")
            if tool.required_params:
                req_params_str = ", ".join(
                    p.name for p in tool.required_params
                )
            lines.append(f"func (c *Client) {go_name}Fn(req {go_name}) (string, error) {{")

            # Build args map
            lines.append("\targs := map[string]any{}")
            for p in tool.params:
                field = go_field_name(p.name)
                if p.has_default:
                    if p.cs_type == "string[]":
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f"\t\targs[\"{p.name}\"] = req.{field}")
                        lines.append(f"\t}}")
                    elif p.cs_type == "string" or p.cs_type == "string?":
                        lines.append(f"\tif req.{field} != \"\" {{")
                        lines.append(f"\t\targs[\"{p.name}\"] = req.{field}")
                        lines.append(f"\t}}")
                    else:
                        lines.append(f"\tif req.{field} != nil {{")
                        lines.append(f"\t\targs[\"{p.name}\"] = *req.{field}")
                        lines.append(f"\t}}")
                else:
                    if p.cs_type == "string[]":
                        lines.append(f"\targs[\"{p.name}\"] = req.{field}")
                    else:
                        lines.append(f"\targs[\"{p.name}\"] = req.{field}")

            if tool.snake_name == "picogk_shutdown":
                lines.append(f"\treturn c.callToolNoParse(\"{tool.snake_name}\", args)")
            else:
                lines.append(f"\treturn c.callTool(\"{tool.snake_name}\", args)")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def gen_go_mod(version: str = "1.0.0") -> str:
    """Generate go.mod."""
    return f"""module github.com/gmlewis/PicoGK/sdk/go/picogk

go 1.22

// picogk: PicoGK MCP SDK for Go
// Version: {version}
"""


def gen_readme_md(tools: list[ToolDef]) -> str:
    """Generate the SDK README.md."""
    tool_count = len(tools)
    category_list: dict[str, list[str]] = {}
    for t in tools:
        category_list.setdefault(t.category, []).append(t.snake_name)

    cat_table = "\n".join(
        f"| **{cat}** | {', '.join(names)} |"
        for cat, names in sorted(category_list.items())
    )

    return f"""# picogk — Go SDK for the PicoGK MCP Server

`picogk` is an auto-generated Go SDK for the [PicoGK](https://picogk.org) geometry
kernel's MCP (Model Context Protocol) server. It provides a fully typed, idiomatic Go
interface to all {tool_count} PicoGK tools — from creating primitives to boolean operations,
lattice design, mesh manipulation, rendering, and 3D-printing export.

## Quick Start

```bash
go get github.com/gmlewis/PicoGK/sdk/go/picogk
```

```go
package main

import (
    "context"
    "fmt"
    "log"

    "github.com/gmlewis/PicoGK/sdk/go/picogk"
)

func main() {{
    ctx := context.Background()

    // Launch the PicoGK MCP server (default path: $HOME/.local/bin/picogk-mcp/PicoGK.Mcp)
    client, err := picogk.NewClient(ctx, "")
    if err != nil {{
        log.Fatal(err)
    }}
    defer client.Close()

    // Initialize the geometry kernel (0.5mm voxels)
    _, err = client.PicoGKInit(picogk.PicoGKInitRequest{{
        VoxelSizeMM: float64Ptr(0.5),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Create a sphere
    res, err := client.CreateSphere(picogk.CreateSphereRequest{{
        X:      0,
        Y:      0,
        Z:      0,
        Radius: 30,
        Id:     stringPtr("body"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}
    fmt.Println(res)

    // Create a box cutout
    _, err = client.CreateBox(picogk.CreateBoxRequest{{
        MinX: -10, MinY: -10, MinZ: -40,
        MaxX:  10, MaxY:  10, MaxZ: 40,
        Id:   stringPtr("cutout"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Subtract box from sphere
    _, err = client.BooleanSubtract(picogk.BooleanSubtractRequest{{
        A:  "body",
        B:  "cutout",
        Id: stringPtr("result"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Smooth the result
    _, err = client.Smooth(picogk.SmoothRequest{{
        ObjectId: "result",
        Distance: 2.0,
        Id:       stringPtr("smoothed"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Convert to mesh and export STL
    _, err = client.VoxelsToMesh(picogk.VoxelsToMeshRequest{{
        VoxelsId: "smoothed",
        Id:       stringPtr("mesh"),
    }})
    if err != nil {{
        log.Fatal(err)
    }}
    _, err = client.SaveStl(picogk.SaveStlRequest{{
        MeshId: "mesh",
        Path:   "/tmp/part.stl",
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    // Render a preview
    _, err = client.RenderToImage(picogk.RenderToImageRequest{{
        ObjectId: "smoothed",
        Path:     "/tmp/preview.png",
    }})
    if err != nil {{
        log.Fatal(err)
    }}

    fmt.Println("Done! Part exported to /tmp/part.stl")
}}

// Helper: create a float64 pointer
func float64Ptr(v float64) *float64 {{ return &v }}

// Helper: create a string pointer
func stringPtr(v string) *string {{ return &v }}
```

## API Overview

The SDK exposes all {tool_count} PicoGK MCP tools via builder-pattern request structs:

| Category | Tools |
|----------|-------|
{cat_table}

Each tool has:
- A `XxxRequest` struct with typed fields (optional params are pointers)
- A `client.Xxx(req)` method returning `(string, error)`
- Full doc comments

## Architecture

The SDK launches the PicoGK MCP server as a subprocess and communicates via
JSON-RPC over stdio. No network connection is needed. The server binary must
be installed separately (see the main PicoGK README for build instructions).

## Auto-Generation

This SDK is auto-generated from the PicoGK C# MCP tool definitions by
`scripts/generate-go-picogk-sdk.py`. To regenerate:

```bash
./scripts/generate-go-picogk-sdk.py --verbose
```

**DO NOT EDIT** the generated files — changes will be overwritten. Edit the
C# tool definitions in `PicoGK.Mcp/Tools/*.cs` instead, then regenerate.
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate the Go (picogk) MCP SDK from PicoGK C# tool definitions."
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parent.parent / "sdk" / "go",
        help="Output directory (default: sdk/go/)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    tools = parse_mcp_tools()
    print(f"Parsed {len(tools)} tools from PicoGK.Mcp/Tools/*.cs")

    # Create output directories
    pkg_dir = args.output / "picogk"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    client_go = gen_client_go(tools)
    tools_go = gen_tools_go(tools)
    go_mod = gen_go_mod()
    readme_md = gen_readme_md(tools)

    (pkg_dir / "client.go").write_text(client_go)
    (pkg_dir / "tools.go").write_text(tools_go)
    (pkg_dir / "go.mod").write_text(go_mod)
    (pkg_dir / "README.md").write_text(readme_md)

    # Run go fmt on generated source files
    import subprocess
    try:
        subprocess.run(["go", "fmt", str(pkg_dir / "client.go"), str(pkg_dir / "tools.go")],
                       check=True, capture_output=True, timeout=30)
    except Exception as e:
        print(f"  Warning: go fmt failed: {e}")

    # Re-read formatted files for accurate line count
    client_lines = len((pkg_dir / "client.go").read_text().splitlines())
    tools_lines = len((pkg_dir / "tools.go").read_text().splitlines())
    readme_lines = len((pkg_dir / "README.md").read_text().splitlines())

    print(f"Generated Go SDK in {pkg_dir}:")
    print(f"  client.go   ({client_lines:>5} lines)")
    print(f"  tools.go    ({tools_lines:>5} lines)")
    print(f"  go.mod")
    print(f"  README.md   ({readme_lines:>5} lines)")
    print(f"\n  Total: {len(tools)} tools across {len(set(t.category for t in tools))} categories")


if __name__ == "__main__":
    main()