// Code generated by scripts/generate-go-blender-sdk.py — DO NOT EDIT.

package blender

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

// Client manages a connection to the Blender MCP server.
// It launches the server as a subprocess and communicates via JSON-RPC over stdio.
//
// Usage:
//
//	// Uses default server (blender-mcp)
//	client, err := blender.NewClient(ctx, "")
//	defer client.Close()
//	// Or specify a custom path:
//	client, err := blender.NewClient(ctx, "/path/to/blender-mcp")
//	// Execute Python code in Blender
//	res, err := client.ExecuteBlenderCode(blender.ExecuteBlenderCodeRequest{
//		Code: "import bpy; result = {'objects': [o.name for o in bpy.data.objects]}",
//	})
type Client struct {
	ctx       context.Context
	cmd       *exec.Cmd
	stdin     io.WriteCloser
	stdout    *bufio.Reader
	mu        sync.Mutex
	msgID     int
	serverBin string
}

// DefaultServerBin is the default command to launch the Blender MCP server.
// It can be overridden by passing a non-empty path to NewClient.
const DefaultServerBin = "uv"

// DefaultServerArgs are the default arguments for the Blender MCP server.
var DefaultServerArgs = []string{"--directory", expandPath("~/Projects/Blender/blender_mcp/mcp/blmcp"), "run", "blender-mcp"}

// NewClient launches the Blender MCP server and returns a Client.
// If serverBin is empty, uses the default (uv run blender-mcp).
// If serverBin is a directory, uses uv --directory <dir> run blender-mcp.
func NewClient(ctx context.Context, serverBin string) (*Client, error) {
	if serverBin == "" {
		return newClientWithArgs(ctx, DefaultServerBin, DefaultServerArgs, "")
	}
	serverBin = expandPath(serverBin)
	// If it's a directory, use uv --directory <dir> run blender-mcp
	if info, err := os.Stat(serverBin); err == nil && info.IsDir() {
		return newClientWithArgs(ctx, "uv", []string{"--directory", serverBin, "run", "blender-mcp"}, "")
	}
	// Otherwise treat as a direct binary/command
	return newClientWithArgs(ctx, serverBin, nil, "")
}

func newClientWithArgs(ctx context.Context, bin string, args []string, workDir string) (*Client, error) {
	cmd := exec.CommandContext(ctx, bin, args...)
	if workDir != "" {
		cmd.Dir = workDir
	}
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdin pipe: %w", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdout pipe: %w", err)
	}
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("starting server: %w", err)
	}
	c := &Client{
		ctx:       ctx,
		cmd:       cmd,
		stdin:     stdin,
		stdout:    bufio.NewReader(stdout),
		serverBin: bin,
	}
	// Perform MCP initialize handshake
	if err := c.initialize(); err != nil {
		cmd.Process.Kill()
		return nil, fmt.Errorf("initialize handshake: %w", err)
	}
	return c, nil
}

// Close shuts down the MCP server process.
func (c *Client) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.stdin != nil {
		c.stdin.Close()
	}
	if c.cmd != nil && c.cmd.Process != nil {
		done := make(chan struct{})
		go func() {
			c.cmd.Wait()
			close(done)
		}()
		select {
		case <-done:
		case <-c.ctx.Done():
			c.cmd.Process.Kill()
			<-done
		}
	}
	return nil
}

// expandPath expands a leading ~ to the user's home directory.
func expandPath(path string) string {
	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err == nil {
			path = filepath.Join(home, path[1:])
		}
	}
	return path
}

// --- JSON-RPC internals ---

type jsonRPCRequest struct {
	JSONRPC string `json:"jsonrpc"`
	ID      int    `json:"id"`
	Method  string `json:"method"`
	Params  any    `json:"params"`
}

type jsonRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      int             `json:"id"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *jsonRPCErr     `json:"error,omitempty"`
}

type jsonRPCErr struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type toolResult struct {
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content"`
	IsError bool `json:"isError"`
}

func (c *Client) initialize() error {
	req := map[string]any{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "initialize",
		"params": map[string]any{
			"protocolVersion": "2024-11-05",
			"capabilities":    map[string]any{},
			"clientInfo": map[string]any{
				"name":    "blender-go-sdk",
				"version": "1.0.0",
			},
		},
	}
	_, err := c.call(req)
	if err != nil {
		return err
	}
	// Send initialized notification
	notif := map[string]any{
		"jsonrpc": "2.0",
		"method":  "notifications/initialized",
	}
	return c.send(notif)
}

func (c *Client) nextID() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.msgID++
	return c.msgID
}

func (c *Client) send(msg any) error {
	data, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshaling: %w", err)
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	_, err = c.stdin.Write(append(data, '\n'))
	return err
}

func (c *Client) callNoParse(req any) (string, error) {
	if err := c.send(req); err != nil {
		return "", err
	}
	// Read response line
	line, err := c.stdout.ReadString('\n')
	if err != nil {
		return "", fmt.Errorf("reading response: %w", err)
	}
	return line, nil
}

func (c *Client) call(req any) (json.RawMessage, error) {
	line, err := c.callNoParse(req)
	if err != nil {
		return nil, err
	}
	var resp jsonRPCResponse
	if err := json.Unmarshal([]byte(line), &resp); err != nil {
		return nil, fmt.Errorf("parsing response: %w (line: %q)", err, line)
	}
	if resp.Error != nil {
		return nil, fmt.Errorf("server error [%d]: %s", resp.Error.Code, resp.Error.Message)
	}
	return resp.Result, nil
}

func (c *Client) newReq(toolName string, args map[string]any) map[string]any {
	return map[string]any{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "tools/call",
		"params": map[string]any{
			"name":      toolName,
			"arguments": args,
		},
	}
}

// callToolNoParse invokes an MCP tool by name and returns the raw response.
func (c *Client) callToolNoParse(toolName string, args map[string]any) (string, error) {
	req := c.newReq(toolName, args)
	result, err := c.callNoParse(req)
	if err != nil {
		return "", err
	}
	return string(result), nil
}

// callTool invokes an MCP tool by name and returns the parsed text content.
func (c *Client) callTool(toolName string, args map[string]any) (string, error) {
	req := c.newReq(toolName, args)
	result, err := c.call(req)
	if err != nil {
		return "", err
	}
	var tr toolResult
	if err := json.Unmarshal([]byte(result), &tr); err != nil {
		return "", fmt.Errorf("parsing tool result: %w", err)
	}
	var text string
	for _, item := range tr.Content {
		if item.Type == "text" {
			text += item.Text
		}
	}
	if tr.IsError {
		return text, fmt.Errorf("tool error: %s", text)
	}
	return text, nil
}

// Must calls Do and must have no error or it will abort the program.
func (c *Client) Must(cmd any) (label, result string) {
	var err error
	label, result, err = c.Do(cmd)
	if err != nil {
		log.Fatalf("FAIL: %v -> %v", label, err)
	}
	return label, result
}

// Do executes an MCP tool call, returning a string result and an error.
func (c *Client) Do(cmd any) (label, result string, err error) {
	switch req := cmd.(type) {
	case ExecuteBlenderCodeRequest:
		label = "ExecuteBlenderCode"
		result, err = c.ExecuteBlenderCode(req)
	case ExecuteBlenderCodeForCLIRequest:
		label = "ExecuteBlenderCodeForCLI"
		result, err = c.ExecuteBlenderCodeForCLI(req)
	case GetBlendFileSummaryDatablocksRequest:
		label = "GetBlendFileSummaryDatablocks"
		result, err = c.GetBlendFileSummaryDatablocks(req)
	case GetBlendFileSummaryDatablocksForCLIRequest:
		label = "GetBlendFileSummaryDatablocksForCLI"
		result, err = c.GetBlendFileSummaryDatablocksForCLI(req)
	case GetBlendFileSummaryMissingFilesRequest:
		label = "GetBlendFileSummaryMissingFiles"
		result, err = c.GetBlendFileSummaryMissingFiles(req)
	case GetBlendFileSummaryMissingFilesForCLIRequest:
		label = "GetBlendFileSummaryMissingFilesForCLI"
		result, err = c.GetBlendFileSummaryMissingFilesForCLI(req)
	case GetBlendFileSummaryOfLinkedLibrariesRequest:
		label = "GetBlendFileSummaryOfLinkedLibraries"
		result, err = c.GetBlendFileSummaryOfLinkedLibraries(req)
	case GetBlendFileSummaryOfLinkedLibrariesForCLIRequest:
		label = "GetBlendFileSummaryOfLinkedLibrariesForCLI"
		result, err = c.GetBlendFileSummaryOfLinkedLibrariesForCLI(req)
	case GetBlendFileSummaryPathInfoRequest:
		label = "GetBlendFileSummaryPathInfo"
		result, err = c.GetBlendFileSummaryPathInfo(req)
	case GetBlendFileSummaryPathInfoForCLIRequest:
		label = "GetBlendFileSummaryPathInfoForCLI"
		result, err = c.GetBlendFileSummaryPathInfoForCLI(req)
	case GetBlendFileSummaryUsageGuessRequest:
		label = "GetBlendFileSummaryUsageGuess"
		result, err = c.GetBlendFileSummaryUsageGuess(req)
	case GetBlendFileSummaryUsageGuessForCLIRequest:
		label = "GetBlendFileSummaryUsageGuessForCLI"
		result, err = c.GetBlendFileSummaryUsageGuessForCLI(req)
	case GetObjectDetailSummaryRequest:
		label = "GetObjectDetailSummary"
		result, err = c.GetObjectDetailSummary(req)
	case GetObjectsSummaryRequest:
		label = "GetObjectsSummary"
		result, err = c.GetObjectsSummary(req)
	case GetPythonAPIDocsRequest:
		label = "GetPythonAPIDocs"
		result, err = c.GetPythonAPIDocs(req)
	case GetScreenshotOfAreaAsImageRequest:
		label = "GetScreenshotOfAreaAsImage"
		result, err = c.GetScreenshotOfAreaAsImage(req)
	case GetScreenshotOfWindowAsImageRequest:
		label = "GetScreenshotOfWindowAsImage"
		result, err = c.GetScreenshotOfWindowAsImage(req)
	case GetScreenshotOfWindowAsJSONRequest:
		label = "GetScreenshotOfWindowAsJSON"
		result, err = c.GetScreenshotOfWindowAsJSON(req)
	case JumpToTabByNameRequest:
		label = "JumpToTabByName"
		result, err = c.JumpToTabByName(req)
	case JumpToTabBySpaceTypeRequest:
		label = "JumpToTabBySpaceType"
		result, err = c.JumpToTabBySpaceType(req)
	case JumpToView3dObjectByNameRequest:
		label = "JumpToView3dObjectByName"
		result, err = c.JumpToView3dObjectByName(req)
	case JumpToView3dObjectDataByNameRequest:
		label = "JumpToView3dObjectDataByName"
		result, err = c.JumpToView3dObjectDataByName(req)
	case RenderThumbnailToPathRequest:
		label = "RenderThumbnailToPath"
		result, err = c.RenderThumbnailToPath(req)
	case RenderViewportToPathRequest:
		label = "RenderViewportToPath"
		result, err = c.RenderViewportToPath(req)
	case SearchAPIDocsRequest:
		label = "SearchAPIDocs"
		result, err = c.SearchAPIDocs(req)
	case SearchManualDocsRequest:
		label = "SearchManualDocs"
		result, err = c.SearchManualDocs(req)

	default:
		return "", "", fmt.Errorf("unknown cmd type %T", cmd)
	}
	return label, result, err
}
