// Code generated by scripts/generate-go-mcp-sdk.py — DO NOT EDIT.

package picogk

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

// Client manages a connection to the PicoGK MCP server.
// It launches the server as a subprocess and communicates via JSON-RPC over stdio.
//
// Usage:
//
//	// Uses default server at $HOME/.local/bin/picogk-mcp/PicoGK.Mcp
//	client, err := picogk.NewClient(ctx, "")
//	defer client.Close()
//	// Or specify a custom path:
//	client, err := picogk.NewClient(ctx, "/custom/path/to/PicoGK.Mcp")
//	// Initialize the geometry kernel
//	res, err := client.PicoGKInit(picogk.PicoGKInitRequest{VoxelSizeMM: 0.5})
//	// Create a sphere, subtract a box, export STL...
type Client struct {
	ctx       context.Context
	cmd       *exec.Cmd
	stdin     io.WriteCloser
	stdout    *bufio.Reader
	mu        sync.Mutex
	msgID     int
	serverBin string
}

// DefaultServerBin is the default path to the PicoGK MCP server binary.
// It can be overridden by passing a non-empty path to NewClient.
const DefaultServerBin = "~/.local/bin/picogk-mcp/PicoGK.Mcp"

// NewClient launches the PicoGK MCP server binary and returns a Client.
// If serverBin is empty, uses DefaultServerBin ($HOME/.local/bin/picogk-mcp/PicoGK.Mcp).
// Expand ~ to the user's home directory automatically.
func NewClient(ctx context.Context, serverBin string) (*Client, error) {
	if serverBin == "" {
		serverBin = DefaultServerBin
	}
	serverBin = expandPath(serverBin)
	cmd := exec.CommandContext(ctx, serverBin)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdin pipe: %w", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdout pipe: %w", err)
	}
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("starting server: %w", err)
	}
	c := &Client{
		cmd:       cmd,
		stdin:     stdin,
		stdout:    bufio.NewReader(stdout),
		serverBin: serverBin,
	}
	// Perform MCP initialize handshake
	if err := c.initialize(); err != nil {
		cmd.Process.Kill()
		return nil, fmt.Errorf("initialize handshake: %w", err)
	}
	return c, nil
}

// Close shuts down the MCP server process.
func (c *Client) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.stdin != nil {
		c.stdin.Close()
	}
	if c.cmd != nil && c.cmd.Process != nil {
		done := make(chan struct{})
		go func() {
			c.cmd.Wait()
			close(done)
		}()
		select {
		case <-done:
		case <-c.ctx.Done():
			c.cmd.Process.Kill()
			<-done
		}
	}
	return nil
}

// expandPath expands a leading ~ to the user's home directory.
func expandPath(path string) string {
	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err == nil {
			path = filepath.Join(home, path[1:])
		}
	}
	return path
}

// --- JSON-RPC internals ---

type jsonRPCRequest struct {
	JSONRPC string `json:"jsonrpc"`
	ID      int    `json:"id"`
	Method  string `json:"method"`
	Params  any    `json:"params"`
}

type jsonRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      int             `json:"id"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *jsonRPCErr     `json:"error,omitempty"`
}

type jsonRPCErr struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type toolResult struct {
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content"`
	IsError bool `json:"isError"`
}

func (c *Client) initialize() error {
	req := map[string]any{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "initialize",
		"params": map[string]any{
			"protocolVersion": "2024-11-05",
			"capabilities":    map[string]any{},
			"clientInfo": map[string]any{
				"name":    "picogk",
				"version": "1.0.0",
			},
		},
	}
	_, err := c.call(req)
	if err != nil {
		return err
	}
	// Send initialized notification
	notif := map[string]any{
		"jsonrpc": "2.0",
		"method":  "notifications/initialized",
	}
	return c.send(notif)
}

func (c *Client) nextID() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.msgID++
	return c.msgID
}

func (c *Client) send(msg any) error {
	data, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshaling: %w", err)
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	_, err = c.stdin.Write(append(data, '\n'))
	return err
}

func (c *Client) callNoParse(req any) (string, error) {
	if err := c.send(req); err != nil {
		return "", err
	}
	// Read response line
	line, err := c.stdout.ReadString('\n')
	if err != nil {
		return "", fmt.Errorf("reading response: %w", err)
	}
	return line, nil
}

func (c *Client) call(req any) (json.RawMessage, error) {
	line, err := c.callNoParse(req)
	if err != nil {
		return nil, err
	}
	var resp jsonRPCResponse
	if err := json.Unmarshal([]byte(line), &resp); err != nil {
		return nil, fmt.Errorf("parsing response: %w (line: %q)", err, line)
	}
	if resp.Error != nil {
		return nil, fmt.Errorf("server error [%d]: %s", resp.Error.Code, resp.Error.Message)
	}
	return resp.Result, nil
}

func (c *Client) newReq(toolName string, args map[string]any) map[string]any {
	return map[string]any{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "tools/call",
		"params": map[string]any{
			"name":      toolName,
			"arguments": args,
		},
	}
}

// callToolNoParse invokes an MCP tool by name and returns the raw text content of the response.
func (c *Client) callToolNoParse(toolName string, args map[string]any) (string, error) {
	req := c.newReq(toolName, args)
	result, err := c.callNoParse(req)
	if err != nil {
		return "", err
	}
	return string(result), nil
}

// callTool invokes an MCP tool by name and returns the parsed text content of the response.
func (c *Client) callTool(toolName string, args map[string]any) (string, error) {
	req := c.newReq(toolName, args)
	result, err := c.call(req)
	if err != nil {
		return "", err
	}
	var tr toolResult
	if err := json.Unmarshal([]byte(result), &tr); err != nil {
		return "", fmt.Errorf("parsing tool result: %w", err)
	}
	var text string
	for _, item := range tr.Content {
		if item.Type == "text" {
			text += item.Text
		}
	}
	if tr.IsError {
		return text, fmt.Errorf("tool error: %s", text)
	}
	return text, nil
}

// Must calls Do and must have no error or it will abort the program.
func (c *Client) Must(cmd any) (label, result string) {
	var err error
	label, result, err = c.Do(cmd)
	if err != nil {
		log.Fatalf("FAIL: %v -> %v", label, err)
	}
	return label, result
}

// Do executes an MCP tool call, returning a string result and an error.
func (c *Client) Do(cmd any) (label, result string, err error) {
	switch req := cmd.(type) {
	case BooleanAdd:
		label = "boolean_add"
		result, err = c.BooleanAddFn(req)
	case BooleanSubtract:
		label = "boolean_subtract"
		result, err = c.BooleanSubtractFn(req)
	case BooleanIntersect:
		label = "boolean_intersect"
		result, err = c.BooleanIntersectFn(req)
	case BooleanAddAll:
		label = "BooleanAddAll"
		result, err = c.BooleanAddAllFn(req)
	case BooleanSubtractAll:
		label = "BooleanSubtractAll"
		result, err = c.BooleanSubtractAllFn(req)
	case SaveSTL:
		label = "SaveSTL"
		result, err = c.SaveSTLFn(req)
	case SaveVDB:
		label = "SaveVDB"
		result, err = c.SaveVDBFn(req)
	case LoadVDB:
		label = "LoadVDB"
		result, err = c.LoadVDBFn(req)
	case ListVDBFields:
		label = "ListVDBFields"
		result, err = c.ListVDBFieldsFn(req)
	case SaveSVG:
		label = "SaveSVG"
		result, err = c.SaveSVGFn(req)
	case SaveCLI:
		label = "SaveCLI"
		result, err = c.SaveCLIFn(req)
	case CreateLattice:
		label = "CreateLattice"
		result, err = c.CreateLatticeFn(req)
	case LatticeAddBeam:
		label = "LatticeAddBeam"
		result, err = c.LatticeAddBeamFn(req)
	case LatticeAddSphere:
		label = "LatticeAddSphere"
		result, err = c.LatticeAddSphereFn(req)
	case LatticeToVoxels:
		label = "LatticeToVoxels"
		result, err = c.LatticeToVoxelsFn(req)
	case CreateMesh:
		label = "CreateMesh"
		result, err = c.CreateMeshFn(req)
	case MeshAddVertex:
		label = "MeshAddVertex"
		result, err = c.MeshAddVertexFn(req)
	case MeshAddTriangle:
		label = "MeshAddTriangle"
		result, err = c.MeshAddTriangleFn(req)
	case MeshAddTriangleVertices:
		label = "MeshAddTriangleVertices"
		result, err = c.MeshAddTriangleVerticesFn(req)
	case MeshAddQuad:
		label = "MeshAddQuad"
		result, err = c.MeshAddQuadFn(req)
	case VoxelsToMesh:
		label = "VoxelsToMesh"
		result, err = c.VoxelsToMeshFn(req)
	case MeshToVoxels:
		label = "MeshToVoxels"
		result, err = c.MeshToVoxelsFn(req)
	case MeshFromSTL:
		label = "MeshFromSTL"
		result, err = c.MeshFromSTLFn(req)
	case MeshTransform:
		label = "MeshTransform"
		result, err = c.MeshTransformFn(req)
	case MeshMirror:
		label = "MeshMirror"
		result, err = c.MeshMirrorFn(req)
	case MeshAppend:
		label = "MeshAppend"
		result, err = c.MeshAppendFn(req)
	case CreateSphere:
		label = "CreateSphere"
		result, err = c.CreateSphereFn(req)
	case CreateBox:
		label = "CreateBox"
		result, err = c.CreateBoxFn(req)
	case CreateCylinder:
		label = "CreateCylinder"
		result, err = c.CreateCylinderFn(req)
	case CreateCapsule:
		label = "CreateCapsule"
		result, err = c.CreateCapsuleFn(req)
	case CreateTorus:
		label = "CreateTorus"
		result, err = c.CreateTorusFn(req)
	case GetBoundingBox:
		label = "GetBoundingBox"
		result, err = c.GetBoundingBoxFn(req)
	case GetVolume:
		label = "GetVolume"
		result, err = c.GetVolumeFn(req)
	case GetMeshInfo:
		label = "GetMeshInfo"
		result, err = c.GetMeshInfoFn(req)
	case PointInside:
		label = "PointInside"
		result, err = c.PointInsideFn(req)
	case SurfaceNormal:
		label = "SurfaceNormal"
		result, err = c.SurfaceNormalFn(req)
	case ClosestPoint:
		label = "ClosestPoint"
		result, err = c.ClosestPointFn(req)
	case ListObjects:
		label = "ListObjects"
		result, err = c.ListObjectsFn(req)
	case DeleteObject:
		label = "DeleteObject"
		result, err = c.DeleteObjectFn(req)
	case GetVoxelDimensions:
		label = "GetVoxelDimensions"
		result, err = c.GetVoxelDimensionsFn(req)
	case VoxelsIsEmpty:
		label = "VoxelsIsEmpty"
		result, err = c.VoxelsIsEmptyFn(req)
	case VoxelsMemUsage:
		label = "VoxelsMemUsage"
		result, err = c.VoxelsMemUsageFn(req)
	case VoxelsIsEqual:
		label = "VoxelsIsEqual"
		result, err = c.VoxelsIsEqualFn(req)
	case RayCast:
		label = "RayCast"
		result, err = c.RayCastFn(req)
	case MeasureThickness:
		label = "MeasureThickness"
		result, err = c.MeasureThicknessFn(req)
	case DuplicateObject:
		label = "DuplicateObject"
		result, err = c.DuplicateObjectFn(req)
	case DeleteObjects:
		label = "DeleteObjects"
		result, err = c.DeleteObjectsFn(req)
	case RenderToImage:
		label = "RenderToImage"
		result, err = c.RenderToImageFn(req)
	case RenderSlice:
		label = "RenderSlice"
		result, err = c.RenderSliceFn(req)
	case Init:
		label = "Init"
		result, err = c.InitFn(req)
	case Info:
		label = "Info"
		result, err = c.InfoFn(req)
	case Shutdown:
		label = "Shutdown"
		result, err = c.ShutdownFn(req)
	case Offset:
		label = "Offset"
		result, err = c.OffsetFn(req)
	case DoubleOffset:
		label = "DoubleOffset"
		result, err = c.DoubleOffsetFn(req)
	case OverOffset:
		label = "OverOffset"
		result, err = c.OverOffsetFn(req)
	case Smooth:
		label = "Smooth"
		result, err = c.SmoothFn(req)
	case Trim:
		label = "Trim"
		result, err = c.TrimFn(req)
	case Shell:
		label = "Shell"
		result, err = c.ShellFn(req)
	case Fillet:
		label = "Fillet"
		result, err = c.FilletFn(req)
	case ProjectZSlice:
		label = "ProjectZSlice"
		result, err = c.ProjectZSliceFn(req)
	case TransformVoxels:
		label = "TransformVoxels"
		result, err = c.TransformVoxelsFn(req)
	case CircularPattern:
		label = "CircularPattern"
		result, err = c.CircularPatternFn(req)

	default:
		return "", "", fmt.Errorf("unknown cmd type %T", cmd)
	}
	return label, result, err
}
