// Code generated by scripts/generate-go-mcp-sdk.py — DO NOT EDIT.

package picogk

// --- Booleans ---

// BooleanAdd holds parameters for the boolean_add tool.
// Boolean UNION: combine two voxel objects. Both volumes are kept, overlapping regions are merged. Returns a new object ID.
type BooleanAdd struct {
	A  string `json:"a"`
	B  string `json:"b"`
	ID string `json:"id,omitempty"`
}

// BooleanAddFn calls the boolean_add MCP tool.
// Boolean UNION: combine two voxel objects. Both volumes are kept, overlapping regions are merged. Returns a new object ID.
func (c *Client) BooleanAddFn(req BooleanAdd) (string, error) {
	args := map[string]any{}
	args["a"] = req.A
	args["b"] = req.B
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("boolean_add", args)
}

// BooleanSubtract holds parameters for the boolean_subtract tool.
// Boolean SUBTRACTION: subtract voxels of B from A. Removes the volume of B from A. Returns a new object ID.
type BooleanSubtract struct {
	A  string `json:"a"`
	B  string `json:"b"`
	ID string `json:"id,omitempty"`
}

// BooleanSubtractFn calls the boolean_subtract MCP tool.
// Boolean SUBTRACTION: subtract voxels of B from A. Removes the volume of B from A. Returns a new object ID.
func (c *Client) BooleanSubtractFn(req BooleanSubtract) (string, error) {
	args := map[string]any{}
	args["a"] = req.A
	args["b"] = req.B
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("boolean_subtract", args)
}

// BooleanIntersect holds parameters for the boolean_intersect tool.
// Boolean INTERSECTION: keep only the overlapping volume of two voxel objects. Returns a new object ID.
type BooleanIntersect struct {
	A  string `json:"a"`
	B  string `json:"b"`
	ID string `json:"id,omitempty"`
}

// BooleanIntersectFn calls the boolean_intersect MCP tool.
// Boolean INTERSECTION: keep only the overlapping volume of two voxel objects. Returns a new object ID.
func (c *Client) BooleanIntersectFn(req BooleanIntersect) (string, error) {
	args := map[string]any{}
	args["a"] = req.A
	args["b"] = req.B
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("boolean_intersect", args)
}

// BooleanAddAll holds parameters for the boolean_add_all tool.
// Combine multiple voxel objects into one. All volumes are merged. Returns a new object ID.
type BooleanAddAll struct {
	ObjectIDs []string `json:"objectIds"`
	ID        string   `json:"id,omitempty"`
}

// BooleanAddAllFn calls the boolean_add_all MCP tool.
// Combine multiple voxel objects into one. All volumes are merged. Returns a new object ID.
func (c *Client) BooleanAddAllFn(req BooleanAddAll) (string, error) {
	args := map[string]any{}
	args["objectIds"] = req.ObjectIDs
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("boolean_add_all", args)
}

// BooleanSubtractAll holds parameters for the boolean_subtract_all tool.
// Subtract multiple voxel objects from a single object in one call. Equivalent to calling boolean_subtract repeatedly, but more efficient for multi-hole drilling or multi-cutout operations. Returns a new object ID.
type BooleanSubtractAll struct {
	A           string   `json:"a"`
	SubtractIDs []string `json:"subtractIds"`
	ID          string   `json:"id,omitempty"`
}

// BooleanSubtractAllFn calls the boolean_subtract_all MCP tool.
// Subtract multiple voxel objects from a single object in one call. Equivalent to calling boolean_subtract repeatedly, but more efficient for multi-hole drilling or multi-cutout operations. Returns a new object ID.
func (c *Client) BooleanSubtractAllFn(req BooleanSubtractAll) (string, error) {
	args := map[string]any{}
	args["a"] = req.A
	args["subtractIds"] = req.SubtractIDs
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("boolean_subtract_all", args)
}

// --- IO ---

// SaveSTL holds parameters for the save_stl tool.
// Save a mesh to an STL file. The mesh is typically obtained from voxels_to_mesh. Units are millimeters by default.
type SaveSTL struct {
	MeshID string `json:"meshId"`
	Path   string `json:"path"`
	Units  string `json:"units,omitempty"`
}

// SaveSTLFn calls the save_stl MCP tool.
// Save a mesh to an STL file. The mesh is typically obtained from voxels_to_mesh. Units are millimeters by default.
func (c *Client) SaveSTLFn(req SaveSTL) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	args["path"] = req.Path
	if req.Units != "" {
		args["units"] = req.Units
	}
	return c.callTool("save_stl", args)
}

// SaveVDB holds parameters for the save_vdb tool.
// Save voxels to an OpenVDB file. VDB files preserve the full voxel field data.
type SaveVDB struct {
	VoxelsID  string `json:"voxelsId"`
	Path      string `json:"path"`
	FieldName string `json:"fieldName,omitempty"`
}

// SaveVDBFn calls the save_vdb MCP tool.
// Save voxels to an OpenVDB file. VDB files preserve the full voxel field data.
func (c *Client) SaveVDBFn(req SaveVDB) (string, error) {
	args := map[string]any{}
	args["voxelsId"] = req.VoxelsID
	args["path"] = req.Path
	if req.FieldName != "" {
		args["fieldName"] = req.FieldName
	}
	return c.callTool("save_vdb", args)
}

// LoadVDB holds parameters for the load_vdb tool.
// Load voxels from an OpenVDB file. Returns the object ID.
type LoadVDB struct {
	Path      string `json:"path"`
	FieldName string `json:"fieldName,omitempty"`
	ID        string `json:"id,omitempty"`
}

// LoadVDBFn calls the load_vdb MCP tool.
// Load voxels from an OpenVDB file. Returns the object ID.
func (c *Client) LoadVDBFn(req LoadVDB) (string, error) {
	args := map[string]any{}
	args["path"] = req.Path
	if req.FieldName != "" {
		args["fieldName"] = req.FieldName
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("load_vdb", args)
}

// ListVDBFields holds parameters for the list_vdb_fields tool.
// List all fields in a VDB file with their names, types, and indices. Useful for inspecting multi-field VDB files before loading a specific field with load_vdb. Returns field count and a table of index, name, type, and PicoGK compatibility.
type ListVDBFields struct {
	Path string `json:"path"`
}

// ListVDBFieldsFn calls the list_vdb_fields MCP tool.
// List all fields in a VDB file with their names, types, and indices. Useful for inspecting multi-field VDB files before loading a specific field with load_vdb. Returns field count and a table of index, name, type, and PicoGK compatibility.
func (c *Client) ListVDBFieldsFn(req ListVDBFields) (string, error) {
	args := map[string]any{}
	args["path"] = req.Path
	return c.callTool("list_vdb_fields", args)
}

// SaveSVG holds parameters for the save_svg tool.
// Vectorize voxels into 2D slice contours and save as SVG. Each slice is written to its own file: <path>.NNNN.svg (zero-padded 4 digits). Useful for 2D manufacturing or visualization. Returns the count of files written.
type SaveSVG struct {
	VoxelsID    string   `json:"voxelsId"`
	Path        string   `json:"path"`
	LayerHeight *float64 `json:"layerHeight,omitempty"`
}

// SaveSVGFn calls the save_svg MCP tool.
// Vectorize voxels into 2D slice contours and save as SVG. Each slice is written to its own file: <path>.NNNN.svg (zero-padded 4 digits). Useful for 2D manufacturing or visualization. Returns the count of files written.
func (c *Client) SaveSVGFn(req SaveSVG) (string, error) {
	args := map[string]any{}
	args["voxelsId"] = req.VoxelsID
	args["path"] = req.Path
	if req.LayerHeight != nil {
		args["layerHeight"] = *req.LayerHeight
	}
	return c.callTool("save_svg", args)
}

// SaveCLI holds parameters for the save_cli tool.
// Save voxels to a CLI (Common Layer Interface) file for 3D printing. Vectorizes the voxel field into 2D layers and writes the CLI format. Returns the file path and slice count.
type SaveCLI struct {
	VoxelsID       string   `json:"voxelsId"`
	Path           string   `json:"path"`
	LayerHeight    *float64 `json:"layerHeight,omitempty"`
	Format         string   `json:"format,omitempty"`
	UseAbsXYOrigin *bool    `json:"useAbsXYOrigin,omitempty"`
}

// SaveCLIFn calls the save_cli MCP tool.
// Save voxels to a CLI (Common Layer Interface) file for 3D printing. Vectorizes the voxel field into 2D layers and writes the CLI format. Returns the file path and slice count.
func (c *Client) SaveCLIFn(req SaveCLI) (string, error) {
	args := map[string]any{}
	args["voxelsId"] = req.VoxelsID
	args["path"] = req.Path
	if req.LayerHeight != nil {
		args["layerHeight"] = *req.LayerHeight
	}
	if req.Format != "" {
		args["format"] = req.Format
	}
	if req.UseAbsXYOrigin != nil {
		args["useAbsXYOrigin"] = *req.UseAbsXYOrigin
	}
	return c.callTool("save_cli", args)
}

// --- Lattice ---

// CreateLattice holds parameters for the create_lattice tool.
// Create an empty lattice structure. Add beams and sphere nodes to build it, then convert to voxels. Returns the object ID.
type CreateLattice struct {
	ID string `json:"id,omitempty"`
}

// CreateLatticeFn calls the create_lattice MCP tool.
// Create an empty lattice structure. Add beams and sphere nodes to build it, then convert to voxels. Returns the object ID.
func (c *Client) CreateLatticeFn(req CreateLattice) (string, error) {
	args := map[string]any{}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("create_lattice", args)
}

// LatticeAddBeam holds parameters for the lattice_add_beam tool.
// Add a tapered beam (strut) between two points in a lattice. Each end has its own radius. Returns a confirmation.
type LatticeAddBeam struct {
	LatticeID string  `json:"latticeId"`
	X1        float64 `json:"x1"`
	Y1        float64 `json:"y1"`
	Z1        float64 `json:"z1"`
	Radius1   float64 `json:"radius1"`
	X2        float64 `json:"x2"`
	Y2        float64 `json:"y2"`
	Z2        float64 `json:"z2"`
	Radius2   float64 `json:"radius2"`
	RoundCap  *bool   `json:"roundCap,omitempty"`
}

// LatticeAddBeamFn calls the lattice_add_beam MCP tool.
// Add a tapered beam (strut) between two points in a lattice. Each end has its own radius. Returns a confirmation.
func (c *Client) LatticeAddBeamFn(req LatticeAddBeam) (string, error) {
	args := map[string]any{}
	args["latticeId"] = req.LatticeID
	args["x1"] = req.X1
	args["y1"] = req.Y1
	args["z1"] = req.Z1
	args["radius1"] = req.Radius1
	args["x2"] = req.X2
	args["y2"] = req.Y2
	args["z2"] = req.Z2
	args["radius2"] = req.Radius2
	if req.RoundCap != nil {
		args["roundCap"] = *req.RoundCap
	}
	return c.callTool("lattice_add_beam", args)
}

// LatticeAddSphere holds parameters for the lattice_add_sphere tool.
// Add a sphere node at a point in a lattice. Returns a confirmation.
type LatticeAddSphere struct {
	LatticeID string  `json:"latticeId"`
	X         float64 `json:"x"`
	Y         float64 `json:"y"`
	Z         float64 `json:"z"`
	Radius    float64 `json:"radius"`
}

// LatticeAddSphereFn calls the lattice_add_sphere MCP tool.
// Add a sphere node at a point in a lattice. Returns a confirmation.
func (c *Client) LatticeAddSphereFn(req LatticeAddSphere) (string, error) {
	args := map[string]any{}
	args["latticeId"] = req.LatticeID
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	args["radius"] = req.Radius
	return c.callTool("lattice_add_sphere", args)
}

// LatticeToVoxels holds parameters for the lattice_to_voxels tool.
// Convert a lattice to voxels. Renders the lattice beams and nodes into a voxel field. Returns a new voxel object ID.
type LatticeToVoxels struct {
	LatticeID string `json:"latticeId"`
	ID        string `json:"id,omitempty"`
}

// LatticeToVoxelsFn calls the lattice_to_voxels MCP tool.
// Convert a lattice to voxels. Renders the lattice beams and nodes into a voxel field. Returns a new voxel object ID.
func (c *Client) LatticeToVoxelsFn(req LatticeToVoxels) (string, error) {
	args := map[string]any{}
	args["latticeId"] = req.LatticeID
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("lattice_to_voxels", args)
}

// --- Mesh ---

// CreateMesh holds parameters for the create_mesh tool.
// Create an empty mesh. Add vertices and triangles to build geometry. Returns the object ID.
type CreateMesh struct {
	ID string `json:"id,omitempty"`
}

// CreateMeshFn calls the create_mesh MCP tool.
// Create an empty mesh. Add vertices and triangles to build geometry. Returns the object ID.
func (c *Client) CreateMeshFn(req CreateMesh) (string, error) {
	args := map[string]any{}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("create_mesh", args)
}

// MeshAddVertex holds parameters for the mesh_add_vertex tool.
// Add a vertex to a mesh. Returns the vertex index (0-based) for use in triangle creation.
type MeshAddVertex struct {
	MeshID string  `json:"meshId"`
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
	Z      float64 `json:"z"`
}

// MeshAddVertexFn calls the mesh_add_vertex MCP tool.
// Add a vertex to a mesh. Returns the vertex index (0-based) for use in triangle creation.
func (c *Client) MeshAddVertexFn(req MeshAddVertex) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	return c.callTool("mesh_add_vertex", args)
}

// MeshAddTriangle holds parameters for the mesh_add_triangle tool.
// Add a triangle to a mesh using vertex indices. Returns the triangle index.
type MeshAddTriangle struct {
	MeshID string `json:"meshId"`
	A      int    `json:"a"`
	B      int    `json:"b"`
	C      int    `json:"c"`
}

// MeshAddTriangleFn calls the mesh_add_triangle MCP tool.
// Add a triangle to a mesh using vertex indices. Returns the triangle index.
func (c *Client) MeshAddTriangleFn(req MeshAddTriangle) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	args["a"] = req.A
	args["b"] = req.B
	args["c"] = req.C
	return c.callTool("mesh_add_triangle", args)
}

// MeshAddTriangleVertices holds parameters for the mesh_add_triangle_vertices tool.
// Add a triangle to a mesh by specifying three vertex positions directly. The vertices are added automatically. Returns the triangle index.
type MeshAddTriangleVertices struct {
	MeshID string  `json:"meshId"`
	X1     float64 `json:"x1"`
	Y1     float64 `json:"y1"`
	Z1     float64 `json:"z1"`
	X2     float64 `json:"x2"`
	Y2     float64 `json:"y2"`
	Z2     float64 `json:"z2"`
	X3     float64 `json:"x3"`
	Y3     float64 `json:"y3"`
	Z3     float64 `json:"z3"`
}

// MeshAddTriangleVerticesFn calls the mesh_add_triangle_vertices MCP tool.
// Add a triangle to a mesh by specifying three vertex positions directly. The vertices are added automatically. Returns the triangle index.
func (c *Client) MeshAddTriangleVerticesFn(req MeshAddTriangleVertices) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	args["x1"] = req.X1
	args["y1"] = req.Y1
	args["z1"] = req.Z1
	args["x2"] = req.X2
	args["y2"] = req.Y2
	args["z2"] = req.Z2
	args["x3"] = req.X3
	args["y3"] = req.Y3
	args["z3"] = req.Z3
	return c.callTool("mesh_add_triangle_vertices", args)
}

// MeshAddQuad holds parameters for the mesh_add_quad tool.
// Add a quad to a mesh by specifying four vertex positions directly. The vertices are added automatically and two triangles are created. Use bFlipped=true to reverse the winding order. Returns the starting triangle index.
type MeshAddQuad struct {
	MeshID  string  `json:"meshId"`
	X0      float64 `json:"x0"`
	Y0      float64 `json:"y0"`
	Z0      float64 `json:"z0"`
	X1      float64 `json:"x1"`
	Y1      float64 `json:"y1"`
	Z1      float64 `json:"z1"`
	X2      float64 `json:"x2"`
	Y2      float64 `json:"y2"`
	Z2      float64 `json:"z2"`
	X3      float64 `json:"x3"`
	Y3      float64 `json:"y3"`
	Z3      float64 `json:"z3"`
	Flipped *bool   `json:"flipped,omitempty"`
}

// MeshAddQuadFn calls the mesh_add_quad MCP tool.
// Add a quad to a mesh by specifying four vertex positions directly. The vertices are added automatically and two triangles are created. Use bFlipped=true to reverse the winding order. Returns the starting triangle index.
func (c *Client) MeshAddQuadFn(req MeshAddQuad) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	args["x0"] = req.X0
	args["y0"] = req.Y0
	args["z0"] = req.Z0
	args["x1"] = req.X1
	args["y1"] = req.Y1
	args["z1"] = req.Z1
	args["x2"] = req.X2
	args["y2"] = req.Y2
	args["z2"] = req.Z2
	args["x3"] = req.X3
	args["y3"] = req.Y3
	args["z3"] = req.Z3
	if req.Flipped != nil {
		args["flipped"] = *req.Flipped
	}
	return c.callTool("mesh_add_quad", args)
}

// VoxelsToMesh holds parameters for the voxels_to_mesh tool.
// Convert a voxel object to a mesh using marching cubes. Returns a new mesh object ID.
type VoxelsToMesh struct {
	VoxelsID string `json:"voxelsId"`
	ID       string `json:"id,omitempty"`
}

// VoxelsToMeshFn calls the voxels_to_mesh MCP tool.
// Convert a voxel object to a mesh using marching cubes. Returns a new mesh object ID.
func (c *Client) VoxelsToMeshFn(req VoxelsToMesh) (string, error) {
	args := map[string]any{}
	args["voxelsId"] = req.VoxelsID
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("voxels_to_mesh", args)
}

// MeshToVoxels holds parameters for the mesh_to_voxels tool.
// Convert a mesh to voxels. Returns a new voxel object ID.
type MeshToVoxels struct {
	MeshID string `json:"meshId"`
	ID     string `json:"id,omitempty"`
}

// MeshToVoxelsFn calls the mesh_to_voxels MCP tool.
// Convert a mesh to voxels. Returns a new voxel object ID.
func (c *Client) MeshToVoxelsFn(req MeshToVoxels) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("mesh_to_voxels", args)
}

// MeshFromSTL holds parameters for the mesh_from_stl tool.
// Load a mesh from an STL file on disk. Returns the object ID.
type MeshFromSTL struct {
	Path string `json:"path"`
	ID   string `json:"id,omitempty"`
}

// MeshFromSTLFn calls the mesh_from_stl MCP tool.
// Load a mesh from an STL file on disk. Returns the object ID.
func (c *Client) MeshFromSTLFn(req MeshFromSTL) (string, error) {
	args := map[string]any{}
	args["path"] = req.Path
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("mesh_from_stl", args)
}

// MeshTransform holds parameters for the mesh_transform tool.
// Transform a mesh: apply uniform scale and/or translation. Returns a new mesh object ID.
type MeshTransform struct {
	MeshID     string   `json:"meshId"`
	Scale      *float64 `json:"scale,omitempty"`
	TranslateX *float64 `json:"translateX,omitempty"`
	TranslateY *float64 `json:"translateY,omitempty"`
	TranslateZ *float64 `json:"translateZ,omitempty"`
	ID         string   `json:"id,omitempty"`
}

// MeshTransformFn calls the mesh_transform MCP tool.
// Transform a mesh: apply uniform scale and/or translation. Returns a new mesh object ID.
func (c *Client) MeshTransformFn(req MeshTransform) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	if req.Scale != nil {
		args["scale"] = *req.Scale
	}
	if req.TranslateX != nil {
		args["translateX"] = *req.TranslateX
	}
	if req.TranslateY != nil {
		args["translateY"] = *req.TranslateY
	}
	if req.TranslateZ != nil {
		args["translateZ"] = *req.TranslateZ
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("mesh_transform", args)
}

// MeshMirror holds parameters for the mesh_mirror tool.
// Mirror a mesh across a plane defined by a point and normal. Returns a new mesh object ID.
type MeshMirror struct {
	MeshID string  `json:"meshId"`
	PtX    float64 `json:"ptX"`
	PtY    float64 `json:"ptY"`
	PtZ    float64 `json:"ptZ"`
	NX     float64 `json:"nX"`
	NY     float64 `json:"nY"`
	NZ     float64 `json:"nZ"`
	ID     string  `json:"id,omitempty"`
}

// MeshMirrorFn calls the mesh_mirror MCP tool.
// Mirror a mesh across a plane defined by a point and normal. Returns a new mesh object ID.
func (c *Client) MeshMirrorFn(req MeshMirror) (string, error) {
	args := map[string]any{}
	args["meshId"] = req.MeshID
	args["ptX"] = req.PtX
	args["ptY"] = req.PtY
	args["ptZ"] = req.PtZ
	args["nX"] = req.NX
	args["nY"] = req.NY
	args["nZ"] = req.NZ
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("mesh_mirror", args)
}

// MeshAppend holds parameters for the mesh_append tool.
// Append one mesh into another (modifies the target). Returns the target mesh ID.
type MeshAppend struct {
	TargetID string `json:"targetId"`
	SourceID string `json:"sourceId"`
}

// MeshAppendFn calls the mesh_append MCP tool.
// Append one mesh into another (modifies the target). Returns the target mesh ID.
func (c *Client) MeshAppendFn(req MeshAppend) (string, error) {
	args := map[string]any{}
	args["targetId"] = req.TargetID
	args["sourceId"] = req.SourceID
	return c.callTool("mesh_append", args)
}

// --- Primitives ---

// CreateSphere holds parameters for the create_sphere tool.
// Create a sphere voxel object. Returns the object ID.
type CreateSphere struct {
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
	Z      float64 `json:"z"`
	Radius float64 `json:"radius"`
	ID     string  `json:"id,omitempty"`
}

// CreateSphereFn calls the create_sphere MCP tool.
// Create a sphere voxel object. Returns the object ID.
func (c *Client) CreateSphereFn(req CreateSphere) (string, error) {
	args := map[string]any{}
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	args["radius"] = req.Radius
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("create_sphere", args)
}

// CreateBox holds parameters for the create_box tool.
// Create a box (axis-aligned cuboid) from minimum and maximum corner coordinates. Returns the object ID.
type CreateBox struct {
	MinX float64 `json:"minX"`
	MinY float64 `json:"minY"`
	MinZ float64 `json:"minZ"`
	MaxX float64 `json:"maxX"`
	MaxY float64 `json:"maxY"`
	MaxZ float64 `json:"maxZ"`
	ID   string  `json:"id,omitempty"`
}

// CreateBoxFn calls the create_box MCP tool.
// Create a box (axis-aligned cuboid) from minimum and maximum corner coordinates. Returns the object ID.
func (c *Client) CreateBoxFn(req CreateBox) (string, error) {
	args := map[string]any{}
	args["minX"] = req.MinX
	args["minY"] = req.MinY
	args["minZ"] = req.MinZ
	args["maxX"] = req.MaxX
	args["maxY"] = req.MaxY
	args["maxZ"] = req.MaxZ
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("create_box", args)
}

// CreateCylinder holds parameters for the create_cylinder tool.
// Create a cylinder. By default it runs along the +Z axis from (x,y,z) to (x,y,z+height). Pass dirX/dirY/dirZ to orient the axis differently (the vector is normalized automatically). The cylinder has flat end caps. Returns the object ID.
type CreateCylinder struct {
	X      float64  `json:"x"`
	Y      float64  `json:"y"`
	Z      float64  `json:"z"`
	Radius float64  `json:"radius"`
	Height float64  `json:"height"`
	DirX   *float64 `json:"dirX,omitempty"`
	DirY   *float64 `json:"dirY,omitempty"`
	DirZ   *float64 `json:"dirZ,omitempty"`
	ID     string   `json:"id,omitempty"`
}

// CreateCylinderFn calls the create_cylinder MCP tool.
// Create a cylinder. By default it runs along the +Z axis from (x,y,z) to (x,y,z+height). Pass dirX/dirY/dirZ to orient the axis differently (the vector is normalized automatically). The cylinder has flat end caps. Returns the object ID.
func (c *Client) CreateCylinderFn(req CreateCylinder) (string, error) {
	args := map[string]any{}
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	args["radius"] = req.Radius
	args["height"] = req.Height
	if req.DirX != nil {
		args["dirX"] = *req.DirX
	}
	if req.DirY != nil {
		args["dirY"] = *req.DirY
	}
	if req.DirZ != nil {
		args["dirZ"] = *req.DirZ
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("create_cylinder", args)
}

// CreateCapsule holds parameters for the create_capsule tool.
// Create a capsule (a sphere-swept line segment). Returns the object ID.
type CreateCapsule struct {
	X1     float64 `json:"x1"`
	Y1     float64 `json:"y1"`
	Z1     float64 `json:"z1"`
	X2     float64 `json:"x2"`
	Y2     float64 `json:"y2"`
	Z2     float64 `json:"z2"`
	Radius float64 `json:"radius"`
	ID     string  `json:"id,omitempty"`
}

// CreateCapsuleFn calls the create_capsule MCP tool.
// Create a capsule (a sphere-swept line segment). Returns the object ID.
func (c *Client) CreateCapsuleFn(req CreateCapsule) (string, error) {
	args := map[string]any{}
	args["x1"] = req.X1
	args["y1"] = req.Y1
	args["z1"] = req.Z1
	args["x2"] = req.X2
	args["y2"] = req.Y2
	args["z2"] = req.Z2
	args["radius"] = req.Radius
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("create_capsule", args)
}

// CreateTorus holds parameters for the create_torus tool.
// Create a torus (donut shape) by revolving a circle around the Z axis. Returns the object ID.
type CreateTorus struct {
	MajorRadius float64  `json:"majorRadius"`
	MinorRadius float64  `json:"minorRadius"`
	X           *float64 `json:"x,omitempty"`
	Y           *float64 `json:"y,omitempty"`
	Z           *float64 `json:"z,omitempty"`
	ID          string   `json:"id,omitempty"`
}

// CreateTorusFn calls the create_torus MCP tool.
// Create a torus (donut shape) by revolving a circle around the Z axis. Returns the object ID.
func (c *Client) CreateTorusFn(req CreateTorus) (string, error) {
	args := map[string]any{}
	args["majorRadius"] = req.MajorRadius
	args["minorRadius"] = req.MinorRadius
	if req.X != nil {
		args["x"] = *req.X
	}
	if req.Y != nil {
		args["y"] = *req.Y
	}
	if req.Z != nil {
		args["z"] = *req.Z
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("create_torus", args)
}

// --- Query ---

// GetBoundingBox holds parameters for the get_bounding_box tool.
// Get the axis-aligned bounding box of any object. Returns min/max corners in mm. Retries internally with exponential backoff if the object was just created/transformed and the internal mesh conversion is not yet settled.
type GetBoundingBox struct {
	ObjectID string `json:"objectId"`
}

// GetBoundingBoxFn calls the get_bounding_box MCP tool.
// Get the axis-aligned bounding box of any object. Returns min/max corners in mm. Retries internally with exponential backoff if the object was just created/transformed and the internal mesh conversion is not yet settled.
func (c *Client) GetBoundingBoxFn(req GetBoundingBox) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	return c.callTool("get_bounding_box", args)
}

// GetVolume holds parameters for the get_volume tool.
// Calculate the volume and bounding box of a voxel object. Retries internally with exponential backoff if the object was just created/transformed.
type GetVolume struct {
	ObjectID string `json:"objectId"`
}

// GetVolumeFn calls the get_volume MCP tool.
// Calculate the volume and bounding box of a voxel object. Retries internally with exponential backoff if the object was just created/transformed.
func (c *Client) GetVolumeFn(req GetVolume) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	return c.callTool("get_volume", args)
}

// GetMeshInfo holds parameters for the get_mesh_info tool.
// Get information about a mesh: vertex count, triangle count, bounding box.
type GetMeshInfo struct {
	ObjectID string `json:"objectId"`
}

// GetMeshInfoFn calls the get_mesh_info MCP tool.
// Get information about a mesh: vertex count, triangle count, bounding box.
func (c *Client) GetMeshInfoFn(req GetMeshInfo) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	return c.callTool("get_mesh_info", args)
}

// PointInside holds parameters for the point_inside tool.
// Check if a 3D point is inside a voxel object.
type PointInside struct {
	ObjectID string  `json:"objectId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
}

// PointInsideFn calls the point_inside MCP tool.
// Check if a 3D point is inside a voxel object.
func (c *Client) PointInsideFn(req PointInside) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	return c.callTool("point_inside", args)
}

// SurfaceNormal holds parameters for the surface_normal tool.
// Get the surface normal vector at a point on a voxel object's surface.
type SurfaceNormal struct {
	ObjectID string  `json:"objectId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
}

// SurfaceNormalFn calls the surface_normal MCP tool.
// Get the surface normal vector at a point on a voxel object's surface.
func (c *Client) SurfaceNormalFn(req SurfaceNormal) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	return c.callTool("surface_normal", args)
}

// ClosestPoint holds parameters for the closest_point tool.
// Find the closest point on a voxel object's surface to a given point.
type ClosestPoint struct {
	ObjectID string  `json:"objectId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
}

// ClosestPointFn calls the closest_point MCP tool.
// Find the closest point on a voxel object's surface to a given point.
func (c *Client) ClosestPointFn(req ClosestPoint) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	return c.callTool("closest_point", args)
}

// ListObjects holds parameters for the list_objects tool.
// List all objects in the current session with their IDs, types, and descriptions.
type ListObjects struct {
}

// ListObjectsFn calls the list_objects MCP tool.
// List all objects in the current session with their IDs, types, and descriptions.
func (c *Client) ListObjectsFn(req ListObjects) (string, error) {
	args := map[string]any{}
	return c.callTool("list_objects", args)
}

// DeleteObject holds parameters for the delete_object tool.
// Delete an object from the session. Frees memory and removes the object from the registry.
type DeleteObject struct {
	ObjectID string `json:"objectId"`
}

// DeleteObjectFn calls the delete_object MCP tool.
// Delete an object from the session. Frees memory and removes the object from the registry.
func (c *Client) DeleteObjectFn(req DeleteObject) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	return c.callTool("delete_object", args)
}

// GetVoxelDimensions holds parameters for the get_voxel_dimensions tool.
// Get the voxel dimensions (grid size) of a voxel object.
type GetVoxelDimensions struct {
	ObjectID string `json:"objectId"`
}

// GetVoxelDimensionsFn calls the get_voxel_dimensions MCP tool.
// Get the voxel dimensions (grid size) of a voxel object.
func (c *Client) GetVoxelDimensionsFn(req GetVoxelDimensions) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	return c.callTool("get_voxel_dimensions", args)
}

// VoxelsIsEmpty holds parameters for the voxels_is_empty tool.
// Check if a voxel object is empty (contains no volume). Useful for detecting failed operations — e.g. an intersection that produced no overlap, or a subtraction that removed all material.
type VoxelsIsEmpty struct {
	ObjectID string `json:"objectId"`
}

// VoxelsIsEmptyFn calls the voxels_is_empty MCP tool.
// Check if a voxel object is empty (contains no volume). Useful for detecting failed operations — e.g. an intersection that produced no overlap, or a subtraction that removed all material.
func (c *Client) VoxelsIsEmptyFn(req VoxelsIsEmpty) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	return c.callTool("voxels_is_empty", args)
}

// VoxelsMemUsage holds parameters for the voxels_mem_usage tool.
// Get the memory usage of a voxel object in bytes. Useful for monitoring memory consumption when building complex models.
type VoxelsMemUsage struct {
	ObjectID string `json:"objectId"`
}

// VoxelsMemUsageFn calls the voxels_mem_usage MCP tool.
// Get the memory usage of a voxel object in bytes. Useful for monitoring memory consumption when building complex models.
func (c *Client) VoxelsMemUsageFn(req VoxelsMemUsage) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	return c.callTool("voxels_mem_usage", args)
}

// VoxelsIsEqual holds parameters for the voxels_is_equal tool.
// Compare two voxel objects for equality. Returns true if they contain the same voxel data. Useful for verifying that a transform or round-trip preserved the shape.
type VoxelsIsEqual struct {
	ObjectIDA string `json:"objectIdA"`
	ObjectIDB string `json:"objectIdB"`
}

// VoxelsIsEqualFn calls the voxels_is_equal MCP tool.
// Compare two voxel objects for equality. Returns true if they contain the same voxel data. Useful for verifying that a transform or round-trip preserved the shape.
func (c *Client) VoxelsIsEqualFn(req VoxelsIsEqual) (string, error) {
	args := map[string]any{}
	args["objectIdA"] = req.ObjectIDA
	args["objectIdB"] = req.ObjectIDB
	return c.callTool("voxels_is_equal", args)
}

// RayCast holds parameters for the ray_cast tool.
// Cast a ray from a point in a given direction and find where it hits the surface of a voxel object. Useful for measuring wall thickness, checking bore clearance, and probing internal geometry. Returns the hit point and the distance from the origin, or an error if no intersection is found.
type RayCast struct {
	ObjectID string  `json:"objectId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
	DirX     float64 `json:"dirX"`
	DirY     float64 `json:"dirY"`
	DirZ     float64 `json:"dirZ"`
}

// RayCastFn calls the ray_cast MCP tool.
// Cast a ray from a point in a given direction and find where it hits the surface of a voxel object. Useful for measuring wall thickness, checking bore clearance, and probing internal geometry. Returns the hit point and the distance from the origin, or an error if no intersection is found.
func (c *Client) RayCastFn(req RayCast) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	args["dirX"] = req.DirX
	args["dirY"] = req.DirY
	args["dirZ"] = req.DirZ
	return c.callTool("ray_cast", args)
}

// MeasureThickness holds parameters for the measure_thickness tool.
// Cast a ray from a point in both +direction and -direction and report both hit points and the total span between them. Measures the through-thickness of the object along the ray axis (surface to surface through the interior, which may cross internal cavities). For local wall thickness of a shell, place the origin inside the wall material and note that the total span includes all internal voids.
type MeasureThickness struct {
	ObjectID string  `json:"objectId"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
	DirX     float64 `json:"dirX"`
	DirY     float64 `json:"dirY"`
	DirZ     float64 `json:"dirZ"`
}

// MeasureThicknessFn calls the measure_thickness MCP tool.
// Cast a ray from a point in both +direction and -direction and report both hit points and the total span between them. Measures the through-thickness of the object along the ray axis (surface to surface through the interior, which may cross internal cavities). For local wall thickness of a shell, place the origin inside the wall material and note that the total span includes all internal voids.
func (c *Client) MeasureThicknessFn(req MeasureThickness) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["x"] = req.X
	args["y"] = req.Y
	args["z"] = req.Z
	args["dirX"] = req.DirX
	args["dirY"] = req.DirY
	args["dirZ"] = req.DirZ
	return c.callTool("measure_thickness", args)
}

// DuplicateObject holds parameters for the duplicate_object tool.
// Create a duplicate (deep copy) of an existing object. Works with voxel and mesh objects. Returns the new object ID.
type DuplicateObject struct {
	ObjectID string `json:"objectId"`
	ID       string `json:"id,omitempty"`
}

// DuplicateObjectFn calls the duplicate_object MCP tool.
// Create a duplicate (deep copy) of an existing object. Works with voxel and mesh objects. Returns the new object ID.
func (c *Client) DuplicateObjectFn(req DuplicateObject) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("duplicate_object", args)
}

// DeleteObjects holds parameters for the delete_objects tool.
// Delete multiple objects from the session in one call. Useful for cleaning up intermediate objects after a complex build. Returns the count of objects actually deleted.
type DeleteObjects struct {
	ObjectIDs []string `json:"objectIds"`
	KeepOnly  *bool    `json:"keepOnly,omitempty"`
}

// DeleteObjectsFn calls the delete_objects MCP tool.
// Delete multiple objects from the session in one call. Useful for cleaning up intermediate objects after a complex build. Returns the count of objects actually deleted.
func (c *Client) DeleteObjectsFn(req DeleteObjects) (string, error) {
	args := map[string]any{}
	args["objectIds"] = req.ObjectIDs
	if req.KeepOnly != nil {
		args["keepOnly"] = *req.KeepOnly
	}
	return c.callTool("delete_objects", args)
}

// --- Render ---

// RenderToImage holds parameters for the render_to_image tool.
// Render an object to a PNG image using an isometric projection with Lambertian shading. The agent can use this to visually inspect geometry. Returns the file path of the rendered image.
type RenderToImage struct {
	ObjectID        string `json:"objectId"`
	Path            string `json:"path"`
	Width           *int   `json:"width,omitempty"`
	Height          *int   `json:"height,omitempty"`
	BackgroundColor string `json:"backgroundColor,omitempty"`
	ObjectColor     string `json:"objectColor,omitempty"`
}

// RenderToImageFn calls the render_to_image MCP tool.
// Render an object to a PNG image using an isometric projection with Lambertian shading. The agent can use this to visually inspect geometry. Returns the file path of the rendered image.
func (c *Client) RenderToImageFn(req RenderToImage) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["path"] = req.Path
	if req.Width != nil {
		args["width"] = *req.Width
	}
	if req.Height != nil {
		args["height"] = *req.Height
	}
	if req.BackgroundColor != "" {
		args["backgroundColor"] = req.BackgroundColor
	}
	if req.ObjectColor != "" {
		args["objectColor"] = req.ObjectColor
	}
	return c.callTool("render_to_image", args)
}

// RenderSlice holds parameters for the render_slice tool.
// Render a Z-slice of a voxel object to a PNG image. Shows the cross-section at a specific height. Returns the file path.
type RenderSlice struct {
	VoxelsID  string  `json:"voxelsId"`
	ZPosition float64 `json:"zPosition"`
	Path      string  `json:"path"`
	Mode      string  `json:"mode,omitempty"`
}

// RenderSliceFn calls the render_slice MCP tool.
// Render a Z-slice of a voxel object to a PNG image. Shows the cross-section at a specific height. Returns the file path.
func (c *Client) RenderSliceFn(req RenderSlice) (string, error) {
	args := map[string]any{}
	args["voxelsId"] = req.VoxelsID
	args["zPosition"] = req.ZPosition
	args["path"] = req.Path
	if req.Mode != "" {
		args["mode"] = req.Mode
	}
	return c.callTool("render_slice", args)
}

// --- Session ---

// Init holds parameters for the picogk_init tool.
// Initialize the PicoGK geometry kernel. Must be called before any other tool. Sets the voxel resolution in millimeters. Smaller values = higher resolution but more memory. Typical range: 0.1mm (fine) to 5.0mm (coarse).
type Init struct {
	VoxelSizeMM *float64 `json:"voxelSizeMM,omitempty"`
}

// InitFn calls the picogk_init MCP tool.
// Initialize the PicoGK geometry kernel. Must be called before any other tool. Sets the voxel resolution in millimeters. Smaller values = higher resolution but more memory. Typical range: 0.1mm (fine) to 5.0mm (coarse).
func (c *Client) InitFn(req Init) (string, error) {
	args := map[string]any{}
	if req.VoxelSizeMM != nil {
		args["voxelSizeMM"] = *req.VoxelSizeMM
	}
	return c.callTool("picogk_init", args)
}

// Info holds parameters for the picogk_info tool.
// Get information about the PicoGK library and current session state. Returns version, memory usage, and counts of allocated objects.
type Info struct {
}

// InfoFn calls the picogk_info MCP tool.
// Get information about the PicoGK library and current session state. Returns version, memory usage, and counts of allocated objects.
func (c *Client) InfoFn(req Info) (string, error) {
	args := map[string]any{}
	return c.callTool("picogk_info", args)
}

// Shutdown holds parameters for the picogk_shutdown tool.
// Shut down the PicoGK session and release all resources. All object references become invalid after this call.
type Shutdown struct {
}

// ShutdownFn calls the picogk_shutdown MCP tool.
// Shut down the PicoGK session and release all resources. All object references become invalid after this call.
func (c *Client) ShutdownFn(req Shutdown) (string, error) {
	args := map[string]any{}
	return c.callToolNoParse("picogk_shutdown", args)
}

// --- Transforms ---

// Offset holds parameters for the offset tool.
// Offset a voxel surface outward (positive) or inward (negative) by a distance. Use for thickening, thinning, or creating clearance. Returns a new object ID.
type Offset struct {
	ObjectID string  `json:"objectId"`
	Distance float64 `json:"distance"`
	ID       string  `json:"id,omitempty"`
}

// OffsetFn calls the offset MCP tool.
// Offset a voxel surface outward (positive) or inward (negative) by a distance. Use for thickening, thinning, or creating clearance. Returns a new object ID.
func (c *Client) OffsetFn(req Offset) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["distance"] = req.Distance
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("offset", args)
}

// DoubleOffset holds parameters for the double_offset tool.
// Offset a voxel surface twice: first by offset1, then by offset2. Enables precise morphological operations not possible with a single offset — e.g. offset out by 2mm then back by 1.5mm to remove thin features while preserving wall thickness. Returns a new object ID.
type DoubleOffset struct {
	ObjectID string  `json:"objectId"`
	Offset1  float64 `json:"offset1"`
	Offset2  float64 `json:"offset2"`
	ID       string  `json:"id,omitempty"`
}

// DoubleOffsetFn calls the double_offset MCP tool.
// Offset a voxel surface twice: first by offset1, then by offset2. Enables precise morphological operations not possible with a single offset — e.g. offset out by 2mm then back by 1.5mm to remove thin features while preserving wall thickness. Returns a new object ID.
func (c *Client) DoubleOffsetFn(req DoubleOffset) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["offset1"] = req.Offset1
	args["offset2"] = req.Offset2
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("double_offset", args)
}

// OverOffset holds parameters for the over_offset tool.
// Offset a voxel surface by a first distance, then settle the surface at a specified final distance from the original. More precise than fillet: lets you say 'offset by 3mm, then move the surface to exactly 0.5mm from where it started.' Useful for controlled material removal. Returns a new object ID.
type OverOffset struct {
	ObjectID         string   `json:"objectId"`
	FirstOffset      float64  `json:"firstOffset"`
	FinalSurfaceDist *float64 `json:"finalSurfaceDist,omitempty"`
	ID               string   `json:"id,omitempty"`
}

// OverOffsetFn calls the over_offset MCP tool.
// Offset a voxel surface by a first distance, then settle the surface at a specified final distance from the original. More precise than fillet: lets you say 'offset by 3mm, then move the surface to exactly 0.5mm from where it started.' Useful for controlled material removal. Returns a new object ID.
func (c *Client) OverOffsetFn(req OverOffset) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["firstOffset"] = req.FirstOffset
	if req.FinalSurfaceDist != nil {
		args["finalSurfaceDist"] = *req.FinalSurfaceDist
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("over_offset", args)
}

// Smooth holds parameters for the smooth tool.
// Smooth/round a voxel surface by applying triple offset. Good for removing sharp edges. Returns a new object ID.
type Smooth struct {
	ObjectID string  `json:"objectId"`
	Distance float64 `json:"distance"`
	ID       string  `json:"id,omitempty"`
}

// SmoothFn calls the smooth MCP tool.
// Smooth/round a voxel surface by applying triple offset. Good for removing sharp edges. Returns a new object ID.
func (c *Client) SmoothFn(req Smooth) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["distance"] = req.Distance
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("smooth", args)
}

// Trim holds parameters for the trim tool.
// Trim a voxel object to fit within a bounding box. Everything outside the box is removed. Returns a new object ID.
type Trim struct {
	ObjectID string  `json:"objectId"`
	MinX     float64 `json:"minX"`
	MinY     float64 `json:"minY"`
	MinZ     float64 `json:"minZ"`
	MaxX     float64 `json:"maxX"`
	MaxY     float64 `json:"maxY"`
	MaxZ     float64 `json:"maxZ"`
	ID       string  `json:"id,omitempty"`
}

// TrimFn calls the trim MCP tool.
// Trim a voxel object to fit within a bounding box. Everything outside the box is removed. Returns a new object ID.
func (c *Client) TrimFn(req Trim) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["minX"] = req.MinX
	args["minY"] = req.MinY
	args["minZ"] = req.MinZ
	args["maxX"] = req.MaxX
	args["maxY"] = req.MaxY
	args["maxZ"] = req.MaxZ
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("trim", args)
}

// Shell holds parameters for the shell tool.
// Create a hollow shell from a voxel object. Both positive and negative offsets are applied. Returns a new object ID.
type Shell struct {
	ObjectID    string   `json:"objectId"`
	InnerOffset float64  `json:"innerOffset"`
	OuterOffset float64  `json:"outerOffset"`
	Smooth      *float64 `json:"smooth,omitempty"`
	ID          string   `json:"id,omitempty"`
}

// ShellFn calls the shell MCP tool.
// Create a hollow shell from a voxel object. Both positive and negative offsets are applied. Returns a new object ID.
func (c *Client) ShellFn(req Shell) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["innerOffset"] = req.InnerOffset
	args["outerOffset"] = req.OuterOffset
	if req.Smooth != nil {
		args["smooth"] = *req.Smooth
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("shell", args)
}

// Fillet holds parameters for the fillet tool.
// Fillets (rounds) the surface of a voxel object. Same as smooth but semantically for rounding edges. Returns a new object ID.
type Fillet struct {
	ObjectID string  `json:"objectId"`
	Radius   float64 `json:"radius"`
	ID       string  `json:"id,omitempty"`
}

// FilletFn calls the fillet MCP tool.
// Fillets (rounds) the surface of a voxel object. Same as smooth but semantically for rounding edges. Returns a new object ID.
func (c *Client) FilletFn(req Fillet) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["radius"] = req.Radius
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("fillet", args)
}

// ProjectZSlice holds parameters for the project_z_slice tool.
// Project voxels onto a Z-plane (top-down silhouette). Useful for creating 2D cross-sections. Returns a new object ID.
type ProjectZSlice struct {
	ObjectID string  `json:"objectId"`
	StartZ   float64 `json:"startZ"`
	EndZ     float64 `json:"endZ"`
	ID       string  `json:"id,omitempty"`
}

// ProjectZSliceFn calls the project_z_slice MCP tool.
// Project voxels onto a Z-plane (top-down silhouette). Useful for creating 2D cross-sections. Returns a new object ID.
func (c *Client) ProjectZSliceFn(req ProjectZSlice) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["startZ"] = req.StartZ
	args["endZ"] = req.EndZ
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("project_z_slice", args)
}

// TransformVoxels holds parameters for the transform_voxels tool.
// Transform a voxel object by translating, rotating, and/or scaling it. Rotations are applied first (around the world origin 0,0,0 — not the object's center), then translation. To rotate an object in place, first translate it to the origin, rotate, then translate back. Uses native PicoGK signed-distance-field re-rasterization (no expensive mesh round-trip), so it is efficient for large voxel fields. Returns a new object ID.
type TransformVoxels struct {
	ObjectID   string   `json:"objectId"`
	TranslateX *float64 `json:"translateX,omitempty"`
	TranslateY *float64 `json:"translateY,omitempty"`
	TranslateZ *float64 `json:"translateZ,omitempty"`
	RotateX    *float64 `json:"rotateX,omitempty"`
	RotateY    *float64 `json:"rotateY,omitempty"`
	RotateZ    *float64 `json:"rotateZ,omitempty"`
	Scale      *float64 `json:"scale,omitempty"`
	ID         string   `json:"id,omitempty"`
}

// TransformVoxelsFn calls the transform_voxels MCP tool.
// Transform a voxel object by translating, rotating, and/or scaling it. Rotations are applied first (around the world origin 0,0,0 — not the object's center), then translation. To rotate an object in place, first translate it to the origin, rotate, then translate back. Uses native PicoGK signed-distance-field re-rasterization (no expensive mesh round-trip), so it is efficient for large voxel fields. Returns a new object ID.
func (c *Client) TransformVoxelsFn(req TransformVoxels) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	if req.TranslateX != nil {
		args["translateX"] = *req.TranslateX
	}
	if req.TranslateY != nil {
		args["translateY"] = *req.TranslateY
	}
	if req.TranslateZ != nil {
		args["translateZ"] = *req.TranslateZ
	}
	if req.RotateX != nil {
		args["rotateX"] = *req.RotateX
	}
	if req.RotateY != nil {
		args["rotateY"] = *req.RotateY
	}
	if req.RotateZ != nil {
		args["rotateZ"] = *req.RotateZ
	}
	if req.Scale != nil {
		args["scale"] = *req.Scale
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("transform_voxels", args)
}

// CircularPattern holds parameters for the circular_pattern tool.
// Create a circular (polar) pattern of a voxel object: rotate copies around an axis through a center point and union them into a single result. Uses SDF re-rasterization (no mesh round-trips) for each copy. Returns a new object ID containing all copies combined. Example: 4 bolt holes around a flange center at 90° intervals.
type CircularPattern struct {
	ObjectID   string   `json:"objectId"`
	Count      int      `json:"count"`
	TotalAngle *float64 `json:"totalAngle,omitempty"`
	CenterX    *float64 `json:"centerX,omitempty"`
	CenterY    *float64 `json:"centerY,omitempty"`
	CenterZ    *float64 `json:"centerZ,omitempty"`
	AxisX      *float64 `json:"axisX,omitempty"`
	AxisY      *float64 `json:"axisY,omitempty"`
	AxisZ      *float64 `json:"axisZ,omitempty"`
	ID         string   `json:"id,omitempty"`
}

// CircularPatternFn calls the circular_pattern MCP tool.
// Create a circular (polar) pattern of a voxel object: rotate copies around an axis through a center point and union them into a single result. Uses SDF re-rasterization (no mesh round-trips) for each copy. Returns a new object ID containing all copies combined. Example: 4 bolt holes around a flange center at 90° intervals.
func (c *Client) CircularPatternFn(req CircularPattern) (string, error) {
	args := map[string]any{}
	args["objectId"] = req.ObjectID
	args["count"] = req.Count
	if req.TotalAngle != nil {
		args["totalAngle"] = *req.TotalAngle
	}
	if req.CenterX != nil {
		args["centerX"] = *req.CenterX
	}
	if req.CenterY != nil {
		args["centerY"] = *req.CenterY
	}
	if req.CenterZ != nil {
		args["centerZ"] = *req.CenterZ
	}
	if req.AxisX != nil {
		args["axisX"] = *req.AxisX
	}
	if req.AxisY != nil {
		args["axisY"] = *req.AxisY
	}
	if req.AxisZ != nil {
		args["axisZ"] = *req.AxisZ
	}
	if req.ID != "" {
		args["id"] = req.ID
	}
	return c.callTool("circular_pattern", args)
}
