// Code generated by scripts/generate-go-mcp-sdk.py — DO NOT EDIT.


package gopicogk

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os/exec"
	"sync"
)

// Client manages a connection to the PicoGK MCP server.
// It launches the server as a subprocess and communicates via JSON-RPC over stdio.
//
// Usage:
//	client, err := gopicogk.NewClient(ctx, "/path/to/PicoGK.Mcp")
//	defer client.Close(ctx)
//	// Initialize the geometry kernel
//	res, err := client.PicogkInit(ctx, gopicogk.PicogkInitRequest{VoxelSizeMM: 0.5})
//	// Create a sphere, subtract a box, export STL...
type Client struct {
	cmd       *exec.Cmd
	stdin     io.WriteCloser
	stdout    *bufio.Reader
	mu        sync.Mutex
	msgID     int
	serverBin string
}

// NewClient launches the PicoGK MCP server binary and returns a Client.
// The serverBin path should point to the self-contained PicoGK.Mcp executable.
func NewClient(ctx context.Context, serverBin string) (*Client, error) {
	cmd := exec.CommandContext(ctx, serverBin)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdin pipe: %w", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("creating stdout pipe: %w", err)
	}
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("starting server: %w", err)
	}
	c := &Client{
		cmd:       cmd,
		stdin:     stdin,
		stdout:    bufio.NewReader(stdout),
		serverBin: serverBin,
	}
	// Perform MCP initialize handshake
	if err := c.initialize(ctx); err != nil {
		cmd.Process.Kill()
		return nil, fmt.Errorf("initialize handshake: %w", err)
	}
	return c, nil
}

// Close shuts down the MCP server process.
func (c *Client) Close(ctx context.Context) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.stdin != nil {
		c.stdin.Close()
	}
	if c.cmd != nil && c.cmd.Process != nil {
		done := make(chan struct{})
		go func() {
			c.cmd.Wait()
			close(done)
		}()
		select {
		case <-done:
		case <-ctx.Done():
			c.cmd.Process.Kill()
			<-done
		}
	}
	return nil
}

// --- JSON-RPC internals ---

type jsonRPCRequest struct {
	JSONRPC string      `json:"jsonrpc"`
	ID       int         `json:"id"`
	Method   string      `json:"method"`
	Params   interface{} `json:"params"`
}

type jsonRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID       int             `json:"id"`
	Result   json.RawMessage `json:"result,omitempty"`
	Error    *jsonRPCErr     `json:"error,omitempty"`
}

type jsonRPCErr struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type toolResult struct {
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content"`
	IsError bool `json:"isError"`
}

func (c *Client) initialize(ctx context.Context) error {
	req := map[string]interface{}{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "initialize",
		"params": map[string]interface{}{
			"protocolVersion": "2024-11-05",
			"capabilities":   map[string]interface{}{},
			"clientInfo": map[string]interface{}{
				"name":    "gopicogk",
				"version": "1.0.0",
			},
		},
	}
	_, err := c.call(ctx, req)
	if err != nil {
		return err
	}
	// Send initialized notification
	notif := map[string]interface{}{
		"jsonrpc": "2.0",
		"method":  "notifications/initialized",
	}
	return c.send(notif)
}

func (c *Client) nextID() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.msgID++
	return c.msgID
}

func (c *Client) send(msg interface{}) error {
	data, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshaling: %w", err)
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	_, err = c.stdin.Write(append(data, '\n'))
	return err
}

func (c *Client) call(ctx context.Context, req interface{}) (json.RawMessage, error) {
	if err := c.send(req); err != nil {
		return nil, err
	}
	// Read response line
	line, err := c.stdout.ReadString('\n')
	if err != nil {
		return nil, fmt.Errorf("reading response: %w", err)
	}
	var resp jsonRPCResponse
	if err := json.Unmarshal([]byte(line), &resp); err != nil {
		return nil, fmt.Errorf("parsing response: %w (line: %q)", err, line)
	}
	if resp.Error != nil {
		return nil, fmt.Errorf("server error [%d]: %s", resp.Error.Code, resp.Error.Message)
	}
	return resp.Result, nil
}

// callTool invokes an MCP tool by name and returns the text content of the response.
func (c *Client) callTool(ctx context.Context, toolName string, args map[string]interface{}) (string, error) {
	req := map[string]interface{}{
		"jsonrpc": "2.0",
		"id":      c.nextID(),
		"method":  "tools/call",
		"params": map[string]interface{}{
			"name":      toolName,
			"arguments": args,
		},
	}
	result, err := c.call(ctx, req)
	if err != nil {
		return "", err
	}
	var tr toolResult
	if err := json.Unmarshal(result, &tr); err != nil {
		return "", fmt.Errorf("parsing tool result: %w", err)
	}
	var text string
	for _, item := range tr.Content {
		if item.Type == "text" {
			text += item.Text
		}
	}
	if tr.IsError {
		return text, fmt.Errorf("tool error: %s", text)
	}
	return text, nil
}
